### ISSUE TITLE
Modify the contents of the snippet (including place holders) before expansion

### ISSUE THREAD

**Issue by tpoliaw** [SirVer/ultisnips#1007]
Is it possible to create new place holders programmatically during a interpolation or pre-expand action?

**Expected behavior:**
I would like to use the regex based matching to expand the snippet differently depending on the match. eg with a snippet such as 

    snippet (\d+)xdiv "multiple divs" r
    # not sure what would go here
    endsnippet

Then it could be used such that 

    3xdiv<tab>

would be equivalent to 

    <div id=${1}/>
    <div id=${2}/>
    <div id=${3}/>

etc and the multiple placeholders could be filled as normal.

**Actual behavior:**

As far as I could see from the documentation, this is not yet possible although I'm happy to be shown I'm wrong. Possibly something to do with `expand_anon`?

**Comment by lacygoill** [comment]
Try to write the following code in the relevant snippets file:

    global !p
    def generate_divs(snip):
        n = snip.buffer[snip.line].split('x', 1)[0]
        n = int(n)
        anon_snip_body = ''
        for i in range(1, n+1):
            anon_snip_body += '<div id=${' + str(i) + '}/>\n'

        snip.buffer[snip.line] = ''
        snip.expand_anon(anon_snip_body)
    endglobal

    pre_expand "generate_divs(snip)"
    snippet "\d+xdiv" "multiple divs" br
    endsnippet

Here's the result:

![gif](https://user-images.githubusercontent.com/8505073/50718259-1ed22600-108e-11e9-96d3-e8af33851c49.gif)

If you have other usage questions, try https://vi.stackexchange.com/ and tag your question with `plugin-ultisnips`.

**Comment by tpoliaw** [comment]
Perfect @lacygoill, exactly what I was after. Thanks.

**Comment by adriaanzon** [comment]
@lacygoill I also use this technique in my plugin vim-emmet-ultisnips, but I experienced issues with it on Neovim. The expanded snippet ends up on the previous line when triggering the snippet in a split window of the same file. I made a screen recording to demonstrate the issue here: https://github.com/adriaanzon/vim-emmet-ultisnips/issues/4 

The same happens when I try it with the snippet you posted here.

Do you have any idea what could be causing this?
