### ISSUE TITLE
Auto-trigger needs two undos

### ISSUE THREAD

**Issue by jchtt** [SirVer/ultisnips#1011]
**Expected behavior:**
After an auto-triggered snippet has been expanded, performing one undo should revert the expansion.

**Actual behavior:**
The first undo operation does not do anything, you need to hit it twice.

**Steps to reproduce**
Define a simple auto-triggered snippet like
```
snippet test "test" A
this is inserted automatically
endsnippet
```
Then, type test in buffer and hit `<C-o>u`. Nothing happens. Hit `<C-o>u` again and it reverts to test.

-----

- **Operating System**: Archlinux
- **Vim Version**:
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 13 2018 14:59:01)
Included patches: 1-279
- **UltiSnips Version**: 6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba
- **Python inside Vim**: 3.7.0
- **Docker repo/vimrc**: None, please see above.

**Comment by SirVer** [comment]
Can't repro, works for me at 4f4d500e21b307894490b24413d663c1c124307f on Mac OS and Linux.

keystrokes in a new buffer:
`itest` -> autotrigger is expanded
`<c-o>u` -> cursor jumps to column 5 again, but text stays unchanged. This is as expected to me, because only with the next edit command will Vim flush its buffer. typing any character, for example `e` yields `teste` in the line.

Please post a video of the problem, ideally with the keystrokes displayed.

**Comment by Neightro** [comment]
Experiencing this issue on Neovim 0.6.1 with ultisnips 2a06971. I'm using Python 3.10.2 with pynvim 0.4.3. My config is pretty heavily customized, so it's possible that this issue is caused by a conflict with some other plugin. I'll test with a minimal .vimrc if I get the chance, and try to narrow it down.
