### ISSUE TITLE
Question: is it possible to always choose first snippet from the list if multiple are matching?

### ISSUE THREAD

**Issue by dominikduda** [SirVer/ultisnips#1012]
Sorry, but I could not find this information anywhere.

When the following occurs:
![image](https://user-images.githubusercontent.com/14922999/45118224-3806ac80-b158-11e8-9830-19997d2dcb0a.png)
I would like to always choose number `1:` and just never prompt me for choosing. Is there such an option?

**Comment by lacygoill** [comment]
Try to add this mapping in your `vimrc`:

    ino <key> <c-r>=UltiSnips#ListSnippets()<cr>1<cr>

Replace `<key>` with whatever keysequence you want to use. But make sure it's not assigned to `g:UltiSnipsListSnippets`, otherwise your mapping would be overwritten by `UltiSnips`.

If you have other usage questions, try to visit https://vi.stackexchange.com/ and tag your question with [plugin-ultisnips](https://vi.stackexchange.com/questions/tagged/plugin-ultisnips).
