### ISSUE TITLE
Run python code several times

### ISSUE THREAD

**Issue by solomonwzs** [SirVer/ultisnips#1021]
**Expected behavior:**
Run the python code only once time

**Actual behavior:**
Run the python code several times

**Steps to reproduce**

I create a snip like this:
```
snippet dd "debug" b
`!p
with open('/tmp/1.txt', 'a') as fd:
	fd.write('1\n')`DD
endsnippet
```
when I expand the code, I found it prints two lines to file `/tmp/1.txt`

-----

- **Operating System**: Archlinux
- **Vim Version**: VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 12 2018 23:25:13)
Included patches: 1-374
- **UltiSnips Version**: 6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba
- **Python inside Vim**: 3.7.0
- **Docker repo/vimrc**:

**Comment by lacygoill** [comment]
Have a look at [this video](https://www.youtube.com/watch?v=JJQYwt6Diro&t=184), where the author of `UltiSnips` explains that:

> UltiSnips evaluates each text object that  might have a dependency on some types of text multiple times, to make sure that all dependencies are properly updated.

There's no way around that. However, you can make your interpolation return the string `'DD'` (since you write these characters just after in the snippet), and check the value of `snip.c`. If the latter is not empty, it means that the python interpolation has already been performed at least once.

Applied to your snippet, it gives:

    snippet dd "debug" b
    `!p if not snip.c:
            with open('/tmp/1.txt', 'a') as fd:
                    fd.write('1\n')
            snip.rv = 'DD'
            `
    endsnippet

Which works as you want:

![gif](https://user-images.githubusercontent.com/8505073/50720953-83ee4180-10b7-11e9-9f1b-476318b8e308.gif)

If you have other usage questions, try to visit https://vi.stackexchange.com/ and tag your question with [plugin-ultisnips](https://vi.stackexchange.com/questions/tagged/plugin-ultisnips).
