### ISSUE TITLE
Custom expand trigger disables <tab> in insert mode

### ISSUE THREAD

**Issue by nerfologist** [SirVer/ultisnips#1022]
Hello, I'm submitting this anomaly which I experience both in MacVim and neovim; I was able to reproduce it with a very simple custom vimrc.

**Expected behavior:**
- I load vim or neovim with only the ultisnips plugin enabled
- I set a custom mapping for ultisnips trigger which differs from the default `<tab>`
- I try to insert a `<tab>` character in insert mode
- The `<tab>` character appears in my buffer (the cursor moves on).

**Actual behavior:**
Pressing the `<tab>` key has no effect.

**Steps to reproduce**

`git clone git@github.com:nerfologist/ultisnips-tab-disable.git`
Follow the instructions to replicate the custom configuration (as simple as possible).

-----

- **Operating System**:  MacOS High Sierra (version 10.13.6 (17G65))
- **Vim Version**: 
  - **vim**
    VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 31 2018 10:52:37)
    macOS version
    Included patches: 1-280
    Compiled by Homebrew
  - **neovim**
    NVIM v0.3.1
    Build type: Release
    LuaJIT 2.0.5

- **UltiSnips Version**:  6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba
- **Python inside Vim**:
  - **vim**:
    - `:py import sys; print(sys.version)`: E319: Sorry the command is not available in this version
    - `:py3 import sys; print(sys.version)`: 3.7.0 (default, Jul 27 2018, 16:45:46)
  - **neovim**:
    - `:py import sys; print(sys.version)`: 2.7.15 (default, Jul 27 2018, 16:39:00)
    - `:py3 import sys; print(sys.version`: 3.7.0 (default, Jul 27 2018, 16:45:46)
- **Docker repo/vimrc**: please see [GitHub repo](https://github.com/nerfologist/ultisnips-tab-disable).

**Comment by lacygoill** [comment]
What is the output of `:verb ino <tab>`?

**Comment by lacygoill** [comment]
You configure the plugin too late.

Try to move the `:let` assignment *before* `packloadall`:

    let g:UltiSnipsExpandTrigger='<C-j>'

    " Load the plugins right now. (optional)
    packloadall

**Comment by nerfologist** [comment]
Hello, thanks for your answer, moving that line before `packloadall` fixes the problem 🥂. However, I am able to configure all other plugins after `packloadall` without similar unwanted side-effects. Is this something that needs fixing or is it my mistake?

Disclaimer: I am just a neovim user, not a plugin developer/maintainer, so I might be wrong.

**Comment by lacygoill** [comment]
I don't think it's a bug. For some plugins, you have to write your settings before they're sourced. Typically, this is done in your `vimrc`. But it can also be done in `~/.vim/plugin/my_plugin.vim`.

For other plugins, you have to write your settings *after* the plugin is sourced. As an example, this is the case for [vim-abolish](https://github.com/tpope/vim-abolish/blob/b95463a1cffd8fc9aff2a1ff0ae9327944948699/doc/abolish.txt#L70-L71). Typically, this is done in `~/.vim/after/plugin/my_plugin.vim`

However, most of the time, the settings should be written before the plugin is sourced, not after. That's what happens for people which write their settings in their `vimrc` and which use a plugin manager such as Vundle or vim-plug.

That's not what happens for you, because even though you write your settings in your `vimrc`, you use packages. With a plugin manager, the plugins are sourced *after* the `vimrc`, no matter the order in which you write your statements. But with `:packloadall`, it seems the plugins are sourced *immediately*.

Here's what happens in your case.

You execute `:packloadall` before assigning a value to `g:UltiSnipsExpandTrigger`. As a result, when [this line](https://github.com/SirVer/ultisnips/blob/6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba/autoload/UltiSnips/map_keys.vim#L8) is sourced, the `if` guard fails to prevent UltiSnips from assigning `<Tab>` to `g:UltiSnipsExpandTrigger`. This makes UltiSnips map some function to the `Tab` key, instead of leaving it alone.

After the plugin is sourced, you finally assign a value to `g:UltiSnipsExpandTrigger`, but it's too late to undo what has happened to the `Tab` key.

You can check that your `Tab` key has been mapped to some function via `:verb ino <tab>`.

To avoid this kind of issue in the future, move `:packloadall` after all your settings.

**Comment by nerfologist** [comment]
Amazing @lacygoill, thanks a lot for taking the time to write such a detailed answer, I appreciate it, and in general thanks for your work on this great plugin. I will get rid of `packloadall`!
