### ISSUE TITLE
Can we get UltiSnips to work in c-edit / command line window?

### ISSUE THREAD

**Issue by simlei** [SirVer/ultisnips#1026]
Hi, 
do any of the experts here know of a quick method to get UltiSnips expand snippets in the command line window? i.e., the ex command console that is set to ft=vim that appears after typing ``q:`` or, ``<C-f>`` when already in the ex-command-line after ``:``.

It would be most useful to have that, I think anyone would agree.

**Comment by baas-hans** [comment]
As anyone I would agree.

**Comment by lacygoill** [comment]
You can tell UltiSnips to automatically expand your snippet, by defining it with the `A` option:

    snippet foo "" A
    bar baz
    endsnippet

Note that the snippet must be defined in a `vim.snippets` file.

---

Or, you can remap the `Tab` key to the function used by UltiSnips to expand a snippet:

    augroup my_cmdline_window
        au!
        au CmdWinEnter * ino  <buffer><nowait><silent>  <tab>  <c-r>=UltiSnips#ExpandSnippet()<cr>
    augroup END

---

If you have other usage questions, try to visit https://vi.stackexchange.com/ and tag your question with [plugin-ultisnips](https://vi.stackexchange.com/questions/tagged/plugin-ultisnips).

**Comment by lacygoill** [comment]
Actually, there's a simpler solution:

    augroup my_cmdline_window
        au!
        au CmdWinEnter * iunmap <buffer> <tab>
    augroup END

The issue is that by default, Vim binds `Tab` to `C-x C-v` in the command-line window.
This local mapping probably shadows the `Tab` mapping installed by UltiSnips.

Once it's removed, UltiSnips can expand a snippet in the command-line window:

![gif](https://user-images.githubusercontent.com/8505073/51376450-a5fcb080-1b08-11e9-9f51-10640bbe45b8.gif)

**Comment by simlei** [comment]
Thank you, that is a very satisfying conclusion to this apparent non-issue.
I am sure, you helped a few other people except me, now, of course :)
