### ISSUE TITLE
Segfault on linux

### ISSUE THREAD

**Issue by sbromberger** [SirVer/ultisnips#1032]
using Ultisnips causes vim to crash with SIGSEGV after hitting 'o' in normal mode

**Expected behavior:**
I expected 'o' to allow me to insert a line below the cursor.

**Actual behavior:**
```
Vim: Caught deadly signal SEGV
Vim: preserving files...
Vim: Finished.
Segmentation fault (core dumped)
```

**Steps to reproduce**
1) Install Ultisnips via Plug
2) (re)start vim
3) type 'o'

-----

- **Operating System**: `Linux xxxxx 3.10.0-862.14.4.1chaos.ch6.x86_64 #1 SMP Wed Sep 26 12:27:08 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux`
- **Vim Version**:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  7 2018 12:00:19)
Included patches: 1-511
```
- **UltiSnips Version**: `6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba`
- **Python inside Vim**: 3.6.4
- **Docker repo/vimrc**:
```
call plug#begin('~/.vim/plugged')
Plug 'SirVer/ultisnips'
call plug#end()
```

**Comment by sbromberger** [comment]
Pretty useless backtrace: https://pastebin.com/Eu4hJ7fU

**Comment by wjt** [comment]
I found over on https://github.com/flathub/org.vim.Vim/pull/20 that this crash mysteriously goes away if Vim is built with `--enable-python3interp=dynamic` (which means "dlopen() it at runtime") rather than `--enable-python3interp` (which means "(dynamically) link to it").

**Comment by wjt** [comment]
@sbromberger what does `vim --version` say?

**Comment by surmish** [comment]
So what is the resolution for this error? I am seeing the same thing with my local vim compiled with Python 3.7.3

**Comment by SirVer** [comment]
My hunch is that Vim is trying to pull in both Python2 and Python3 in some form or shape: for example maybe one is statically linked in, the other is loaded when UltiSnips is loaded. This will yield crashes like these. A simple test is to type `:py print("Hello")` followed by `:py3 print("Hello")` and see if that crashes.

UltiSnips is not the cause here, but the symptom. I think the dynamic loading allows both python versions to coexist within vim.
