### ISSUE TITLE
Only trigger snippets in defined scopes?

### ISSUE THREAD

**Issue by Astrantia** [SirVer/ultisnips#1038]
Hello. I tried to search for this in the open/closed issues and documentation, but couldn't find a way for doing it. Is there a way to config the snippets to be triggered only in a said scope? For example, in tex I would want my snippets to be executed in $ here $, or in other math mode scopes. For further clarity, another example would be a snippet `pub` that expands to `public:` only in Classes in C++. Otherwise, it makes no sense to trigger `pub` unless you're in a class scope. I hope I've been able to explain this clearly and hopefully there's a way to do this without wrapping all snippets in a python code that checks for the outside scope. Thanks for the awesome plugin!

**Comment by lacygoill** [comment]
I think that's what the `e` option is for. Define your snippet with it, and write a python expression which evaluates to True only when you want your tab trigger is written in the right scope.

See `:h UltiSnips-custom-context-snippets`.

If you don't know python, or can't write the right python expression, try to visit https://vi.stackexchange.com/ and tag your question with [plugin-ultisnips](https://vi.stackexchange.com/questions/tagged/plugin-ultisnips).

**Comment by Astrantia** [comment]
@lacygoill Thanks for answering. I found out about `e` soon after asking this question so I can close it, but I couldn't resolve my real question. Is it possible to write a python script that identifies if you are in math mode in Tex? math mode can be inside `$ here $` or inside `$$  here $$` or inside `\begin{equation} here \end{equation}`. It might be possible to write such a script, but will it not be very expensive then?

**Comment by lacygoill** [comment]
> Is it possible to write a python script that identifies if you are in math mode in Tex? math mode can be inside $ here $ or inside $$ here $$ or inside \begin{equation} here \end{equation}.

You could leverage your tex syntax plugin. I don't know much about LaTeX, but if you're in a math environment, I guess the syntax highlighting is set accordingly. I use a mapping similar to this one, to get the stack of syntax items under the cursor:

    nno  <silent>  !s  :<c-u>call <sid>print_syntax_group_stack(v:count)<cr>

    fu! s:print_syntax_group_stack(count) abort
        if a:count
            let name = get(s:get_syntax_group_stack(), a:count-1, '')
            if !empty(name)
                exe 'syntax list '.name
            endif
        else
            echo join(s:get_syntax_group_stack())
        endif
    endfu

    fu! s:get_syntax_group_stack()
        return reverse(map(synstack(line('.'), col('.')), {i,v -> synIDattr(v, 'name')}))
    endfu

I wrote the examples you provided in a tex file:

    $ foo $
    $$ foo $$
    \begin{equation} foo \end{equation}

When I pressed `!s` while the cursor was on `foo`, the output was `texMathZoneX` or `texMathZoneY`.
You could use this information in a python expression. Here's an example:

    global !p
    def myfunc(snip):
        is_math = int(vim.eval("get(reverse(map(synstack(line('.'), col('.')), {i,v -> synIDattr(v, 'name')})), 0, '') =~# 'texMathZone\%(X\|Y\)'"))
        return is_math
    endglobal

    context "myfunc(snip)"
    snippet foo ""
    bar
    endsnippet

Write it in your tex snippets file, then write `foo` and press the key to expand the snippet. It should be expanded only in a math environment, not outside:

![gif](https://user-images.githubusercontent.com/8505073/50744936-8b345d00-1227-11e9-9e20-60c36ef7d6a0.gif)

---

> It might be possible to write such a script, but will it not be very expensive then?

The core of the code is the Vim expression. On my machine, it takes between `2` and `3` ms to be evaluated. I find this time to be acceptable, but you may disagree.

You can check on your machine, how much time the VimL expression takes to be evaluated, with this `:Time` custom command:

    com! -range=1 -nargs=+ -complete=command  Time  call s:time(<q-args>, <count>)
    fu! s:time(cmd, cnt) abort
        let time = reltime()
        if a:cnt > 1
            let i = 0
            while i < a:cnt
                exe a:cmd
                let i += 1
            endwhile
        else
            exe a:cmd
        endif
        redraw
        echom matchstr(reltimestr(reltime(time)), '\v.*\..{,3}').' seconds to run :'.a:cmd
    endfu

    :Time echo get(reverse(map(synstack(line('.'), col('.')), {i,v -> synIDattr(v, 'name')})), 0, '') =~# 'texMathZone\%(X\|Y\)'

You can prefix `:Time` with a count, to repeat the evaluation an arbitrary amount of time:

     vvv
    :123Time echo get(reverse(map(synstack(line('.'), col('.')), {i,v -> synIDattr(v, 'name')})), 0, '') =~# 'texMathZone\%(X\|Y\)'

Note that the code may need to be modified, because it assumes that the syntax item at the top of the stack will always be `texMathZoneX` or `texMathZoneY`. This may be wrong for 2 reasons:

- there may be other syntax items matching a math environment
- in the stack, there may be another syntax item above the one of the math environment

But that's not a python problem, that's a VimL one, and for that, there're people on https://vi.stackexchange.com/ which can help you further.

**Comment by Astrantia** [comment]
@lacygoill You just gave me the exact (and ten times better) answer that I was searching for such a looooong time. I'm so grateful to you, thank you so much really. Not only did you answer that it is possible to do it, but you also described the best way of doing it. I myself wondered if such an approach would be possible, but I didn't know if it was possible to determine in what scope you are located in VIM. Therefore I thought the only possible way of doing this would be by parsing the entire document everytime the snippet was executed and looking for regex matches for math modes. 3 ms is really nothing as I feared it would take even up to a second for parsing the document and looking for regex matches. I owe you a lot! Thank you for writing up such an elegant solution to my few months old problem!

**Comment by lacygoill** [comment]
> but it doesn't work when there are no spaces inbetween two delimiters begin and end: \begin{equation}here\end{equation}. Even though the syntax group is texMathZoneX both times

By default a snippet is expanded only if the tab trigger is the first word on the line or is preceded by one or more whitespace characters. You need to define your snippet with the `i` option (which stands for *in-word expansion*) to override this limitation. See `:h UltiSnips-snippet-options`.

This will allow you to expand `foo`, even if there's no space before:

    \begin{equation}foo \end{equation}

But it won't allow you to expand `foo` if there's no space after:

    \begin{equation}foo\end{equation}

This is because, in insert mode, when your cursor is after `foo`, the output of `col('.')` matches the character after the cursor, wich here is the backslash in `\end`. And in that position, the syntax item at the top of the stack is not `texMathZoneX`, but `texStatement`.

One solution would be to decrease `col('.')` by `1` byte:

    is_math = int(vim.eval("get(reverse(map(synstack(line('.'), col('.')-1), {i,v -> synIDattr(v, 'name')})), 0, '') =~# 'texMathZone\%(X\|Y\)'"))
                                                                        ^^

Which would give:

    global !p
    def myfunc(snip):
        is_math = int(vim.eval("get(reverse(map(synstack(line('.'), col('.')-1), {i,v -> synIDattr(v, 'name')})), 0, '') =~# 'texMathZone\%(X\|Y\)'"))
        return is_math
    endglobal

    context "myfunc(snip)"
    snippet foo "" i
    bar
    endsnippet

**Comment by Astrantia** [comment]
@lacygoill Thanks, thanks and thanks!

**Comment by lacygoill** [comment]
It looks like blindly decreasing the column position by `1` was too naive. Instead of this:

    col('.') - 1

Try:

    col('.')-(col('.')>=2 ? 1 : 0)

New attempt at a snippet:

    global !p
    def is_math():
        return int(vim.eval("get(reverse(map(synstack(line('.'), col('.')-(col('.')>=2 ? 1 : 0)), {i,v -> synIDattr(v, 'name')})), 0, '') =~# 'texMathZone\%(X\|Y\)'"))
    endglobal

    context "is_math()"
    snippet foo "" i
    bar
    endsnippet

**Comment by Astrantia** [comment]
@lacygoill That works great. I encountered one more problem that I reported to vi.stackexchange.com/questions/18490/ultisnips-context-and-tex

**Comment by Astrantia** [comment]
Hopefully a solution can be worked out in stackexchange. I'm very surprised I can find no relevant material for this on the internet, one would think this is something a lot of people desire. Hopefully if someone else comes to the same issue they can refer to the stackexchange link above.
