### ISSUE TITLE
SnippetSyntaxError

### ISSUE THREAD

**Issue by bladrome** [SirVer/ultisnips#1046]
**Expected behavior:**

open a .py file

**Actual behavior:**
"An error occured. "

**Steps to reproduce**
vim foo.py

1. open a .py file

![screenshot from 2019-01-10 09-23-05](https://user-images.githubusercontent.com/16330525/50939824-5dfedd80-14b9-11e9-82a7-c5039ebacfa3.png)

-----

- **Operating System**: Ubuntu 16.04 
- **Vim Version**: 
- **UltiSnips Version**: 6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba 
- **Python inside Vim**: 3.5.2 
- **Docker repo/vimrc**:

let g:UltiSnipsJumpForwardTrigger="Ctrl-n"
let g:UltiSnipsJumpBackwardTrigger="Ctrl-p"
let g:UltiSnipsEditSplit="vertical"

**Comment by lacygoill** [comment]
There's not enough information in your post to help you debug the issue.
In the screenshot you took, [this link](https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs) is mentioned. It explains how to reproduce and report a bug.

At the very least, you should include the snippet which caused the stack trace; otherwise, there's no way to help you.
