### ISSUE TITLE
Ternary replacement operator not working as exepected anymore

### ISSUE THREAD

**Issue by PlasmaHH** [SirVer/ultisnips#1057]
**Expected behavior:**
Replacement to either A or B but never both in the ternary replacement operator. (It has been working before). That is in this particular case when $1 is empty it should display and when it contains something it should display A

**Actual behavior:**
B is always inserted, no matter the match, so we get B or AB but can't get A

**Steps to reproduce**
Use the following snippet:

```
snippet test
result $1
optional: '${1/(.+)|(.*)/(?1:A:B)/g}' full: '$1'
endsnippet
```
then do
test<tab> and play with it and observe that you can never get B to not display.

I had the more complex version of that snippet now for years and it was always working and I noticed recently that it breaks but can't tell in which version. It does so in a "clean" vim without any other plugins installed.

-----

- **Operating System**:  Linux
- **Vim Version**:  8.1.687
- **UltiSnips Version**:  6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba
- **Python inside Vim**: 3.7.2
- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
I am able to reproduce this with my Vim setup here at home, but when I added a test case for it, the test case came back correct for the version I tested with. I created a PR to see what CI shows us here.

**Comment by SirVer** [comment]
Actually, I brought this down to an inconsistency in python regex engines:

```python
import re
reg = re.compile(r"(.+)|(.*)", re.DOTALL)
replace = lambda m: print(m)
reg.subn(replace, "a", 0)
``` 

yields 
~~~

<_sre.SRE_Match object; span=(0, 1), match='a'>
('', 1)
~~~

inside the docker container where I run the tests and

~~~
<re.Match object; span=(0, 1), match='a'>
<re.Match object; span=(1, 1), match=''>
~~~

on my MacOS dev machine. Testing further, it seems to be that this behavior changed in Python 3.7 (which returns 2 matches) while all other Python versions before returned only one. Python 3.8 also returns 2.

~~~
docker run -it python:3.6-stretch /bin/bash
root@48e8dbf1be03:/# python
Python 3.6.9 (default, Oct 17 2019, 06:49:31)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> reg = re.compile(r"(.+)|(.*)", re.DOTALL)
>>> replace = lambda m: print(m)
>>> reg.subn(replace, "a", 0)
<_sre.SRE_Match object; span=(0, 1), match='a'>
('', 1)
>>>


docker run -it python:3.7-stretch /bin/bash
root@16211d4d5cac:/# python
Python 3.7.5 (default, Oct 19 2019, 00:22:19)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> reg = re.compile(r"(.+)|(.*)", re.DOTALL)
>>> replace = lambda m: print(m)
>>> reg.subn(replace, "a", 0)
<re.Match object; span=(0, 1), match='a'>
<re.Match object; span=(1, 1), match=''>
('', 2)
>>>
~~~

For your particular use case, I suggest using python interpolation instead:

```
snippet test
result $1
optional: '`!p snip.rv = 'A' if t[1] else 'B'`' full: '$1'
endsnippet
```

**Comment by PlasmaHH** [comment]
My particular case was just for demonstration, I am not sure if its always possible to do in my more complex real world cases.

Anyways, doesn't that mean that ternary replacement will stay broken?

**Comment by SirVer** [comment]
> Anyways, doesn't that mean that ternary replacement will stay broken?

No. sorry, I was not very clear in my summary. This snippet should work:

```
snippet test
result $1
optional: '${1/(.+)|(.*)/(?1:A:B)/}' full: '$1'
endsnippet
```

The problem is the `g` modifier of the regex. And here the semantics are not really clear in your original snippet and are interpreted differently by newer pythons and older pythons.

Consider your regex: `(.+)|(.*)` and look at any non empty string, let's say `foo`. You are asking for global matches, i.e. rematch times again what remains from the string. Looking at the first part of the regex `(.+)` it clearly matches all of `foo`. Now the question is: should a global match continue trying the rest of the regex against the unconsumed string or not? Older python say no, because the string was fully consumed. Newer pythons say yes, because the regex could still match the empty string. And in fact it does: `(.*)` matches the empty string. This is why you get both matches  with newer python version, hence `AB`. Not using global matching should work in this case.

**Comment by PlasmaHH** [comment]
Got it, this should work in my real world example fine too, thanks.
