### ISSUE TITLE
Manual call to RefreshSnippets needed

### ISSUE THREAD

**Issue by allopislozano** [SirVer/ultisnips#1058]
Using latest version of ultisnips (6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba)

**Steps to reproduce**
From within vim, call :UltisnipsEdit!   and edit the cpp syntax in the vim-snippets plugin that the call to UltisnipsEdit! proposes.   

Add some snippet and save the file

**Expected behavior:**
The snippet should be available when I go back to my cpp file to use it

**Actual behavior:**
There is need of an explicit :call UltiSnips#RefreshSnippets()   so that the snippet is available. 

Is this a known bug?

**Comment by hsmith** [comment]
This may be unrelated to your problems, I recently had a similar problem which turned out to be related to Vundle and a misconfiguration of my `.vimrc`. (if you don't use Vundle feel free to skip)

It turns out, that Vundle requires `filetype off` be set (https://github.com/VundleVim/Vundle.vim/issues/176).  It also appears to forcibly disable it when you `call vundle#begin()`.  This was causing several problems for me, including preventing the UltiSnips and several other plugins from functioning properly.  (A recent change to UltiSnips 4eac9798885f508d388d07847946a925dea583a5 uses autocmd and the snippets filetype to trigger `RefreshSnippets`)
 
The solution for me was to set `filetype plugin on` or after `call vundle#end()` in my `.vimrc` file.
```
  1 "                                                                                                                                                         
  2 " set the runtime path to include Vundle and initialize =======================                                                                           
  3 "                                                                                                                                                         
  4 set rtp+=~/.vim/bundle/Vundle.vim                                                                                                                         
  5 call vundle#begin()                                                                                                                                       
  6                                                                                                                                                           
  7 " Plugin Begin ----------------------------------------------------------------                                                                           
  8 Plugin 'SirVer/ultisnips'                                                                                                                                 
  9 " Plugin End ------------------------------------------------------------------                                                                           
 10 call vundle#end()                                                                                                                                         
 11                                                                                                                                                           
 12 filetype plugin on 
```

After I made this change, UltiSnips worked like a charm!  Hope this helps you~

**Comment by allopislozano** [comment]
Thank you very much @hsmith , even though I do not use Vundle but the built in vim package manager I think that with the information you provided I can try to find the problem. Thanks!

**Comment by SirVer** [comment]
Cannot reproduce, works for me. I need a minimal repro case to look into this, but very likely it is a configuration error similar to what @hsmith pointed out.
