### ISSUE TITLE
Expand Trigger not working with :set paste

### ISSUE THREAD

**Issue by yussidivnall** [SirVer/ultisnips#1080]
**Expected behavior:**
Setting
```
set paste
let g:UltiSnipsExpandTrigger="<c-e>"
```
should expand to snippet.

**Actual behavior:**
It doesn't expand, calling 
`:call UltiSnips#ExpandSnippet() `
or
`:call UltiSnips#ExpandSnippetOrJump()`

does work.  removing  `set paste` seems to fix the issue

**Steps to reproduce**
Using this .vimrc:
```
execute pathogen#infect()`
set paste
" UltiSnips
let g:UltiSnipsExpandTrigger="<c-e>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
```
edit a file, select a trigger, type ctrl-e, not expanding snippet.

-----
- **Operating System**: Debian 9.8
- **Vim Version**: 
    VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 16 2018 19:37:11)
    Included patches: 1-606
- **UltiSnips Version**: 1a99766b73783bafb08cfa07d7e29e5387c55189
- **Python inside Vim**:
    3.5.3 (default, Sep 27 2018, 17:25:39)
    [GCC 6.3.0 20170516]
- **Docker repo/vimrc**: 
```
execute pathogen#infect()
set paste
" UltiSnips
let g:UltiSnipsExpandTrigger="<c-e>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
```

**Comment by lacygoill** [comment]
This is not an issue with UltiSnips, but a limitation of `'paste'`.

Setting `'paste'` disables mappings in insert mode.
From `:help 'paste'`:

> When the 'paste' option is switched on (also when it was already on):
>         - mapping in Insert mode and Command-line mode is disabled

Your `C-e` mapping is insert mode, therefore it can't work if `'paste'` has been set.

**Comment by therealmaxmoon** [comment]
@lacygoill This should be mentioned in the README.md in a troubleshoot section. It took me days to figure this out, because UltiSnips didn't work. At some day I just renamed my .vimrc to see if UltiSnips would run with a clean/no config file and it did. It blew my mind and after uncommenting every single line in my config, I figured out that "set paste" was the problem. And after figuring out the problem, I found this thread. 

What is the problem with having paste always set on? Isn't it a bit complicated to set paste every time one paste something?

**Comment by lacygoill** [comment]
> This should be mentioned in the README.md in a troubleshoot section.

I'm not the maintainer, so I have no say in what is written in the README.

> It took me days to figure this out, because UltiSnips didn't work.

I wrote [an answer](https://www.reddit.com/r/vim/comments/bq2drz/vim_plug_ultisnips_not_working/eo0s50a/) a few months ago to help someone debug their UltiSnips.

Here is its contents:

> Here are a few things you could try:
>
> Change the key expanding a trigger to something else; as a suggestion, `C-g C-g`:
>
>     let g:UltiSnipsExpandTrigger = '<c-g><c-g>'
>
> And make some tests, pressing `C-g C-g` instead of `S-Tab` to expand a snippet.
>
> If it works, maybe it means that Vim fails to recognize `<S-Tab>`.
> In that case, try to add in your vimrc:
>
>     set <s-tab>=
>
> Then, from insert mode, right after the assignment operator `=`, press and release C-v, then press and release S-Tab. This should make Vim write the literal sequence of keys it receives when you press S-Tab.
>
> ---
>
> Replace `~` with the absolute path to your home directory, or with `$HOME`.
>
> Before:
>
>     let g:UltiSnipsSnippetsDir = "~/.vim/UltiSnips"
>     let g:UltiSnipsSnippetDirectories = ['~/.vim/UltiSnips', 'UltiSnips']
>
> After:
>
>     let g:UltiSnipsSnippetsDir = $HOME . '/.vim/UltiSnips'
>     let g:UltiSnipsSnippetDirectories = [$HOME . '/.vim/UltiSnips', 'UltiSnips']
>
> ---
>
> Create the directory `/tmp/snippets/`:
>
>     $ mkdir /tmp/snippets/
>
> Write this test snippet in `/tmp/snippets/vim.snippets`:
>
>     snippet trigger
>     my snippet has been expanded
>     endsnippet
>
> Write this minimal vimrc in `/tmp/vimrc`:
>
>     let g:UltiSnipsSnippetDirectories = ['/tmp/snippets']
>     let g:UltiSnipsExpandTrigger = '<tab>'
>     set rtp-=$HOME/.vim
>     set rtp^=$HOME/.vim/plugged/ultisnips
>     set rtp+=$HOME/.vim/plugged/ultisnips/after
>     set rtp^=$HOME/.vim
>     set vi=
>     filetype plugin on
>
> Start Vim like this:
>
>     $ vim -Nu /tmp/vimrc +"put ='trigger'" +'startinsert!' /tmp/vim.vim
>
> Vim should open a buffer with the word `trigger` in it, your cursor should be positioned after the word, and you should be in insert mode.
>
> Press Tab. The snippet should be expanded.
>
> If it's not, maybe something is wrong in your Vim build (try to recompile with more features; `--with-features=huge`), or something is wrong in your UltiSnips plugin (try to reinstall it and/or update it), or something in your environment intercepts your key (here Tab) before Vim (terminal emulator, window manager, ...).
>
> If it is expanded, you have a working starting point. From there, progressively re-include your custom Vim configurations and your snippets until something breaks. When that happens, restart Vim with the original minimal vimrc, after adding to it the last setting which broke the expansion. If the new – augmented – vimrc reproduces your issue, then you have a [MCVE](https://stackoverflow.com/help/mcve). Post it for people to be able to reproduce your issue.

Note that the answer assumes that you're using Linux and [`vim-plug`](https://github.com/junegunn/vim-plug) as your plugin manager, and that as a consequence your UltiSnips is installed under `~/.vim/plugged/ultisnips/` and `~/.vim/plugged/ultisnips/after/`.
If you're using another OS or plugin manager, then you will need to fix the paths in these 2 statements so that they point to your local UltiSnips:

    set rtp^=$HOME/.vim/plugged/ultisnips
    set rtp+=$HOME/.vim/plugged/ultisnips/after

> What is the problem with having paste always set on?

It breaks many things, including abbreviations, insert mode mappings and command-line mode mappings. This is documented in more detail at `:h 'paste'`. So, when it's set, anything which relies on an abbreviation, an insert mode mapping or a command-line mode mapping is – in turn – broken too.

> Isn't it a bit complicated to set paste every time one paste something?

Yes, that's why – in the past – people didn't set it manually, but used a custom mapping, like [`yop`](https://github.com/tpope/vim-unimpaired/blob/08e66532bffed445c949ae0a0501940c000553ed/doc/unimpaired.txt#L108-L113) provided by the [`vim-unimpaired`](https://github.com/tpope/vim-unimpaired/) plugin.
The latter toggles the value of the `'paste'` option. It also installs [an autocmd](https://github.com/tpope/vim-unimpaired/blob/08e66532bffed445c949ae0a0501940c000553ed/doc/unimpaired.txt#L108-L113) listening to `InsertLeave` to automatically disable the option when leaving insert mode.

Nowadays, you can avoid all the issues which arise when `'paste'` is set by:

   - not pasting from insert mode, but from normal mode
   - using Nvim where the bracketed paste mode is builtin (and where `'paste'` is obsolete)
   - using a terminal which supports the bracketed paste mode, a Vim which includes the patch 8.0.0210, and configuring the latter as explained at `:h xterm-bracketed-paste`

Note that if you rely on the bracketed paste mode, other software layers may also need to be configured (like the terminal multiplexer). I wrote something about it [here](https://www.reddit.com/r/neovim/comments/col6zu/whats_even_the_point_of_insert_paste_mode/ewjw1c6/).

Also, note that the bracketed paste mode is not 100% reliable. I wrote about it [here](https://github.com/lacygoill/config/blob/05245b132a57072d75edd83072a0062185b3044c/.vim/vimrc#L1790-L2030) and [here](https://github.com/lacygoill/wiki/blob/master/vim/terminal.md#the-terminal-doesnt-support-the-bracketed-paste-mode).

FWIW, I never have any issue with `'paste'`, because:

   - I never paste from insert mode (always from normal mode)
   - I never use the (N)Vim terminal
   - I include a [red indicator](https://github.com/lacygoill/vim-statusline/blob/69a896b388ac2127cd878b38605c0926720c4b3c/plugin/statusline.vim#L762-L771) in my tabline to be immediately informed whenever the option gets accidentally set by a third-party plugin or because of a (N)Vim bug, so that I know why things get suddenly broken and how to fix them

**Comment by SirVer** [comment]
@therealmaxmoon `paste` disables basically any smarts Vim has. From the help: `When the 'paste' option is switched on mapping in Insert mode and Command-line mode is disabled` which means Vim does basically nothing. Vim cannot know if the keys it sees are you typing or you copy & pasting text, so that is why it needs an option. I do not think this belongs into UltiSnips README, since this is something very Vim centric and non-UltiSnips specific.

> I'm not the maintainer, so I have no say in what is written in the README. 

@lacygoill, do you want to be a maintainer? You add a lot of value on this bug tracker and kept the lights on while I had no time for UltiSnips, I'd be honored to have you onboard.

**Comment by lacygoill** [comment]
> @lacygoill, do you want to be a maintainer? You add a lot of value on this bug tracker and kept the lights on while I had no time for UltiSnips, I'd be honored to have you onboard.

@SirVer, I would be really glad to, but I have personal issues at the moment, and I don't know whether/when they will be fixed. I don't want to become a maintainer and drop the ball in a few weeks/months because of that.
Besides, I don't know much about Python, so I would not be able to fix the hard bugs which involve refactoring Python code.

The best I can do is to answer some questions here and there, and for that I don't need to be a maintainer. I appreciate the suggestion though, thank you.

**Comment by SirVer** [comment]
@lacygoill Helping on the issue tracker is prime maintenance work, coding is not a prerequisite for helping with maintenance. Your work here is very much appreciated, no matter the amount of time and energy you have to contribute. Thanks!

I hope your personal issues are sorting out quickly! All the best and thanks for being awesome for UltiSnips.
