### ISSUE TITLE
ultisnips errors with Repository not found when installing with vim-plug

### ISSUE THREAD

**Issue by fakeharxy** [SirVer/ultisnips#1160]
**Expected behavior:**
When I run :PlugInstall, ultisnips installs

**Actual behavior:**
It errors with: 
x ultisnips:
    Cloning into '/Users/[me]/.config/nvim/plugins/ultisnips'...
    ERROR: Repository not found.
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.

If this helps, initially it errored with:

Git Error: Could could not read Username for ‘https://github.com’: terminal prompts disabled

Googling that lead me to this blog: 

https://jacopretorius.net/2018/05/git-error-could-not-read-username.html

and therefore entering this:

`git config --global --add url."git@github.com:".insteadOf "https://github.com/"`

**Steps to reproduce**

It's tricky to reproduce for you.

```
filetype plugin on
call plug#begin('~/.config/nvim/plugins')
Plug 'SirVir/ultisnips'
Plug 'honza/vim-snippets'
call plug#end()

let g:UltiSnipsExpandTrigger="<tab>"

```

-----

- **MacOS 10.14.6**: 
- **NVIM v0.4.3
Build type: Release**: 
- **UltiSnips Version**: 
- **Python inside Vim**: 
- **Docker repo/vimrc**:

**Comment by fakeharxy** [comment]
Thanks for any help, sorry I couldn't give you more info

**Comment by SirVer** [comment]
This looks very similar to the docker repro image configuration: https://github.com/SirVer/ultisnips/blob/master/docker/docker_vimrc.vim, which work perfectly in CI and in my own tests. My assumption is that you are behind some sort of proxy, firewall or other network setup that messes with the https cloning. This is definitely something on your end and nothing related to UltiSnips (which you should be able to verify by just removing `Plug 'SirVir/ultisnips'` and see it fail for the `vim-snippets` repo).

The blog you posted seems to indicate that this is due to second factor being enabled for github, which sounds weird to me, because I have second factor enabled as well and do not see the issue. However, you should be able to work around by giving the full git URL instead of the short forms to plug, though I did not try that:

`Plug 'git@github.com:SirVer/ultisnips.git'`

**Comment by fakeharxy** [comment]
Hi, just for the record, `Plug 'git@github.com:SirVer/ultisnips.git'` worked! Something funky is going on, because vim-snippets installs fine. Ah well, it's solved anyhow. Thanks.
