### ISSUE TITLE
Error detected while processing function UltiSnips#TrackChanges

### ISSUE THREAD

**Issue by jlconlin** [SirVer/ultisnips#1161]
I used to have UltiSnips working well. I found it to be particularly helpful. However, something happened and now it doesn't work. *With every keystroke*, I get an error `Error detected while processing function UltiSnips#TrackChanges` followed by a lengthy traceback.

I've spent the last week trying to figure out what is the problem. I was using Vim 8.1.? from the MacVim gui. In my researches, it seemed that UltiSnips no longer supports Python2. So I've tried a number of things to resolve this:

- Updated to Vim 8.2
  - Compiled by myself with python3 support
- Updated UltiSnips
  - Installed with Vundle with this line: `Plugin 'SirVer/ultisnips'`

At the end of my `.vimrc` I `source` [snippets.vim](https://github.com/jlconlin/ViMConfig/blob/master/snippets.vim) which contains the following:

```vim
let g:UltiSnipsUsePythonVersion = 3

let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

let g:UltiSnipsListSnippets = "<c-h>"
                
let g:UltiSnipsSnippetsDir = "~/.vim/ultisnips"
let g:UltiSnipsEditSplit = "vertical"

"Open UltiSnips edit function
nmap <leader>se :UltiSnipsEdit<cr>

let g:UltiSnipsNoPythonWarning = 1
```

Regardless of what I've done, I can't seem to figure out what is wrong and was hoping I could get some help here. I don't know if this is a bug or if my configuration is wrong.

-----

- **Operating System**:  Mac 10.14.6
- **Vim Version**:  

  VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 23 2019 11:40:07)
  macOS version

- **UltiSnips Version**: 
  e100d57b72fcb08f62666880648e9d485751b19e

- **Python inside Vim**: 

  3.7.3 (default, Dec 23 2019, 11:28:16)
  [Clang 10.0.0 (clang-1000.11.45.5)]

- **Docker repo/vimrc**: 
[vimrc](https://github.com/jlconlin/ViMConfig/blob/master/vimrc) and [snippets.vim](https://github.com/jlconlin/ViMConfig/blob/master/snippets.vim)

**Comment by luckscx** [comment]
I have exactly same issue with you after i update UltiSnips to latest.
I try to checkout with old tag(3.2) and it work ok.

**Comment by SirVer** [comment]
This is not enough information to reproduce this issue. Please

1. attach the full stack trace
2. please provide a fully reproducible example, ideally using the approach explained in https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs or if not possible with a minimal `vimrc` and snippets files and an exact sequence of key strokes that trigger the bug., including keystrokes.

@jlconlin, your example is not complete: your .vimrc depends on other files not mentioned in the report. @luckscx, with the information you provided I am not certain that you see the same issue, so please also provide the above information.

@jlconlin, This is what I tried to repro your issue:
 
```
$ make repro
Rest of the commands are inside the docker container.
# rm -rf /root/.vim*
# git clone --recursive https://github.com/jlconlin/ViMConfig.git ~/.vim
I then modified .vimrc and commented in the line including ~/.vim/snippets.vim and in packages.vim the line cloning UltiSnips.
# vim +PluginInstall +qall
Then, the snippets were not found, because `~/.vim/ultisnips` must be `~/.vim/UltiSnips`.
# vim /tmp/blub.cc
typing `iapprox<tab>` and the snippet expands without any errors, further typing does not result in a backtrace.
```

So, everything seems to be working as intended with the information I currently have. I suggest trying to `rm -rf the UltiSnips` git checkout and recheck it out, maybe the python precompiled files have gone stale for one reason or another. Otherwise, you need to provide me with a fully reproducible example.

**Comment by jlconlin** [comment]
Thanks @SirVer for your efforts. I apologize my description was lacking. I've confirmed on a different machine that my setup works. I'll keep working on this to figure out a solution.

**Comment by tbhockey** [comment]
I am having this issue as well.

**Comment by John-Appleseed** [comment]
Same issue with gentoo linux but not macOS. I can temporarily fix the issue by `:source ~/.vimrc` 

Gentoo linux fix is to use the python use flag for vim.
```
USE="python" emerge -a app-editors/vim
```

**Comment by MikeSperone** [comment]
I also had this same issue - and in my case it occurred when writing my git commit message.

I found it was the path to vim in my .gitconfig file.  It was pointing to /usr/bin/vim (the macOS installed vim), instead of /usr/local/bin/vim (v. 8.2 w/ python3 that I installed with homebrew).  This issue stopped when I updated core.editor to point to the correct vim.
