### ISSUE TITLE
Provide an option to select which directory is used by UltiSnipsEdit

### ISSUE THREAD

**Issue by Ram-Z** [SirVer/ultisnips#1163]
As initially described in https://github.com/SirVer/ultisnips/issues/1144#issuecomment-569974963, when using `:UltiSnipsEdit` with multiple entries in `UltiSnipsSnippetsDirectories` it will query which folder should be used even if that folder doesn't exist.

**Expected behavior:**

Although I have multiple entries in `UltiSnipsSnippendsDirectories`, I only have one location for my private snippets, calling `:UltiSnipsEdit` I expect that one location to be opened.

**Actual behavior:**

```
  1: /home/ramsi/.config/vim/UltiSnips/vim.snippets
* 2: /home/ramsi/.config/vim/ultisnips/vim.snippets
Type number and <Enter> or click with mouse (empty cancels):
```
`vim/UltiSnips` does not exist and I have no desire to use it, everything else in that folder is lower case.

I suppose this is a result of my vimrc.

```vim
let g:UltiSnipsSnippetsDir = expand("$XDG_CONFIG_HOME/vim/ultisnips")
if has('fname_case')
  let g:UltiSnipsSnippetDirectories = ["UltiSnips", "ultisnips"]
endif
```

Until recently(?) `:UltiSnipsEdit` would use `g:UltiSnipsSnippetsDir` to decide where to put/edit private snippets, so there was only one choice and it would open that directly. This is not the case anymore.

**Steps to reproduce**

```vim
:let g:UltiSnipsSnippetDirectories = ["UltiSnips", "ultisnips"]
:UltiSnipsEdit
```

**Possible solutions**

IMO the setting for where to look for public snippets and where to edit private snippets should be separate. The concerns are different, one is to find snippets that may have been provided externally by a different plugin, and one is to set the path where you want to edit your own private snippets. The former will have to look for these directories in all dirs in `runtimepath`, the latter however is known to the user and can be set to an absolute path.

I propose to provide a new variable `g:UltiSnipsEditDirectories` which is either empty (default) or contains a list of paths to choose from when calling `:UltiSnipsEdit`. If it is not empty and only contains one entry, open that without querying, else ask the user which path to open. If it's empty use `g:UltiSnipsSnippetsDirectories` and the current wheres-my-vimrc search behaviour.

-----

- **Operating System**: Arch Linux
- **Vim Version**: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 23 2019 16:15:08)
Included patches: 1-33
- **UltiSnips Version**: 96026a4df27899b9e4029dd3b2977ad2ed819caf
- **Python inside Vim**: 3.8.1

**Comment by SirVer** [comment]
So, I acknoledge the use case requested in OP. In the past, there was an option to do just that, but it was very confusing to users and frequently used incorrectly, so in conclusion of #711 I decided to redesign and simplify. The option OP is asking for was consciously cut out to make the configuration simpler.

Let's explore the design space for a moment here on how we could bring it back. Currently I see a few possibilities of implementing this:

1. Not do anything, instead suggest users to define their own `:UltiSnipsEdit` replacement, something akin to `command MyUltiSnipsEdit execute 'edit ~/.vim/UltiSnips/' . (&ft ? &ft : "all")
. '.snippets'` should do the trick. 
1. Have a variable that contains a path to the desired default directory and default to using this in `:UltiSnipsEdit`. This is akin to how it was before my redesign.

Problem with 1 is that it is not dealing well with dotted filetypes `set ft=cuda.cpp`. 

However 2 has a similar problem: For one, how to get back the default behavior of `:UltiSnipsEdit` when the variable is set, and what to do for dotted filetypes? Still show a menu? Another problem of 2 is that it is possible to set a directory that is not on the search path for snippet discovery (which was frequently the mistake before) and so snippets would be edited that would then not be loaded. Also, there is no easy obvious name for such a variable that comes to mind to me - the suggested `UltiSnipsEditDirectories` seems easy to confuse with `UltiSnipsSnippetDirectories`. It's semantics are also unclear: does it contain full paths or just stubs?

@Ram-Z I currently prefer solution 1. for its simplicity, since with 2 I feel there are a few foodguns and the value add seems marginal to 1. Wdyt?

**Comment by Ram-Z** [comment]
For 1, I do already have something similar for other config files ([vimrc#l811](https://git.rmz.io/dotfiles.git/blob/HEAD:/vim/vimrc#l811)), I could extend that to support snippets too. So in that regard, if you decide that you do not want this functionality here, I'll work around it on my end.

> For one, how to get back the default behavior of :UltiSnipsEdit when the variable is set, and what to do for dotted filetypes? Still show a menu?

I didn't realise that `:UltiSnipsEdit` handles dotted filetypes. I don't mind the menu, as long as it only offers paths specified in `g:UltiSnipsEditDirectories`.

> Another problem of 2 is that it is possible to set a directory that is not on the search path for snippet discovery (which was frequently the mistake before) and so snippets would be edited that would then not be loaded

That path could be automatically added to the search path. 

I got confused by `UltiSnipsSnippetDirectories` too recently. In the help it is listed under `3.1.1 UltiSnipsEdit`, so I thought it affected that command only. Changing it to something that didn't contain the default "UltiSnips" entry broke snippets provided by other plugins.

> Also, there is no easy obvious name for such a variable that comes to mind to me - the suggested `UltiSnipsEditDirectories` seems easy to confuse with `UltiSnipsSnippetDirectories`.

It suffers from this less than `UltiSnipsSnippetsDir`, maybe enough for users to look it up in the docs to figure out exactly how to use it?

I can't think of any better alternatives, it does contain the name of the command it affects.

> It's semantics are also unclear: does it contain full paths or just stubs?
 
This would need to be described well in the documentation. IMO it should be a list of full paths.

**Comment by SirVer** [comment]
In general I agree with your thoughts on this. I am quite unhappy about `UltiSnipsSnippetDirectories` and the design we picked in the end, but I do not see an easy way to change it - since third party plugins are affected.

As I am not happy with the options we found to add the discussed feature without increasing complexity for new users again, I suggest you work around the issue on your end as discussed. If more people chime in on this in the future, I might reconsider.

Closing for now.
