### ISSUE TITLE
how to reactivate/reenter a closed snippet?

### ISSUE THREAD

**Issue by ri-aje** [SirVer/ultisnips#1164]
**Expected behavior:**
provide some mechanism to reenter a closed snippet and make it ultisnips-editable again, preferably from the last position an user edit happened.

**Actual behavior:**
once closed, a snippet becomes regular vim text. I don't know a way to have it back for ultisnips to manage. searching ultisnips doc, or here or googling didn't help. for reference, I did find this [SO post](https://stackoverflow.com/questions/42116206/vim-ultisnips-reactivate-snipet) asking the same thing, but no reply so far.

**Steps to reproduce**

1. use this snippet:
```
snippet test "test"
${1:test}
${1/(.*)/$1/}
(${2:default},${2/(.*)/$1/})
endsnippet
```
2. invoke it and type something to replace `$1`. this just shows the snippet works to expectation and isn't essential to the repro.
3. jump forward twice to exit the snippet. now try to change `$2`. I cannot find a way to do this and I would like to do so.

I found this case often happens in complicated snippet editing where I don't remember how many tab stops I have before ultisnips closes the snippet, and by the time I found it by falling out of the snippet due to too many jumps, it's already too late. the only option at that point is either to fix everything myself, or undo all edits and start over on the snippet. neither is ideal. I would like a mechanism to reenter the half-way done snippet and fix the remaining pieces. thanks.

-----

- **Operating System**: 
ubuntu 18.04

- **Vim Version**: 
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 10 2019 10:49:36)
Included patches: 1-1512

- **UltiSnips Version**: 
96026a4df27899b9e4029dd3b2977ad2ed819caf

- **Python inside Vim**: 
`:py import sys; print(sys.version)`
`E319: Sorry, the command is not available in this version`
`:py3 import sys; print(sys.version)`
`3.6.8 (default, Oct  7 2019, 12:59:55) 
 [GCC 8.3.0]`

- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
Unfortunately this is not easily possible. 

Design wise I would have preferred to have snippets open forever, i.e. never exit them. But since state tracking in snippets is a very heavy process  - it does a diff of the past buffer state to the new buffer state on every change which is a O(n^3) operation - due to the insufficient hooks in Vim, we only do it for the shortest amount possible.

This also means that having multiple snippets active at once becomes more and more costly and closing a snippet loses all state required to retrack it again. Reactiving a snippet is not possible, since it would require to keep the state tracked during the time it was not active, which is not viable.

So as much as I'd love this feature, it would actually start by adding some hooks into Vim to better support the kind of state tracking UltiSnips needs - which is not something I am Interested in pursuing anytime soon.
