### ISSUE TITLE
Help Python36.dll is causing problems!

### ISSUE THREAD

**Issue by PhiofS** [SirVer/ultisnips#1167]
Hello, I'm kinda new to vim, so I've encountered this problem while running ultisnips,

![image](https://user-images.githubusercontent.com/60249271/73045603-88110c80-3e3c-11ea-87c4-6c582b2d1feb.png)

I dont know what to do next, any solution will be greatly appreciated.

**Comment by lacygoill** [comment]
What is the output of these 2 commands?:

    :echo has('python3')
    :py3 import sys; print(sys.version)

If the output of the first command is 0, it means your Vim binary was not compiled with the python3 interface.  In that case, your issue is not related to UltiSnips.
You may need to install a Vim package which includes a python3 interface; read [`:h 90.2`](https://vimhelp.org/usr_90.txt.html#90.2) (and more generally [`:h install`](https://vimhelp.org/usr_90.txt.html#install).

You may also need to configure Vim; read:

   - [`:h 'pyxversion`](https://vimhelp.org/options.txt.html#'pyx')
   - [`:h 'pythonthreedll`](https://vimhelp.org/options.txt.html#'pythonthreedll')
   - [`:h 'pythonthreehome`](https://vimhelp.org/options.txt.html#'pythonthreehome')

If you have other usage questions, visit [vi.stackexchange.com](https://vi.stackexchange.com), and tag your question with [plugin-ultisnips](https://vi.stackexchange.com/questions/tagged/plugin-ultisnips).

**Comment by SirVer** [comment]
Very likely you are missing a system wide python installation that Vim could use. Google for Vim + Python 3 on your operating system to get unstuck.

Closing as this is near certainly not a UltiSnips issue. Please post if you disagree.
