### ISSUE TITLE
ultisnips causes imap <ctrl i> invalid

### ISSUE THREAD

**Issue by winkee01** [SirVer/ultisnips#1212]
**Expected behavior:**
I have this mapping:

    inoremap <C-i> <C-o>^

which means when I hit `ctrl - i` in insert mode, my cursor goes to the beginning of the line, but Ultisnips causes a conflict with this mapping, therefore the mapping does not work. When I disable Ultisnips, this mapping works as expected.

**Actual behavior:**
produces a tab

**Steps to reproduce**
inoremap <C-i> <C-o>^

By disabling Ultisnips, this mapping works. 

OS: Mac OS X
vim version: 8.2+
Ultisnips: latest

**Comment by lacygoill** [comment]
This is not an issue in UltiSnips; Vim doesn't make the difference between `C-i` and `Tab`:

    echo "\<c-i>" is# "\<tab>"
    1

Use different keys.  Or [use xterm](https://vi.stackexchange.com/a/23344/17449).

**Comment by winkee01** [comment]
> This is not an issue in UltiSnips; Vim doesn't make the difference between `C-i` and `Tab`:
> 
> ```
> echo "\<c-i>" is# "\<tab>"
> 1
> ```
> 
> Use different keys. Or [use xterm](https://vi.stackexchange.com/a/23344/17449).

But when I turn off Ultisnips, this mapping works as expected.

**Comment by SirVer** [comment]
@winkee01 Replace `<c-i>` through `<tab>` in your examples and you should see the same behaviour given you are using Vim in the terminal. Your expand trigger is likely set to `<tab>` that is why UltiSnips eats this mapping.

In either case, please provide a full repro case (because I cannot repo from this information alone), i.e. full Vimrc ideally working in the docker repro example.

**Comment by lacygoill** [comment]
> when I turn off Ultisnips, it works as expected.

The fact that disabling X makes an issue disappear doesn't necessarily mean that X is the root cause.
It could also be an interaction between X and Y.
Here, Y is the fact that Vim doesn't make the difference between `C-i` and `Tab`.

If UltiSnips is configured to use Tab to expand a snippet (via `g:UltiSnipsExpandTrigger`), then you can't map anything to `Tab` nor to `C-i`.

Again, you need to choose different keys.  Either configure UltiSnips to expand a snippet via another key, or use another key for your `<C-o>^` commands.

If you really want to use the `C-i` and `Tab` keys for different purposes, then you need a terminal which supports the modifyOtherKeys resource, such as xterm. Read `:h modifyOtherKeys` and the link I gave you in the previous comment.

**Comment by winkee01** [comment]
Thanks so much for the response @lacygoill and @SirVer 

here is my setting with regard to UltiSnips:

```
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
```

as you have explained, I understand now it's not possible to map <ctrl-i> to <c-o>^ in my case.
