### ISSUE TITLE
priority between vim-snippets UltiSnips and snippets directories

### ISSUE THREAD

**Issue by laoshaw** [SirVer/ultisnips#1214]
under vim-snippets there are two folders for snippets, vim-snippets/UltiSnips and vim-snippets/snippets(snipMate)

will UltiSnips search snippet definitions from both directories?

if there are snippets with the same name, .e.g both have html.snippets, who has higher priority?

UltiSnipsEdit! also never show shipMate snippets though those are actually been used by UntlSnips

**Comment by SirVer** [comment]
> will UltiSnips search snippet definitions from both directories?

yes

> if there are snippets with the same name, .e.g both have html.snippets, who has higher priority?

UltiSnips prefer its own snippets over snipMates iirc, but it seems simple to run an experiment to test that out?

> UltiSnipsEdit! also never show shipMate snippets though those are actually been used by UntlSnips

That is probably true. One could argue that it would be better if it did, because it uses them. On the other site, it is a command to edit UltiSnips snippets. 
Besides the logic of which files are searched, which files are edited and which files are suggested for editing has been changed multiple times and never was fully satisfactory. I would hesitate making it even more complicated by also pulling in snipMate snippets into this discussion.
