### ISSUE TITLE
Ultisnips autocommand causes Neovim freeze

### ISSUE THREAD

**Issue by urbainvaes** [SirVer/ultisnips#1239]
In vim/nvim, digraphs can be inserted with `<c-k>` in insert mode. The key combination `<c-k>e*`, for example, outputs the greek character epsilon. 

**Steps to reproduce**
In nvim, type `<c-k>e<bs>` in insert mode, which is useful to cancel the digraph if the letter `e` was a typo.

**Expected behavior:**
Should write <BS> in the buffer.

**Actual behavior:**
Neovim freezes. The bug does not appear in `vim`.

I spent some time tracking the bug, and it seems that the culprit is this autocommand in `plugin/ultisnips.vim`:
```vim
au InsertCharPre * call UltiSnips#TrackChange()
```

## Minimal .vimrc
With vim-plug installed:

```vim
call plug#begin('~/.vim/plugged')
Plug 'SirVer/ultisnips'
call plug#end()
```

- **Operating System**: Up to date Arch linux.
- **Vim Version**: NVIM v0.5.0-445-gca02db1f9
- **UltiSnips Version**: e83c8209 (up to date with master)
- **Python inside Vim**: 3.8.3

**Comment by lacygoill** [comment]
Possible duplicate of #1202, #1215, #1225 and #1227.

Try to update pynvim so that it includes [this commit](https://github.com/neovim/pynvim/commit/3791b2581eac4d2f1a829ab6792a122a0bb914fc).

---

@SirVer: just a suggestion, but it's probably at least the fifth report caused by the same underlying issue.  Maybe the original issue could be pinned so that users immediately find the solution, and stop opening various reports all caused by a third-party program.

**Comment by urbainvaes** [comment]
@lacygoill Many thanks for your quick response. The bug still occurs after an update of `pynvim`, but I can see that my issue is a duplicate of another one, so I will close it.

**Comment by lacygoill** [comment]
> The bug still occurs after an update of pynvim, but I can see that my issue is a duplicate of another one, so I will close it.

If the bug still occurs after updating pynvim, then your issue is not a duplicate.

---

I can't reproduce your issue with a minimal vimrc.  Try to run these shell commands:

    $ mkdir /tmp/snippets

    $ cat <<'EOF' >/tmp/snippets/vim.snippets
    snippet trigger
    my snippet has been expanded
    endsnippet
    EOF

    $ cat <<'EOF' >/tmp/vimrc
        let g:UltiSnipsSnippetDirectories = ['/tmp/snippets']
        let g:UltiSnipsExpandTrigger = '<tab>'
        set rtp-=$HOME/.vim
        set rtp-=$HOME/.vim/after
        set rtp^=$HOME/.vim/plugged/ultisnips
        set rtp+=$HOME/.vim/plugged/ultisnips/after
        filetype plugin on
    EOF

They should create a temporary snippets directory, with a snippets file inside, which includes one testing snippet.

Now, start Nvim like this:

    nvim -u /tmp/vimrc -i NONE +"put ='trigger'" +'startinsert!' /tmp/vim.vim

And press `Tab`; the tab trigger `trigger` should be expanded.  Now press `C-k e BS`, and check whether UltiSnips freezes.  On my machine it does not; I tested with `NVIM v0.5.0-553-gd8c5d122f`.

Run `:checkhealth` in Nvim, and make sure everything is ok in the `## Python 3 provider` section; here's what is written in my Nvim:

    ## Python 3 provider (optional)
      - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
      - INFO: Executable: /usr/bin/python3
      - INFO: Python version: 3.5.2
      - INFO: pynvim version: 0.4.1
      - OK: Latest pynvim is installed.

---

If you still have issues, try to disable the autotrigger feature by writing this somewhere in your `init.vim`:

    if has('nvim')
        au VimEnter * if exists('#UltiSnips_AutoTrigger')
            \ |     exe 'au! UltiSnips_AutoTrigger'
            \ |     aug! UltiSnips_AutoTrigger
            \ | endif
    endif

If you want to be able to toggle the feature on-demand, try this:

    nno <silent> cou :<c-u>call Ultisnips_toggle_autotrigger()<cr>

    fu Ultisnips_toggle_autotrigger() abort
        if exists('#UltiSnips_AutoTrigger')
            au! UltiSnips_AutoTrigger
            aug! UltiSnips_AutoTrigger
            echom '[UltiSnips AutoTrigger] OFF'
        else
            augroup UltiSnips_AutoTrigger | au!
                au InsertCharPre,TextChangedI,TextChangedP * call UltiSnips#TrackChange()
            augroup END
            echom '[UltiSnips AutoTrigger] ON'
        endif
    endfu

Press `cou` (mnemonic: "Change Option UltiSnips") to toggle the autotrigger feature on an off.  When it's off, you should not see Nvim freeze.

**Comment by urbainvaes** [comment]
Many thanks for this! I still have the issue with your first suggestion, but disabling the autocommand works for now. The result of `checkhealth` on my system is the following:
```
## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.8.3
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.
```

**Comment by Shougo** [comment]
pynvim update does not work.
Because the commit is not released in pip.
You need to install github version of pynvim.

**Comment by urbainvaes** [comment]
@Shougo This fixed it, thanks! :)

```
pip install --user git+https://github.com/neovim/pynvim
```
