### ISSUE TITLE
Ultisnips cannot detect default user folder for NeoVim on Windows.

### ISSUE THREAD

**Issue by xarthurx** [SirVer/ultisnips#1252]
**Expected behavior:**
I can edit my own snippets when using `:UltiSnipsEdit`.

**Actual behavior:**
A message pop up:

`UltiSnips was not able to find a default directory for snippets. Do you have a .vim directory? Try :UltiSnipsEdit! instead of :UltiSnipsEdit.`

**Steps to reproduce**

1. Install UltiSnips for Neovim using *vim-plug* on Windows 10.

2. type `:UltiSnipsEdit`.

PS.1: If I use  `:UltiSnipsEdit!`.
only the official snips from `vim-snippets` was listed.
![image](https://user-images.githubusercontent.com/1921878/85388366-51076a00-b546-11ea-9338-e7b399a709ce.png)

PS.2: I tried adding dirs and runtimes in the `init.vim` file, but things don't get better.
Is it because ultisnips only check the `$XDG_CONFIG` folder for linux machines, but not `$LOCALAPPDATA` where Nvim is installed on Windows?

-----

- **Operating System**:  Windows 10
- **Vim Version**:  Neovim latest.
- **UltiSnips Version**:  latest.
- **Python inside Vim**:  3.7
- **Docker repo/vimrc**:

**Comment by xarthurx** [comment]
Additional notes:

If I set `g:UltiSnipsSnippetDirectories` to a dir with an absolute path, then I can edit my own snippets.
But once I include the keyword `UltiSnips` in that settings (or use it only as the default settings), the above issue will occur.

**Comment by Kiniwara** [comment]
Same problem, vim-plug, win10

**Comment by FruitDZign** [comment]
I have the exact same issue as xarthurx and Yonshoku (neovim v0.5.0-811 and then neovim v0.5.0-828 64 bits + Windows 10 20H2 + Python 3.7 + vim-plug)
Even when setting the absolute path of my snippets or adjusting the runtimepath variable I had the same error.

**Comment by cristianUrbina** [comment]
You need to create a directory called UltiSnips inside ~/.vim directory
`mkdir ~/.vim/UltiSnips`

**Comment by SirVer** [comment]
I have no idea what Neovim does differently so this does not work. Please try reproducing with Vanilla Vim. I'll leave the ticket open for a while until I see a repro with Vanilla Vim, otherwise I assume this is a neovim only problem.

This issue was deprioritized due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).

**Comment by SirVer** [comment]
@xarthurx UltiSnips is using `rtp` like any Vim plugin should. It does not have a "default folder" per se. I have no idea if and if yes, how Neovim has deviated from this. If a simple patch is possible, I gladly accept a pull request.

**Comment by igor-ribeiro** [comment]
BTW, it works if you create the folder inside `~/.config/nvim/` instead of `~/.vim/`

**Comment by Tsingv** [comment]
I'm using neovim now, and I use `let g:UltiSnipsSnippetDirectories = ["~/.config/nvim/UltiSnips"]` in my init.vim, which probably fixed the issue. (Attention to the '[')

Because I found the origin `g:UltiSnipsSnippetDirectories` is set to `['UltiSnips']` only, it can't be expand to an absolute path. Besides, my `&runtimepath` has no `~/.config/nvim` so `Path(snippet_dir).parent` can't be neovim's "dot_vim_dir". If you specify `g:UltiSnipsSnippetDirectories`, it would return directly without traverse `&runtimepath`.

**Comment by marcdeop** [comment]
I created a [PR](https://github.com/SirVer/ultisnips/pull/1480) that should fix this. At least it allows NeoVim and Vim to work properly on my system :-)

I cannot test on windows but it would be appreciated if anybody could try (@xarthurx perhaps?)

FYI: what @igor-ribeiro mentions [here](https://github.com/SirVer/ultisnips/issues/1252#issuecomment-1085419453) is because `get_dot_vim()` only handles *one* file which happens to be `~/.config/nvim/` (only due to **ordering** in the code :man_shrugging: )
