### ISSUE TITLE
Change SheBangs in the repo to use python3 instead of python

### ISSUE THREAD

**Issue by hdelan** [SirVer/ultisnips#1283]
**Expected behavior:**
I expect that the test_all.py would work.

**Actual behavior:**
```
Traceback (most recent call last):
File "./test_all.py", line 228, in <module>
   sys.exit(main())
File "./test_all.py", line 206, in main
   all_other_plugins.update(test.plugins)
AttributeError: 'ModuleImportFailure' object has no attribute 'plugins'
```

**Steps to reproduce**

My minimal init.vim:
```
call plug#begin()

" Ultisnips
Plug 'SirVer/ultisnips'
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
let g:UltiSnipsSnippetDirectories=[$HOME.'/.config/nvim/plugged/mysnippets']

setlocal spell
set spelllang=en_us
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u

call plug#end()

```
I have tried a fresh install of ultisnips directory but still get same failure. I have tried on both Linux Mint and Mac OS. 

-----

- **Operating System**: Linux Mint 5.4.0-51-generic && Mac OS Catalina
- **Vim Version**: NVIM v0.4.3
- **UltiSnips Version**: 4104d1ff31420a4fcb008ef3309850c5c5366df0
- **Python inside Vim**: 
2.7.18 (default, Aug  4 2020, 11:16:42)
3.8.5 (default, Jul 28 2020, 12:59:40)
- **Docker repo/vimrc**:

**Comment by Rincefeu** [comment]
I think it's because you use python2.

If you run test_all.py in a terminal with the command : $ ./test_all.py
the python used will depend on the shebang of test_all.py which is : #!/usr/bin/env python
But this shebang does not specify a version number.  In this case, the python launched is the one corresponding to the first executable file found, according to the order of your $PATH, starting with the letters "python". And if it is a python2 there will be a problem...

You can test the python actually used by this shebang and your $PATH by typing directly in a terminal: $ /usr/bin/env python

To solve the problem, (at least) three solutions you can :
- work on the order of your $PATH or the localization of your different versions of python (a bit difficult);
- replace the current shebang in test_all.py by : #!/usr/bin/env python3
The python used will then be the first executable file found starting with the letters "python3";
- run the tests with a command specifically calling a python3 : $ python3 ./test_all.py

**Comment by SirVer** [comment]
+1 for changing the shebangs to mention python3 everywhere. Thanks for bringing this up @Rincefeu

**Comment by hdelan** [comment]
Thanks for help!
