### ISSUE TITLE
Camelcase bug in NeoVim

### ISSUE THREAD

**Issue by GiancarloAparicio** [SirVer/ultisnips#1319]
I would like to create a snippet that transforms the first letter into uppercase.
So I started reading an old [blog](https://www.sirver.net/blog/2012/01/08/second-episode-of-ultisnips-screencast/) of yours and found this snippet:
```snippet
snippet title "Titelize in the Transformation"
${1:a text}
${1/\w+\s*/\u$0/g}
endsnippet
```

But when using it instead of converting the first letter to uppercase prepend '\ u', I also tried other ways and with interpolation with python but in all cases it appeared '\ u':
```snippet
snippet title1 "Titelize in the Transformation"
${1:text}
${1/\w+\s*/\u$0/g}
endsnippet

snippet title2 "Titelize in the Transformation"
$1
${1/\w+/\u$0/g}
endsnippet

snippet title3 "Titelize in the Transformation"
${1:text}
${1:`!p snip.rv = t[1].title()`}
`!p snip.rv = t[1].title()`
endsnippet
```

**Expected behavior:**
![imagen](https://i.stack.imgur.com/3JjKa.gif)

**Actual behavior:**

![imagen](https://user-images.githubusercontent.com/61440825/108940846-1187a500-7622-11eb-8156-d7c322a2b1b5.png)

![imagen](https://user-images.githubusercontent.com/61440825/108940977-4267da00-7622-11eb-9864-2ba92323d65d.png)

Except for the number 3 with interpolation, that one just behaves as if it were:

```snippet
snippet title "Titelize in the Transformation"
${1:text}
${1:text}
endsnippet
```

-----

- **Operating System**: Linux Mint 20
- **NeoVim Version**: v.0.4.3
- **UltiSnips Version**: v.3.2
- **Python inside Vim**: 3.8.5 (The command returns error `:py import sys; print(sys.version)` but in my OS I also have v2.7.18)

**Comment by SirVer** [comment]
Works in Vim proper, seems to be another incompatibility of NeoVim. See here the recording in vim: https://asciinema.org/a/YcYP2T1qCGwig332ykf1UcWCJ.


This issue was closed due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).
