### ISSUE TITLE
Choosing between one of many parameters

### ISSUE THREAD

**Issue by medwatt** [SirVer/ultisnips#1321]
I am writing my own snippet file for SPICE and I find myself in situations where I have several statements that vary only slightly.

As an example, to perform ac analysis, we can choose whether we would like to use a decade, linear, etc., sweep. So, an ac analysis command for linear and decade sweeps would look like:

`.ac lin start stop`

`.ac dec start stop`

I was wondering if it is possible to have only one snippet and when we get to the location where we need to choose between `lin` and `dec`, we get some sort of a drop-down menu. Is this possible with ultisnips ?

**Comment by SirVer** [comment]
There are multiple ways how to do it. UltiSnips does not provide dropdown selections, since this is not a build in Vim feature. But it has [choices](https://github.com/SirVer/ultisnips/blob/66d81fc2c0bda30be69fffa46da0932ee8d5ddd5/doc/UltiSnips.txt#L1195), which I find to be a bit finicky to use but should work for you. You select which one you want by typing 1 or 2 at the correct place.

```
snippet ac "AC Description" b
.ac ${1|lin,dec|} start stop
endsnippet
```

I usually prefer using regular expression triggers and encode the variations within them:

```
snippet 'ac([ld])' "AC Description" r
.ac `!p if match.group(1) == 'l':
	snip.rv = 'lin'
else:
	snip.rv = 'dec'` start stop
endsnippet
```

This can be expanded as `acl` or `acd`. I find this more comfortable, but is not really what you asked for, because in some sense these are two different snippets.

**Comment by medwatt** [comment]
Thanks!
