### ISSUE TITLE
tex: ultisnip does not expand snippet after $ with snipMate format

### ISSUE THREAD

**Issue by lkjell** [SirVer/ultisnips#1325]
**Expected behavior:**
`$frac` will expand to `$frac{}{}`

**Actual behavior:**
Does not expand `$frac` 

**Steps to reproduce**
Using snippets from https://github.com/honza/vim-snippets

* First ensure that the snippet frac is not in the file Ultisnips/texmath.snippets or any Ultisnips files.
* Check that the snippet frac is in snippets/tex.snippets or define a snippet in snipMate format
* check if `$frac`  expand to `$frac{}{}`

snipMate format
```
snippet frac \frac{}{}
	\\frac{${1:num}}{${2:denom}} ${0}
```

Ultisnip format
```
snippet frac "Fraction" w
\frac{${1:${VISUAL:nom}}}{${2:denom}}
endsnippet

```
Cross link to https://github.com/honza/vim-snippets/issues/1340

-----

- **Operating System**: Arch linux
- **Vim Version**: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 09 2021 23:51:55)
Included patches: 1-2489

- **UltiSnips Version**: 66d81fc2c0bda30be69fffa46da0932ee8d5ddd5
- **Python inside Vim**: 3.9.2/ 2.7.18 (python 3 is used in vim by default)
- **Docker repo/vimrc**: N/A

**Comment by SirVer** [comment]
I assume (without reading the code just now again) UltiSnips is not expanding this here because `$` is not part of `iskeyword`. IIRC that was the behavior that snipMate also had, i.e. I emulated snipMate here, since these snippets should behave like snipMate did for UltiSnips to be a fully viable alternative.

I conjecture that snipMate is not a popular choice for pure VimScript snippet engines these days and newer engines might make the trigger decision differently. I am not sure what UltiSnips should do here though, being compatible with snipMate always seemed the correct default and I do not see a clear winner in the pure VimScript snippet engine field to emulate.

The conceptually simplest choice would be to reinstantiate the UltiSnips only snippets in vim-scripts, but I can see why that is undesirable to the maintainers of vim-script. I am not sure what direction to take this issue, very interested in other peoples opinions. 

@lpil fyi.

**Comment by lkjell** [comment]
I just checked with snipmate engine: https://github.com/garbas/vim-snipmate
With version 0 and 1 parser. There is no requirement that there must be a space between $ and frac. They must have improved a lot.

**Comment by SirVer** [comment]
@lkjell Thanks for clarifying. So the ideal course forward here would be:

1. add a test for this bug.
2. ensure that triggering of snipMate snippets follows the rules of snipMate, i.e. `$frac` is considered one word.

**Comment by SirVer** [comment]
I was in the mood of some light coding, so I went ahead and fixed this issue today. @lkjell Thanks for doing the communication work required to get this fixed!

**Comment by lkjell** [comment]
Thank you. I just test it works.

**Comment by roachsinai** [comment]
This commit introduced a wrong expand (combine with YouCompleteMe) for me that all `text` follow a `.` will change to `text` append a `self.` like below

https://files.gitter.im/532b1c115e986b0712eff4b6/ukLP/Peek-2021-04-13-23-27.gif

and my untisnips setting is:

```
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

let g:UltiSnipsSnippetsDir="~/.vim/snip"
let g:UltiSnipsSnippetDirectories=["snip", "UltiSnips"]

" https://github.com/ycm-core/YouCompleteMe/issues/36#issuecomment-171966710
function! UltiSnips_Complete()
  call UltiSnips#ExpandSnippet()
  if g:ulti_expand_res == 0
    if pumvisible()
        return "\<C-n>"
    else
      call UltiSnips#JumpForwards()
      if g:ulti_jump_forwards_res == 0
        return "\<TAB>"
      endif
    endif
  endif
  return ""
endfunction

function! UltiSnips_Reverse()
  call UltiSnips#JumpBackwards()
  if g:ulti_jump_backwards_res == 0
    return "\<C-P>"
  endif

  return ""
endfunction

let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

au InsertEnter * exec "inoremap <silent> " . UltiSnipsExpandTrigger . " <C-R>=g:UltiSnips_Complete()<cr>"
au InsertEnter * exec "inoremap <silent> " . UltiSnipsJumpBackwardTrigger . " <C-R>=g:UltiSnips_Reverse()<cr>"
```

**Comment by roachsinai** [comment]
This commit means commit: https://github.com/SirVer/ultisnips/commit/b974a13328071de45a85c62ab65c8bfed0142728

And appreciated for any helps!
