### ISSUE TITLE
Ask for confirmation when writing ipdb because conflicts with pdb

### ISSUE THREAD

**Issue by 00sapo** [SirVer/ultisnips#1340]
Hello, don't know why, but starting from today, when I trigger utilsnips after writing 'ipdb' it asks if I want to expand the 'pdb' or the 'ipdb' snippet. I had just done an update of all the plugins, but I don't know if it matters...

I think that it shouldn't suggest to complete 'pdb' if I have written 'ipdb'.

**Comment by joeltaylor** [comment]
I'm having a similar issue with Ruby and expanding `pry`. It gives me the choice between `y` and `pry`. It looks like the behavior was introduced via https://github.com/SirVer/ultisnips/pull/1336. I'm not very familiar with snipMate though to make sense of the change.

**Comment by SirVer** [comment]
This is very likely due to https://github.com/SirVer/ultisnips/pull/1336 which I might have misinterpreted. The fix for this is to try the `w` option instead of the `i` option or do some more logic and adding a test for `ipdb` vs `pdb`.

Thanks for reporting!

**Comment by csaez** [comment]
@SirVer Thanks for the suggestion!
Changing the option from `i` to `w` seems to pick the snippet selected instead of asking for confirmation (which happen very often for me, after almost any snippet).
I've no idea about the ramifications of this change or what these options stand for (just a regular user here), but this improves the user experience 100% :+1:

**Comment by 00sapo** [comment]
For me works too

**Comment by SirVer** [comment]
Fixed in #1345
