### ISSUE TITLE
Syntax capitalize doubt

### ISSUE THREAD

**Issue by carlosala** [SirVer/ultisnips#1348]
Hi!
This is not an issue, but I have a question about one thing. I have the following snippet:
```
snippet use "useState"
const [${1:state}, set$1] = useState(${2:initialState})
endsnippet
```
The snippet works perfectly, but I want the second `$1` with the first letter capitalized. For instance, for `$1=foo` and `$2=['hello']`, I want to have the following text:
```
const [foo, setFoo] = useState['hello']
```
Is this possible with some Ultisnips syntax? How can I change my snippet to get this result?
Thanks!

**Comment by carlosala** [comment]
I found this in the docs, that works:
```
snippet use "useState"
const [${1:state}, set${1/\w+\s*/\u$0/}] = useState(${2:initialState})
endsnippet
```
Could anyone explain me this regex syntax? I don't undestand it.
Thanks!

**Comment by carlosala** [comment]
Regex is something very tricky for me, but searching in Python's re library I nearly understand what's going on.
Sorry for this issue

**Comment by SirVer** [comment]
The transformations that this is using are documented here: https://github.com/SirVer/ultisnips/blob/204b501cc8f4acd7f32ebdea262bd5772ca007a2/doc/UltiSnips.txt#L1259. 4.7.1 explains the replacement syntax which is lifted from TextMate (a now defunct Mac OS Text editor that was pretty good). To break this down:

`\w+\s*` matches a Word character, followed by any number of whitespace characters.
and the replacement: `\u$0` means 'uppercase the next letter and put here the full match for the regular expression in the search string'. 

I would personally probably write the snippet in this way, using Python interpolation instead of a transformation. I find it more readable

```
snippet use "useState"
const [${1:state}, set`!p snip.rv = t[1].title()` = useState(${2:initialState})
endsnippet
```

**Comment by carlosala** [comment]
Thank you, I really understood it!
Great project, thanks for you work!
