### ISSUE TITLE
Entering normal mode while in nested snippet renders normal mode slow

### ISSUE THREAD

**Issue by dadaurs** [SirVer/ultisnips#1355]
This is an issue I've been running into somewhat frequently while typing latex.
Suppose that I trigger two nested snippets, for instance, I type `al` to trigger an align environment, and then type int<Tab>to expand to an integral command, I end up with something like this
```
\begin{align*}
\int_{ } ^ { | } 
\end{align*}
```
where `|` is my cursor.
If I now enter normal mode, there is a quite noticeable lag between my keypress and the action related to this keypress.
To fix this, I need to reenter insert mode and press tab a couple of time, then the lag completely disappears.
If I don't press tab, the lag persists in insert mode.

The code for the two snippets I used is 
```
snippet int "int" i
\int_{ $1 }^{ $2 }$0
endsnippet
```
and
```
snippet al "align" bA
\begin{align*}
$1
\end{align*}
$0
endsnippet
```
I do also experience similar lag when I don't exit insert mode for a while and have triggered a few snippets.
I haven't tested this issue on standard vim since I exclusively use neovim.
I've always experienced this issue, so I don't believe my python versions etc are relevant, nevertheless, here they are
```
$ python -V
Python 3.9.5
$ nvim -v
NVIM v0.5.0-dev+1177-g095f5da79
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az49-10

Features: +acl +iconv +tui
```

**Comment by SirVer** [comment]
You probably have many many snippets active after you typed for a while, this will make a lot of calculations necessary. They will feel much slower in neovim than in vanillavim, since neovim is running python out of process which adds a lot of delay. 

Please see if you can reproduce in vanillavim and I'll investigate then.

This issue was closed due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).

**Comment by dadaurs** [comment]
Indeed, the issue doesn't persist on vim, sorry for the noise.
