### ISSUE TITLE
os.system runs cmd many times

### ISSUE THREAD

**Issue by junyixu** [SirVer/ultisnips#1361]
**Expected behavior:**
Execute  the cmd once

**Actual behavior:**
Execute the cmd several times

**Steps to reproduce**

```
snippet i "include png" b
\includegraphics[width=0.5\textwidth]{`!p
import os
filename='test.png'
director='figures/'
fullpath=director+filename
cmd='flameshot gui --raw > ' + fullpath
os.system(cmd)
snip.rv=fullpath
`}
$0
endsnippet
```

I tried
```
snippet i "include png" b
\includegraphics[width=0.5\textwidth]{`!p
import os
filename='test.png'
director='figures/'
fullpath=director+filename
cmd='flameshot gui --raw > ' + fullpath
if not snip.c:
    os.system(cmd)
    snip.rv=fullpath
`}
$0
**endsnippet**
```
But [flameshot](https://github.com/flameshot-org/flameshot) GUI didn't appear.

-----

- **Operating System**: 
Arch Linux
- **Vim Version**: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 28 2021 06:58:52)                                                                                                                                   
Included patches: **1-2891**
- **UltiSnips Version**: 
204b501cc8f4acd7f32ebdea262bd5772ca007a2
- **Python inside Vim**: 
3.9.5 (default, May 24 2021, 12:50:35)
[GCC 11.1.0]
- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
I reduced your provided example to 

```
snippet blub "include png" b
`!p
if not snip.c:
    os.system("date >> /tmp/blub.txt")
    snip.rv="foo"
`$0
endsnippet
```

since I do not have the tools that you mention in your snippet. My expected behaviour is that everytime I execute that snippet, a single line is added to `/tmp/blub.txt` and that is exactly what is happening. Can you try reproducing with the snippet I provided?

**Comment by junyixu** [comment]
![image](https://user-images.githubusercontent.com/40481594/120999198-6dce9900-c7bb-11eb-8576-1a79d02a5c87.png)

**Comment by junyixu** [comment]
Thank you very much for your reply!
Flameshot is a fantastic screenshot tool that is worth a shot. 
I also try it in IPython, and it works.
![image](https://user-images.githubusercontent.com/40481594/121000339-ad49b500-c7bc-11eb-9a02-15cb13e27f23.png)

**Comment by SirVer** [comment]
Dunno what I can say. Apparently everything works when you use my snippet and it fails when you use this flameshot tool. I am unable to get this tool to run on my Mac, so I cannot reproduce.

What can we do next?

**Comment by junyixu** [comment]
I'm terribly sorry to trouble you.
But so does [maim](https://github.com/naelstrof/maim).
Maybe all interactive screenshot tools fail?...
Could you please try maim or other interactive screenshot tools?

**Comment by SirVer** [comment]
Sorry, neither maim nor flameshot are easy to install on MacOS, so I cannot further investigate. It seems likely that UltiSnips would fail to work correctly if Vim is loosing focus during snippet expansion, because loosing focus will trigger termination of the current snippet. It will be quite undefined what happens in such cases.

Sorry, but that does not seem to be a good use case for UltiSnips.
