### ISSUE TITLE
UltiSnipsEdit opens blank files instead of existing snippets

### ISSUE THREAD

**Issue by idbrii** [SirVer/ultisnips#1364]
**Expected behavior:**

`:UltiSnipsEdit` always opens an existing file if one can be found.

**Actual behavior:**

`:UltiSnipsEdit` creates ~/.vim/ultisnips and opens an empty file.

(And the folder name doesn't even match the case of `g:UltiSnipsSnippetDirectories`.)

**Steps to reproduce**

1. Create ~/vimfiles (if it already exists, rename it and create a new one). (This step prevents the "not able to find a default directory" error.)
1. Using minimal vimrc run `gvim -Nu ~/.vim/reprovimrc.vim -U NONE`
2. Type `if<Tab>` to show that snippets are found and work.
2. `:UltiSnipsEdit`
1. Bug: An empty file is opened.
2. `:UltiSnipsEdit!`
1. Bug?: The output includes two files that don't exist (3,4):

```
* 1: c:\users\idbrii\.vim\bundle\snippets\ultisnips\all.snippets
* 2: c:\users\idbrii\.vim\bundle\snippets\ultisnips\snippets.snippets
  3: c:\users\idbrii\vimfiles\ultisnips\all.snippets
  4: c:\users\idbrii\vimfiles\ultisnips\snippets.snippets
Type number and <Enter> or click with the mouse (q or empty cancels): 
```

## minimal vimrc 
```vim
" all plugins should work with sensible as a baseline.
let s:plugins = ['sensible']

let s:plugins += ["ultisnips"]
" Some existing snippets to open.
let s:plugins += ["snippets"]

set runtimepath-=~/.vim
set runtimepath-=~/.vim/after
for plugin in s:plugins
    exec "set runtimepath^=~/.vim/bundle/". plugin
    exec "set runtimepath+=~/.vim/bundle/". plugin ."/after"
endfor
set viminfofile=NONE
colorscheme desert

let $PYTHONHOME = expand('$USERPROFILE/scoop/apps/python39/current')
let $PYTHONPATH = $PYTHONHOME . "/Lib"
let $PATH = $PATH . ';' . $PYTHONHOME
```

-----

- **Operating System**: Windows 10
- **Vim Version**: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 10 2021 23:02:05)
MS-Windows 64-bit GUI version with OLE support
- **UltiSnips Version**: 
b6c9a814a4fdfcad3ea53d8888746803a7218a9e
- **Python inside Vim**: 
3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
- **Docker repo/vimrc**: 
                              None

**Comment by idbrii** [comment]
I noticed this because I set `g:UltiSnipsSnippetsDir` and after updating past  298f4c2 that variable doesn't work. The workaround is to use g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit  instead.

Updating my minimal vimrc with the old and new settings:

```vim
let g:UltiSnipsSnippetsDir = '~/.vim/bundle/snippets/UltiSnips/'
let g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit = '~/.vim/bundle/snippets/UltiSnips/'
```

And trying on b6c9a81 (latest) and 16c4e4a (before above change), both show the same behaviour.

So it seems like the bad behaviour isn't new. However, I don't see why it makes sense for ultisnips to try to create a new file instead of locating an existing one.

**Comment by SirVer** [comment]
What happens if you do not set `let g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit` at all?

**Comment by idbrii** [comment]
If neither is set, the original report occurs: a new file is opened. I believe that is also true on the older commit.

**Comment by SirVer** [comment]
Last question: What does the bang command do for you? `:UltiSnipsEdit!`.

**Comment by idbrii** [comment]
On b6c9a81 it shows files that don't exist (3,4):

```
:UltiSnipsEdit!

* 1: c:\users\idbrii\.vim\bundle\snippets\ultisnips\all.snippets
* 2: c:\users\idbrii\.vim\bundle\snippets\ultisnips\snippets.snippets
  3: c:\users\idbrii\vimfiles\ultisnips\all.snippets
  4: c:\users\idbrii\vimfiles\ultisnips\snippets.snippets
Type number and <Enter> or click with the mouse (q or empty cancels): 
```

**Comment by SirVer** [comment]
I'll try to summarize my view on the current issue:

> On b6c9a81 on my above minimal config, it shows files that don't exist (3,4):

This is intentional. Bang is meant to show all possible files that would match in the current scope so that the user can fine tune which file to use. So this is working as intended.

> g:UltiSnipsSnippetDirectories 

is used as a heuristic to try to edit files in the users homedir. This seems to be used in your case.

> However, I don't see why it makes sense for ultisnips to try to create a new file instead of locating an existing one.

UltiSnips is not seeking out for existing files, it will default to the first option it finds, because people were complaining that UltiSnips used to open files in third party plugins which was found to be undesirable. So this is working as intended too. 

However, to overwrite this behaviour we have the long variable. If 

> UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit

is set to "a single absolute path" (https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L187) it should always be used to find the path to edit. Note that in your example you do not set it to an absolute path - I do not think `~` is a well defined concept under Windows, but I would not know since i never use Windows.

The formerly used variable `UltiSnipsSnippetsDir` had unclear semantics and was confusing (since it affected both search path for editing and for finding snippets), hence we removed it.

Try setting `UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit` to a full path and see what happens. Note that if that does not work for you, I'll need a minimal reproducible repro case (because your minimal vimrc does not reproduce the problem for me on Mac OS; and it also does not mention any of the UltiSnips variables). It could be that this problem is windows only in which case you would probably need to dig in yourself, since I have no access to a windows computer.

**Comment by idbrii** [comment]
I see the same behaviour on macos. Here's my minimal vimrc for macos:

```
runtime bundle/pathogen/autoload/pathogen.vim
call pathogen#infect()
```

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 01 2021 08:32:44)
macOS version - x86_64
Included patches: 1-2681

tpope/vim-pathogen@c6bc42404597c718e4a032a98e21e63321cbb05a
tpope/vim-sensible@7aa7dba2a2594c209d8063c4c1c56de130c362d3
honza/vim-snippets@a85fb1d98d9ee94e0a9c08dece103a5994612fb7
vim-ultisnips b6c9a814a4fdfcad3ea53d8888746803a7218a9e

I removed my vim config, created ~/.vim/bundle and cloned the above.

**Comment by idbrii** [comment]
> UltiSnips is not seeking out for existing files, it will default to the first option it finds, because people were complaining that UltiSnips used to open files in third party plugins which was found to be undesirable. So this is working as intended too.

Rereading this, I think I understand. `:UltiSnipsEdit` is supposed to be "open a snippet file for this filetype in my config and intentionally ignore plugins". If I want to edit snippets in a plugin, I need to use `:UltiSnipsEdit!` or set `g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit` to the plugin containing my snippets. In my case, I have snippets in two plugins (vim-snippets and my own david-snippets). So I'll have to set the long variable to david-snippets and use the bang to find vim-snippets.

Setting the variable works as expected:

    let g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit = '~/.vim/bundle/snippets/UltiSnips/'
