### ISSUE TITLE
Question: How to disable a single snippet

### ISSUE THREAD

**Issue by dapc11** [SirVer/ultisnips#1401]
Is there a way to disable a snippet, for example 'c)', which is automatically chosen when I close paranthesis. 

If there is a way, how can I achieve it? 

Thanks for a good plugin.

**Comment by hl037** [comment]
See section 4.9 of the documentation : "Custom context snippet"

...Then you can define a global function python that checks the presence a vim variable (see `help :py`), and call it from the context expression

**Comment by SirVer** [comment]
@dapc11 What @hl037 suggesting will also require changes to the snippet file, which is my understanding is something that you want to avoid, right?

At this point in time, UltiSnips does not have affordances to disable certain snippets through a configuration. I have no plans of adding this, because it feels like duplicating effort: the snippet files are the configuration for snippets, having out of bands configuration to ignore parts of the snippet files seems cumbersome and complicated. My suggestion is that you copy & paste the snippets you like instead of cloning a ready made snippet repository.

**Comment by dapc11** [comment]
@SirVer thanks for the clarification and suggestion. Will for sure extract the snippets I want in the future for better control. And once again, thanks for a good plug-in!

**Comment by winkee01** [comment]
> My suggestion is that you copy & paste the snippets you like instead of cloning a ready-made snippet repository.
Probably a reasonable (not optimal) solution.
