### ISSUE TITLE
CPU usage with autotrigger enable

### ISSUE THREAD

**Issue by medwatt** [SirVer/ultisnips#1409]
I've always noticed a slight lag while using ultisnips inside insert mode. While browsing through the issues, I came across disabling `autotrigger` functionality. That actually helped.

Here's a [video](https://streamable.com/st7b5e) I recorded that shows a non-trivial Python CPU usage while doing nothing but pressing down a key. Disabling `autotrigger` fixes the lag and CPU usage. My question is, is this a bug or expected behaviour?

I am using:
- Neovim 0.6
- pynvim 0.4.3
- Kitty terminal

**Comment by SirVer** [comment]
This is to be expected in NeoVim (but not in Vanilla Vim). Their out-of-core python process adds a lot of communication overhead, probably mostly serialization and deserialization of the process data. This adds chunk and of course CPU load. This is one of the reasons why NeoVim is hard to properly support in UltiSnips and why I am so tired of hearing about it.

This issue was closed due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).
