### ISSUE TITLE
NVIM v0.6.0 take into account changes to the runtimepath

### ISSUE THREAD

**Issue by camilledejoye** [SirVer/ultisnips#1414]
Snippets provided by plugins are no longer loaded using Neovim >= v0.6.0
This is the [commit](https://github.com/neovim/neovim/commit/9df7e022b498cb74ffbf5b8fd2ddc4dd5c04d127) introducing the change.
The paths of `start` packages in the `runtimepath` are no longer expanded, so instead of having an entry for each of them there is only one matching `/home/<username>/.local/share/nvim/site/pack/*/start/*`.

**Expected behavior:**
Load the snippets provided by plugins.

**Actual behavior:**
Snippets provided by plugins are not found.

**Steps to reproduce**
With the usual setup, open nvim using the correct version by using the appimage:
```sh
curl -LO https://github.com/neovim/neovim/releases/download/v0.6.0/nvim.appimage
chmod u+x nvim.appimage
```

Try to expand a snippet provided by a plugin stored in the `start` package's directory.

-----
I'm not comfortable with Python but I think it could be easily fixed in: https://github.com/SirVer/ultisnips/blob/2c83e40ce66814bf813457bb58ea96184ab9bb81/pythonx/UltiSnips/snippet/source/file/ulti_snips.py#L61-L64
My temporary fix is:
```py
            pth = normalize_file_path(
                os.path.expanduser(os.path.join(rtp, snippet_dir))
            )
            if '*' in pth:
                for fn in glob.glob(pth):
                    all_dirs.append(fn)
            else:
                all_dirs.append(pth)
```

-----

- **Operating System**: Arch Linux 5.15.7
- **Vim Version**: NVIM v0.6.0
- **UltiSnips Version**: 2c83e40ce66814bf813457bb58ea96184ab9bb81
- **Python inside Vim**: 3.9.9

**Comment by SirVer** [comment]
Actually, NeoVim is really leaving a bad taste in my mouth... so many of the bugs in UltiSnips are NeoVim only, and just because they deviate further and further from being Vim compatible. What is the thought process behind this change even? I wish they would rename that damn thing finally, stop pretending to be compatible and just make it something different entirely. Sigh.....

I will not work on this issue, but if there is a PR provided by somebody that does not break Vanilla Vim compatibility, I will accept it. I'll leave this one open for now for that reason, but might close it for inactivity at some point. I leave the usual disclaimer about NeoVim below.


This issue was marked to only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).

**Comment by hl037** [comment]
Note that in vim too, you can have wildcard entries in `rtp` : 

`:h rtp<cr> 71j`
>  	Note that, unlike 'path', no wildcards like "**" are allowed.  Normal
> 	wildcards are allowed, but can significantly slow down searching for
> 	runtime files.  For speed, use as few items as possible and avoid
> 	wildcards.

I think it may actually be safer to always extend all_dirs with glob : 

```
pth = normalize_file_path(
    os.path.expanduser(os.path.join(rtp, snippet_dir))
)
all_dirs.extend(glob.glob(pth))
```
