### ISSUE TITLE
Error while using vim-snippets

### ISSUE THREAD

**Issue by b3g00d** [SirVer/ultisnips#1428]
**Expected behavior:**
ifm snippets complete the quotes

**Actual behavior:**
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 47, in wrapper
    return func(self, *args, **kwds)
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 173, in expand
    if not self._try_expand():
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 810, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 759, in _do_snippet
    snippet_instance = snippet.launch(
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/definition/base.py", line 523, in launch
    snippet_instance.update_textobjects(vim_helper.buf)
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/snippet_instance.py", line 102, in update_textobjects
    if obj._update(done, buf):
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/python_code.py", line 284, in _update
    exec(compiled_code, self._locals)  # pylint:disable=exec-used
  File "<exec-interpolation-code>", line 1, in <module>
NameError: name 'get_quoting_style' is not defined

Executed snippet code:
  1 > snip.rv = get_quoting_style(snip)
```

**Comment by SirVer** [comment]
```
NameError: name 'get_quoting_style' is not defined

Executed snippet code:
  1 > snip.rv = get_quoting_style(snip)
```

Your snippet is using a function `get_quoting_style` that is not defined. Did you write the snippet yourself?

**Comment by b3g00d** [comment]
@SirVer all my snippet are using vim-snippets.

**Comment by b3g00d** [comment]
error in on this line https://github.com/honza/vim-snippets/blob/master/UltiSnips/python.snippets#L30
and I try to patch for override this error
```
if __name__ == "__main__":
```

**Comment by SirVer** [comment]
@b3g00d This function is defined in the same file: https://github.com/honza/vim-snippets/blob/master/UltiSnips/python.snippets#L109. Are you just copying the snippet without adding the `global !p` block? How are you making use of this snippet?

**Comment by b3g00d** [comment]
@SirVer everything I am using is original, nothing changed at all.

**Comment by delvatt** [comment]
I think I am experiencing the same issue since a couple of days, therefore I am just commenting here but just let me know if I am wrong.

```An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/hacker/.vim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 47, in wrapper
    return func(self, *args, **kwds)
  File "/home/hacker/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 173, in expand
    if not self._try_expand():
  File "/home/hacker/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 810, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/hacker/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 759, in _do_snippet
    snippet_instance = snippet.launch(
  File "/home/hacker/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/definition/base.py", line 523, in launch
    snippet_instance.update_textobjects(vim_helper.buf)
  File "/home/hacker/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/snippet_instance.py", line 102, in update_textobjects
    if obj._update(done, buf):
  File "/home/hacker/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/python_code.py", line 284, in _update
    exec(compiled_code, self._locals)  # pylint:disable=exec-used
  File "<exec-interpolation-code>", line 1, in <module>
NameError: name 'closing_par' is not defined

Executed snippet code:
  1 > closing_par(snip, 5)
```
just like @b3g00d 's issue, there seem to be a missing python helper function (actually 2 in my case), which causes the crash.

the _faulty_ snippets are the following: 
```
# method
snippet meth "func (self Type) Method(...) [error] { ... }"
func (${1:receiver} ${2:type}) ${3:name}(${4:params})${5/(.+)/ /}`!p opening_par(snip, 5)`$5`!p closing_par(snip, 5)` {
	${0:${VISUAL}}
}
endsnippet
```

and 

```
# function
snippet func "func Function(...) [error] { ... }"
func ${1:name}(${2:params})${3/(.+)/ /}`!p opening_par(snip, 3)`$3`!p closing_par(snip, 3)` {
	${0:${VISUAL}}
}
endsnippet
```
Now, the missing python helpers `opening_par` and `closing_par`  are also defined  at the bottom of the snippet source definition [vim-go/gosnippets/UltiSnips/go.snippets#L551](https://github.com/fatih/vim-go/blob/master/gosnippets/UltiSnips/go.snippets#L551)

```
global !p

{...}

def opening_par(snip, pos):
	if return_values(t[pos]) > 1 and not t[pos].startswith("("):
		snip.rv = "("
	else:
		snip.rv = ""
def closing_par(snip, pos):
	if return_values(t[pos]) > 1:
		snip.rv = ")"
	else:
		snip.rv = ""
endglobal
```
The thing is, as soon as  I move the  global python interpolation definition on  top of it's client snippets, everything works (which is the actual workaround that I use)  

@b3g00d  can you try to see if it kinda workaround for you as well ?

This behavior is weird because the snippet file, AFAIK, was not changed recently from upstream vim-go repository, and it has been working fine before.

@SirVer  do you think there could be any recent changes on UltiSnips or vim/python3 that might be the cause?

**Note:** I am using vim-go, UltiSnips (both via vim plug), vim 8.2/+python3 (3.10.2)

**Comment by jasonli108** [comment]
@b3g00d I tried the action you mentioned in your comments. So the issue was coming from the code snippet definition of if __name__ == `!p snip.rv = get_quoting_style(snip)`__main__`!p snip.rv = get_quoting_style(snip)`:
	${1:${VISUAL:main()}}
I replaced with if __name__ == "__main__": , saved, close all nvim and start a new to ensure the new python snippet file was read. This resolved the issue for me, thanks

**Comment by SirVer** [comment]
I can reproduce the issue with Vanilla Vim and latest master now, I believe I was testing with a wrong revision of UltiSnips before, my bad and sorry for that.

Bisecting indicates that the bug appeared in #1421. I revert this revision in #1435. Sorry for the problems!

**Comment by delvatt** [comment]
@SirVer  I can confirm  #1435 fixes the issue for me. Thank you very much!
