### ISSUE TITLE
Empty lines from snippet get replaced with tabs when expanded on tabbed line

### ISSUE THREAD

**Issue by SingularisArt** [SirVer/ultisnips#1475]
Here's an example environment snippet:

```vim
snippet enum "Enumerate Environment" bAi
\begin{enumerate}
	\label{enum:$1}

	\item ${VISUAL}$2
\end{enumerate}$0
endsnippet
```

But when I expand the snippet on a line that's tabbed in, the empty lines from the snippet are replaced with tabs. Here's an example file after expanding the snippet:

```tex
\begin{document}
  \begin{enumerate}
    \label{enum:}
  
    \item 
  \end{enumerate}
\end{document}
```

As you can see, there's a tab that's replacing the empty line.
How can I get rid of this and just keep the empty lines from the snippet empty without any spaces/tabs?

- **Operating System**: 5.15.53-1 Manjaro
- **Vim Version**: NVIM v0.8.0-dev
- **UltiSnips Version**: 
- **Python inside Vim**: python3.10

**Minimal Vimrc**:

```lua
vim.cmd([[
  " make YCM compatible with UltiSnips (using supertab)
  let g:ycm_key_list_select_completion = ['<C-j>', '<Down>']
  let g:ycm_key_list_previous_completion = ['<C-k>', '<Up>']
  let g:SuperTabDefaultCompletionType = '<C-n>'

  " better key bindings for UltiSnipsExpandTrigger
  let g:UltiSnipsExpandTrigger = "<Enter>"
  let g:UltiSnipsJumpForwardTrigger = "<C-j>"
  let g:UltiSnipsJumpBackwardTrigger = "<C-k>"

  " open the file in a new tab
  let g:UltiSnipsEditSplit='tabdo'

  " the location of the snippets
  let g:UltiSnipsSnippetDirectories=[$HOME."/.local/share/deathvim/dvim/UltiSnips", "UltiSnips"]
]])

require("packer").startup(function(use)
	use({ "wbthomason/packer.nvim" })
	use({ "SirVer/UltiSnips" })
end)
```
My latex snippets can be found [here](https://github.com/SingularisArt/snippets/blob/master/tex)

**Comment by SirVer** [comment]
This issue was closed due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).

**Comment by SingularisArt** [comment]
Sorry. I should've also mentioned that it was a problem with vim as well. Here's the minimal `.vimrc` needed:

```vim
call plug#begin()
  Plug 'SirVer/ultisnips'
  Plug 'lervag/vimtex'
call plug#end()

" make YCM compatible with UltiSnips (using supertab)
let g:ycm_key_list_select_completion = ['<C-j>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-k>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<Enter>"
let g:UltiSnipsJumpForwardTrigger = "<C-j>"
let g:UltiSnipsJumpBackwardTrigger = "<C-k>"

" open the file in a new tab
let g:UltiSnipsEditSplit='tabdo'

" the location of the snippets
let g:UltiSnipsSnippetDirectories=[$HOME."/.vim/UltiSnips", "UltiSnips"]
```

And here's what is inside of my `~/.vim/UltiSnips/tex.snippets`:

```vim
global !p
import vim

def text():
    return vim.eval('vimtex#syntax#in_mathzone()') == '0'
endglobal

context "text()"
snippet beg "begin{} / end{}" bAi
\begin{$1}[$2]
	\label{$3:${4:${2/\\\w+\{(.*?)\}|\\(.)|(\w+)|([^\w\\]+)/(?4:_:\L$1$2$3\E)/ga}}}

	${VISUAL}$5
\end{$1}$0
endsnippet
```

**Comment by SingularisArt** [comment]
[Answer](https://github.com/SirVer/ultisnips/issues/1476#issuecomment-1192065688).
