### ISSUE TITLE
Ungrab tab key in visual mode

### ISSUE THREAD

**Issue by avidseeker** [SirVer/ultisnips#1528]
**Expected behavior:**
Tab key can be remapped when not in a snippet.

**Actual behavior:**
Pressing tab erases selected text.

**Steps to reproduce**
```
cat >> ~/.config/nvim/init.vim
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv
```
Select some lines of text and press tab.

Nvim v0.8.3
Ultisnip: 0ad238 commit id

**Comment by SirVer** [comment]
This is desired behavior. Please see the docs for visual. Am 02.04.2023 um 10:30 schrieb avidseeker ***@***.***>:﻿

Expected behavior:
Tab key can be remapped when not in a snippet.
Actual behavior:
Pressing tab erases selected text.
Steps to reproduce
cat >> ~/.config/nvim/init.vim
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv

Select some lines of text and press tab.
Nvim v0.8.3
Ultisnip: 0ad238 commit id
