### ISSUE TITLE
Installing the newest version of `pynvim` makes Ultisnips laggy

### ISSUE THREAD

**Issue by jsr-p** [SirVer/ultisnips#1529]
Hi

Today I cloned the package [pynvim](https://github.com/neovim/pynvim) and installed the package directly instead from PyPi.

After reopening nvim I noticed that nvim was very laggy in all python files.
I found out that the issue was with `Ultisnips`.
Deleting the package and reinstalling it from PyPi made the lag go away.

The version of [pynvim](https://github.com/neovim/pynvim)  on PyPi is 4.3 and so I went through the git history to check where something significant changed.
I located the issue to be this PR https://github.com/neovim/pynvim/pull/506.
This PR changes a `num_to_str` function to include a [boolean check](https://github.com/neovim/pynvim/blob/41edb05b035c53bc396bf11fb2815ab03f65a2fc/pynvim/plugin/script_host.py#L197).
The helper function is used in the LegacyVim object's `eval` function [here](https://github.com/neovim/pynvim/blob/41edb05b035c53bc396bf11fb2815ab03f65a2fc/pynvim/plugin/script_host.py#L203).
Browsing through this [repo's](https://github.com/SirVer/ultisnips) source code reveals that `Ultisnips` uses `vim.eval` at many places.

I wonder what could be done to circument this issue?
Profiling different variations of the `num_to_str` function did not reveal any significant speed up :cowboy_hat_face: 
I have also made an issue at `pynvim`'s repo [here](https://github.com/neovim/pynvim/issues/523).

**Comment by SirVer** [comment]
@jsr-p That sucks... yet another new bug that only affects neovim. I am sorry, but I cannot support neovim currently. 

This issue was closed due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).
