### ISSUE TITLE
Constant errors when python is missing  (Can we enable discussions on github for this project?)

### ISSUE THREAD

**Issue by danielb2** [SirVer/ultisnips#1545]
I don't have a bug but would like to ask questions.

In my case, it seems I always get errors on new platforms or even plaforms where I do have python installed, and I'm finding this frustrating. This is the only plugin that makes it impossible to edit a file when python isn't existing. How to get around this?

Last was nvim works fine with this plugin, but as soon as I did a `crontab -e` to edit my crontab, suddenly python wasn't in the env, and I couldn't type anything because of all the errors from the  plugin

**Comment by SirVer** [comment]
I'd not like to have discussions on this on, because it is yet another thing that I need to monitor and drive. It is fine to asks questions here.

As for your problem: UltiSnips needs Python3, because it is 90% written in Python. Hence if you want to use it, you need that unfortunately. To work around the issue that it is annoying when you do not have it, you could use something like this in your vimrc.

~~~
if has('python3')
Plug 'SirVer/UltiSnips'
end
~~~
