### ISSUE TITLE
I can't make UltiSnips to set <tab> as jump forward trigger  

### ISSUE THREAD

**Issue by BODH1SATVA** [SirVer/ultisnips#1554]
I want to set `<tab>` for both to expand and jump forward but it seems like 
`vim.g.UltiSnipsExpandOrJumpTrigger = '<tab>'` does not work.
I thought that other maps could get in the way or it might be due to the conflict with other plugins, but I don't use `<tab>` in any other maps and I have tried deleting other plugins (left only VimTex and UltiSnips), It still would not work. Later I found that this does not work for any keys not just for `<tab>`.
`vim.g.UltiSnipsJumpBackwardTrigger = '<s-tab>'`   works fine though.

I use lazy.nvim as my plugin manager. I have tried updating UltiSnips but it says it's  up to date.

I have tried more direct way  and I changed my ultisnips.lua file inside my plugins folder to have
```
return {"SirVer/ultisnips", 

lazy = false, 
config = function()
vim.api.nvim_set_keymap('i', '<tab>', '<C-R>=UltiSnips#ExpandSnippetOrJump()<CR>', {noremap = true, silent = true})
end

}
```
This works with other keys  ( `<c-k>` for example )  but not with `<tab>` (also this does not remove default mappings obviously).  When I try to set `<tab>` this way and use command `:imap<tab>` it gives me  `<C-R>=UltiSnips#ExpandSnippet()<CR>`  instead of `<C-R>=UltiSnips#ExpandSnippetOrJump()<CR>` . 

-----

- **Operating System**:   Pop!_OS 22.04 LTS
- **Vim Version**: 
           NVIM v0.10.0-dev-3020+g435dee74b
           Build type: RelWithDebI
- **Python inside Vim**:   3.10.12

**Comment by AshyAspen** [comment]
I'm not sure about the specifics of your case, but I just thought I'd share that I was having a similar problem recently because I was trying to define the remap in a config file set in a snips.lua file in the "after" folder specifically for UltiSnips, like I do for most config stuff. I found that the <tab> was working for expanding but not jumping and wasn't sure why.

I ended up putting 
```vim.cmd([[                    
let g:UltiSnipsExpandTrigger = '<tab>'                              
let g:UltiSnipsJumpForwardTrigger = '<tab>'                                          
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'                                                 
]])```
in my init.lua and everything works fine now like I was trying to get it.

Perhaps doing separate commands for forward and expand would work? Or moving it to a piece of your config that initializes sooner, if you're having a problem I was having? I'm not exactly sure but I thought I'd share. Sorry I can't help more.

**Comment by BODH1SATVA** [comment]
I have figured these out. I changed my ultisnips.lua file to have

```
return {"SirVer/ultisnips", 
lazy = false, 
init = function()
vim.g.UltiSnipsExpandOrJumpTrigger = '<tab>'
vim.g.UltiSnipsJumpBackwardTrigger = '<s-tab>'
end
}
```
Everithing works as it should now.

**Comment by SirVer** [comment]
Glad you made it work. I do not use Neovim and it is officially not supported by UltiSnips, hence i could not have helped in either case.
