### ISSUE TITLE
"Error detected while processing TextChangedI Autocommands for *..function UltiSnips#TrackChange" - macOS update broke UltiSnips

### ISSUE THREAD

**Issue by nickeltingupta** [SirVer/ultisnips#1560]
**Expected behavior:**
UltiSnips works

**Actual behavior:**
UltiSnips doesn't work. 

In MacVim I get an error like the following whenever I open a tex file in MacVim.

`
Error detected while processing BufRead Autocommands for "*. tex"
•function dist#ft#FTtex[47]. .FileType Autoco
mmands for "tex".. function <SNR>3_1od_ft[4].. <SNR>3_doautocmd[2]..FileType Autocommands for "*".. function <SN
R>11_LoadFTPlugin[171. script /Users/nitin/.vim/plugged/vimtex/ftplugin/tex.vim:
Error: VimTeX does not support your version of Vim
`

This displays for a split second and disappears. I'm using the latest Vim 9.1 so I disabled checking for the version of Vim using `let g:vimtex_version_check = 0`. Now, when I try to write anything in the tex file I get the following errors.

`
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
E370: Could not load library /opt/homebrew/Frameworks/Python.framework/Versions/3.9/Python
`

In case the issue is with MacVim, I open vi using terminal and get the following errors when I type any character.
`
Error detected while processing TextChangedI Autocommands for "*"..function Ulti
Snips#TrackChange:
<global-snippets>:3: SyntaxWarning: invalid escape sequence '\<'
`

**Steps to reproduce**
macOS 15.1+MacVim+UltiSnips (all latest stable versions) : then open any tex file

**.vimrc**
`
call plug#begin()
Plug 'SirVer/ultisnips'
let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<tab>'
let g:UltiSnipsJumpBackwardTrigger='<s-tab>'
let g:UltiSnipsEditSplit='tabdo'
let g:vimtex_version_check = 0
let g:UltiSnipsSnippetDirectories=['/Users/nitin/.vim/plugged/mysnippets/']
Plug 'honza/vim-snippets'
Plug 'arcticicestudio/nord-vim'
Plug 'KeitaNakamura/tex-conceal.vim', {'for': 'tex'}
Plug 'lervag/vimtex', {'for': ['tex']}
let g:tex_flavor='latex'
let g:vimtex_view_method='skim'
let g:vimtex_view_skim_activate = 1
let g:vimtex_view_skim_sync = 1
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'
let g:vimtex_compiler_latexmk = { 
        \ 'build_dir' : 'build',
	\ 'executable' : 'latexmk',
        \ 'options' : [ 
	\   '-shell-escape',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-interaction=nonstopmode',
        \ ],
        \}
call plug#end()
colorscheme nord
setlocal spell 
set spelllang=en_us
inoremap <C-l> <c-g>u<Esc>[s1z=]a<c-g>u
"Set the window-size
set fullscreen
"Set the guifont
:set guifont=Monaco:h21
"filetype indent off
"set noautoindent
"set nosmartindent
`

**Comment by SirVer** [comment]
Disable ultisnips when you have no python3 support in Vim installed. Search the issues, this was discussed prior. The other issues are not on ultisnips. Am 30.10.2024 um 11:55 schrieb nickeltingupta ***@***.***>:﻿
Expected behavior:
UltiSnips works
Actual behavior:
UltiSnips doesn't work.
In MacVim I get an error like the following whenever I open a tex file in MacVim.
`
Error detected while processing BufRead Autocommands for ". tex"
•function dist#ft#FTtex[47]. .FileType Autoco
mmands for "tex".. function 3_1od_ft[4].. 3_doautocmd[2]..FileType Autocommands for "".. function 11_LoadFTPlugin[171. script /Users/nitin/.vim/plugged/vimtex/ftplugin/tex.vim:
Error: VimTeX does not support your version of Vim
This displays for a split second and disappears. I'm using the latest Vim 9.1 so I disabled checking for the version of Vim usinglet g:vimtex_version_check = 0. Now, when I try to write anything in the tex file I get the following errors. 
Error detected while processing InsertCharPre Autocommands for ""..function UltiSnips#TrackChange:
line    1:
E370: Could not load library /opt/homebrew/Frameworks/Python.framework/Versions/3.9/Python
In case the issue is with MacVim, I open vi using terminal and get the following errors when I type any character.
Error detected while processing TextChangedI Autocommands for ""..function Ulti
Snips#TrackChange:
line    1:
:3: SyntaxWarning: invalid escape sequence '<'
`
Steps to reproduce
macOS 15.1+MacVim+UltiSnips (all latest stable versions) : then open any tex file
.vimrc
`
call plug#begin()
Plug 'SirVer/ultisnips'
let g:UltiSnipsExpandTrigger=''
let g:UltiSnipsJumpForwardTrigger=''
let g:UltiSnipsJumpBackwardTrigger=''
let g:UltiSnipsEditSplit='tabdo'
let g:vimtex_version_check = 0
let g:UltiSnipsSnippetDirectories=['/Users/nitin/.vim/plugged/mysnippets/']
Plug 'honza/vim-snippets'
Plug 'arcticicestudio/nord-vim'
Plug 'KeitaNakamura/tex-conceal.vim', {'for': 'tex'}
Plug 'lervag/vimtex', {'for': ['tex']}
let g:tex_flavor='latex'
let g:vimtex_view_method='skim'
let g:vimtex_view_skim_activate = 1
let g:vimtex_view_skim_sync = 1
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'
let g:vimtex_compiler_latexmk = {
\ 'build_dir' : 'build',
\ 'executable' : 'latexmk',
\ 'options' : [
\   '-shell-escape',
\   '-file-line-error',
\   '-synctex=1',
\   '-interaction=nonstopmode',
\ ],
}
call plug#end()
colorscheme nord
setlocal spell
set spelllang=en_us
inoremap  u[s1z=`]au
"Set the window-size
set fullscreen
"Set the guifont
:set guifont=Monaco:h21
"filetype indent off
"set noautoindent
"set nosmartindent
`

**Comment by nickeltingupta** [comment]
> Disable ultisnips when you have no python3 support in Vim installed. Search the issues, this was discussed prior. The other issues are not on ultisnips. Am 30.10.2024 um 11:55 schrieb nickeltingupta ***@***.***>

I'm going to describe how things were resolved for future reference. ChatGPT came in handy.

I found [https://stackoverflow.com/questions/69914503/installing-vim-with-python3-support](https://stackoverflow.com/questions/69914503/installing-vim-with-python3-support). When I run `mvim --version | grep python` or `vim --version | grep python`, I get `-python` and `+python3`.

However, I had a cask of MacVim installed which could not see python3 and I had two installations of python3. To fix this, I removed both the regular and cask MacVim, reinstalled cask MacVim, and explicitly pointed MacVim to the correct python3 path (obtained by `which python3`) using `let g:python3_host_prog = '/output/of/which python3'`. This fixed the python3 recognition issue.

As for other problems, others may find [this resolved issue](https://github.com/SirVer/ultisnips/issues/1557) helpful. My problem was coming through a indent fixing snippet I obtained from elsewhere. The `\<` was not being recognized after the recent updates I made to my system. Changing `\<` ---> `\\<` fixed everything.
`
global !p
def fix_indent(snip):
    vim.eval('feedkeys("\<c-f>")') 
endglobal
`

This issue is resolved.
