### ISSUE TITLE
Is it possible to replace the text in tabstop?

### ISSUE THREAD

**Issue by SirVer** [SirVer/ultisnips#187]
using the `complete()` function from the screencast as an example. 

def complete(t, opts):
    if t:
        opts = [m[len(t):] for m in opts if m.startswith(t)]
    if len(opts) == 1:
        return opts[0]
    return '|'.join(opts[:7])

What if the opts are all similar and start with same letters? for example, ['this_is_a', 'this_not_b']. This can be filtered using fuzzy match. But how can it return the result and simply replace the text in tabstop like `t[1] = opts[0]`?

Launchpad Details: [#LP1182251](https://bugs.launchpad.net/bugs/1182251) Zhao Cai - 2013-05-21 00:33:13 +0200

**Comment by zed0** [comment]
It's not quite what is asked for in the original post, but I found that the following snippet works well for my header guard:
```
snippet guard "Header guard"     
#ifndef ${1/(\w)?(\W)?/(?1:\u$1)(?2:_)/g}     
#define ${1/(\w)?(\W)?/(?1:\u$1)(?2:_)/g}                    
    
${0:$1}     
    
#endif // ${1/(\w)?(\W)?/(?1:\u$1)(?2:_)/g}                     
endsnippet                                           
```
The important part being the `${0:$1}` which leaves you with the unwanted text selected so you can just keep typing.

**Comment by SirVer** [comment]
I never quite understood what you wanted, but I am glad you found something that works :)

**Comment by idbrii** [comment]
I came across this issue while trying to figure out how to replace text in a tabstop. This issue is closed and unresolved, but the answer is actually yes.

Here's three examples of replacing the text in a tabstop.

```snippets
snippet ex1 "Forced upper case text" b
$1`!p
def toupper(i):
	if t[i]:
		t[i] = t[i].upper()
toupper(1)
`
endsnippet

snippet ex2 "Consonants only" b
$1`!p
def strip_vowel(i):
	if t[i]:
		t[i] = ''.join([a for a in t[i] if a not in "aeiou"])
strip_vowel(1)
`
endsnippet

snippet ex3 "Autocomplete" b
$1`!p
def complete_tabstop(i, opts):
    if t[i]:
        opts = [m for m in opts if m.startswith(t[i])]

    if len(opts) == 1:
        t[i] = opts[0]
		snip.rv = ''
    elif len(opts) > 0:
		opts = [m[len(t[i]):] for m in opts]
		snip.rv = "({0})".format("|".join(opts))
	else:
		snip.rv = ''

DIRECTIVES = ['commit', 'status', 'start', 'diff']
complete_tabstop(1, DIRECTIVES)
`

Further uses are also updated: This is a $1
endsnippet
```

The last example is a direct answer to the original question. It's based on the [complete function](https://github.com/honza/vim-snippets/blob/b62dfce8449d8a8196720ddd3cfecbca8bb7fe45/pythonx/vimsnippets.py#L5-L25) from vim-snippets that is similar to the original question. As far as I can tell, the vim-snippets version doesn't modify the tabstop text. Instead, it adds the remaining text after the tabstop.

My solution is not very usable because it applies immediately when a match is found which is surprising to the user. An improvement would work more like vim-snippet's version but then modify the tabstop when switching to the next tabstop. I haven't figured that out yet, but that's a separate issue.
