### ISSUE TITLE
Per project snippet files

### ISSUE THREAD

**Issue by simendsjo** [SirVer/ultisnips#222]
Different projects use different coding conventions even if they are using the same language. What is the best way to enable this in ultisnips?

**Comment by mMontu** [comment]
I know this issue is closed for quite some time, but I think it is still relevant.

    1) there are tools that do this job for you and better (clang-format, gofmt and so on).

"One size doesn't fit all" -- not everyone is able to use the newest or the better tool. Some people work in legacy projects where it is not easy to use such tools. On some projects there is also the requirement that you just add to a given source file -- running such kind of tool would change code that is supposed to be untouched.

    2) there are too many different styles people love (just an example in c: where to put {}, put *& close to the type or close to the variable, align the equals in aaaa = bb,\ncccccc = dd or not, indent namespaces or class members or not? 

I agree that there are too many different styles and it would be complicated to support all of them. I understand that it is possible to write custom snippets solve this, but you probably agree that the python interpolation above is quite verbose, which makes the snippet harder to read.

This solution also requires that all the original snippets to be duplicated, even if they are otherwise perfect.

Despite there are so many aspects for different styles, some of them are more clearly noticed, and usually required to be followed on some companies. For instance, from the C examples above, I believe that most people will pay attention only to the braces position.

Maybe for the main cases we could have some identifiers that expands to a python interpolation, and use these identifiers on the predefined snippets. The identifiers could be unique for the plugin, and defined at the start of the default snippets for that language. (my knowledge in python is quite limited - maybe this is already possible without changing the plugin)

**Comment by SirVer** [comment]
I suggest looking at https://github.com/honza/vim-snippets/blob/master/UltiSnips/python.snippets#L34 - it does something along those lines for documentation markers in comments. A very similar approach can be used to add various C indentation styles to the snippets.

**Comment by mMontu** [comment]
Thank you @SirVer, I will try this approach. At first I will limit on opening/closing braces.

**Comment by raine** [comment]
I have some JS projects that use an extra space in a function expression and some that don't.

```
function[ ]?() {}
```

Here's my solution:

```
global !p
def s():
    snip.rv = " " if snip.opt('g:javascript_function_style') == "space" else ""
endglobal

snippet f "function()" w
function`!p s()`(${1:}) {${2:}}
endsnippet
```

```viml
" project's .vimrc
let g:javascript_function_style = "space"
```

It's not optimal but nicer than duplicating snippets.
