### ISSUE TITLE
Recursion while expanding

### ISSUE THREAD

**Issue by ivan-cukic** [SirVer/ultisnips#305]
Hi,

A related issue to #168, but with a twist, otherwise I'd post there.

This snippet has more than a few issues:
snippet '[' "Lambda" r
[${1:&}](${2}) {
    ${0}
}
endsnippet

For [<tab><tab><tab><tab> it just expands the snippet and expands and expands.

The same snippet, but with 'l' instead of '[' works without problems.

Tested on debian gnu/linux jessie, vim 7.4, using YCM, and <tab> <s-tab> to move between tabstops.

**Comment by marcmo** [comment]
@SirVer coming from other snippet plugins this can be annoying
from the documentation:

    The g:UltiSnipsExpandTrigger and g:UltiSnipsJumpForwardTrigger can be set to
    the same value. To simulate TextMate behavior, add the following lines to your
    vimrc file. >
      let g:UltiSnipsExpandTrigger="<tab>"
      let g:UltiSnipsJumpForwardTrigger="<tab>"
      let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

if this mapping is a "bug" I'd consider removing this from the documentation.
is it possible to disable the recursive nature of ultisnips?

**Comment by SirVer** [comment]
@marcmo, I can only repeat what I said before: The real bug is that you overload your tab trigger for two distinct uses - jump and expand. This is not a 'bug' in the software, it is a 'bug' in expectation - you ask the software to guess what you want in cases where both possibilities are valid - and sometimes it guesses wrong.

You can always design your snippet triggers in a way that there is no ambiguity - but usually it is just better to use two different key maps for two different functionalities. There is no toggle to disable the recursiveness of UltiSnips.

**Comment by marcmo** [comment]
@SirVer I think it's OK the way it is. thanks for the plugin, I really enjoy it!
I guess I was just misled by the example you have in your docs where you suggest this overload for tab for the 2 distinct use-cases.

**Comment by SirVer** [comment]
I removed this part of the documentation now - while the feature works as expected (at least what I'd expect) and has exactly the same issues as TextMate had too I think it leads to too much confusion. Let's reduce it's discoverability a bit and see what happens.
