### ISSUE TITLE
Custom number of placeholders based on line content?

### ISSUE THREAD

**Issue by anvaka** [SirVer/ultisnips#424]
Hello,

I've spent last couple hours reading documentation and learning examples, but yet I cannot come up with an answer. How can I have different number of placeholders based on content of the line?

I have a simple snippet:

```
snippet re "commonjs require"
var ${1} = require('${2}');
endsnippet
```
If I type

``` javascript
re<tab>x<tab>hello
```

I will get `var x = require('hello');` this is perfect. Now I want to add a condition: If current line already contains equal sign `=`, I want to type `re<tab>hello` and get only `require('hello');` expanded.

How can I achieve this?

**Comment by SirVer** [comment]
Snippets only can have a fixed number of tabstops right now, see https://github.com/SirVer/ultisnips/issues/235.  For now, you have to use two snippets:

~~~
snippet re "commonjs require" b
var ${1} = require('${2}');
endsnippet

snippet "^([^=]*)= re" "commonjs require" r
`!p snip.rv = match.group(1)`= require('${1}');
endsnippet
~~~

The first one is the one you wrote. The second uses a regular expression trigger.

Another approach would be to use one snippet with the 'b' option and one without, but you need to adjust the priorities correctly, so that always the correct one matches, see https://github.com/SirVer/ultisnips/issues/400#issuecomment-63939849.

**Comment by anvaka** [comment]
Thank you Holger. Two snippets did the trick.
