### ISSUE TITLE
Custom auto-complete with UltiSnips in vim

### ISSUE THREAD

**Issue by byakugan** [SirVer/ultisnips#428]
I would like to create snippets that do a custom completion at each tab stop using Vim's complete() function. Here's a simple example of what i want to achieve.

```vim
snippet date "Date snippet"
   day of month: ${1:`!v complete(col('.'), [1, 2, 3, 4])`}
   month: ${2:`!v complete(col('.'), ['Jan', 'Feb', 'March'])`}
   year: ${3:`!v complete(col('.'), ['2012', '2013', '2014', '2015'])`}
endsnippet
```
At the first tab stop i want to see Vim's auto-complete menu with [1, 2, 3, 4] items. Similarly for other tab stops. But, when i actually run this snippet I get the following output
```
day of month: Jan0an0
month: 201200120
year:100
```
There might be other ways to achieve auto-complete as shown in screen cast Episode 4: Python Interpolation. But, I would love to see Vim's auto-complete inside UltiSnips.

Please anyone suggest on how to achieve this. I posted in statckoverflow but i did not receive any response for this http://stackoverflow.com/questions/27962109/custom-auto-complete-with-ultisnips-in-vim

**Comment by SirVer** [comment]
Sorry, can't happen. The problem is that Vim is not open for extension in the way UltiSnips needs it - so UltiSnips is quite the hack (for example at each key movement we take a partial diff of the buffer before and after the movement to guess the edit action, since Vim does not provide it to us). That also means that it is not stable against any sort of interruption - like running other vim script during evaluation. This is precisely what you want to do here. 

I wish I had better news, but before neovim - which solves all of these issues - this cannot happen unfortunately :(.

**Comment by byakugan** [comment]
Thanks for the quick reply.
