### ISSUE TITLE
Error when undo-ing after an Expand tab

### ISSUE THREAD

**Issue by etiennebatise** [SirVer/ultisnips#438]
Hello, 

I'm new to issue reporting and not native english speaker so sorry for the poor "intervention"

I've just installed Ultinsnips on my gvim editor (version 7.3.443). I have python2 activate and python2 correctly installed on my computer. I've also installed the vim-snippet package as explained in the readme file.

I've put this line in my vimrc :
```
let g:UltiSnipsUsePythonVersion = 2
let g:UltiSnips#ExpandSnippet = 1
```

To trigger the error, I just open vim, I enter : `:set ft=tex` and the I just insert "sec<TAB>" to trigger the snippet. Then I meet my first error : 
```
Error detected treating UltiSnips#ExpandSnippet:
line1
Please install unicode python package in order to be able to make ascii conversions.
```
I really don't understand what I have to install in the third line.

So I forget that, I go on and play with the snippets. When in the snippet, when I undo, a window pop up up displaying this error

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/etienne/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 56, in wrapper
    return func(self, *args, **kwds)
  File "/home/etienne/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 330, in _cursor_moved
    self._csnippets[0].update_textobjects()
  File "/home/etienne/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 77, in update_textobjects
    if obj._update(done):
  File "/home/etienne/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_mirror.py", line 20, in _update
    self.overwrite('')
  File "/home/etienne/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 128, in overwrite
    if self.current_text == gtext:
  File "/home/etienne/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 101, in current_text
    return _vim.buf[self._start.line][self._start.col:self._end.col]
  File "/home/etienne/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 23, in __getitem__
    rv = vim.current.buffer[idx]
IndexError: numéro de ligne hors limites
```

**Comment by SirVer** [comment]
For the first issue you need to `pip install unidecode` for the latex snippets you are using. See
https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L1163

The second issue is not fixable - UltiSnips cannot deal with undo. Due to the limitations of Vim it needs to keep guessing user edits. And undos are very hard to impossible to guess - especially since vim does not emit all autocommands for undos. This might be fixable in the move to neovim which is nicer to plugins. Maybe.

**Comment by etiennebatise** [comment]
Thanks for the tip, the pip install worked.

Regarding of the second error, well, I'll try to know what I'm doing ;)

Thank you for the quick answer, and the awesome plugin!

**Comment by Aster89** [comment]
I get the same error (the first one), but there's something irregular in the behavior, since I get it with `sec<F8>` and `sub<F8>`, but not for `subs<F8>`, for example. I already did `pip install unicode`.

**Comment by iasj** [comment]
@Aster89 . It is `pip install unidecode` instead.

**Comment by Aster89** [comment]
Oh, s***, I missed that "de"! I'll try and make you know in some hour.

**Comment by Aster89** [comment]
I still have the same error triggered. (BTW `grep`ing the text of the error I understand know why I get the alert just once.)
The version 8.1.1 of `pip` was installed at first, but I was prompted to install the newer version with `pip install --upgrade pip`, so I did it, obtaining the version 9.0.1 to be successfully installed. Hope the problem is not related to this upgrade.

**Comment by L4in** [comment]
@Aster89, I ran into the same problem 10 minutes ago I was setting a new vim install on a new computer.
Installing `python-unidecode` didn't led to a change, however `python3-unidecode` did the trick for me.

If you still have your issue, I would suggest running a `pip3 install unidecode` and see if the problem persists.
