### ISSUE TITLE
Recursively search Ultisnips directory

### ISSUE THREAD

**Issue by pelonpelon** [SirVer/ultisnips#442]
I am developing a collection of snippets in a github repository for the obvious reasons, and also so that they can be easily shared.

Would it be possible for ultisnips to find .snippet files in subdirectories? Then you could  `git clone repository` within the Ultisnips directory, much like we do in the bundles directory. It would also allow for `git submodule add` so that snippets could be kept up to date in one command.

UltisnipsEdit would have to behave differently as well.

**Comment by SirVer** [comment]
This request is kind of the opposite of https://github.com/SirVer/ultisnips/pull/409. 

By default UltiSnips finds snippets in each runtimepath. So if a plugin adds a 'UltiSnips/' directory and somebody `Plugin`s this, she will have all the snippets in this plugin as well. I think that is all that is needed.

Could you elaborate about your specific use case for this feature, i.e. which snippets would you like to have and don't right now?

**Comment by pelonpelon** [comment]
Thanks for responding.

I'm not writing a plugin in this case. I was hoping, under the already established default directory
`~/.vim/Ultisnips/` I could clone a simple git repo just like I can do under the `~/.vim/bundle` directory. Not a plugin, but a git repo that might contain only one snippet file. Or possibly a collection of related snippet files.

I'm authoring snippets that I would like to share via git cloning. I'm writing them for a framework called mithril that is in alpha stage and constantly changing. Thus, for users to keep up to date, so that the snippets stay current with the latest mithril release, all a user must do is `git pull` in a directory `~/.vim/Ultisnips/mithril/`
for example.

The request is that when the `~/.vim/Ultisnips/ directory is searched, that search could be recursive in order to find a snippet file inside a cloned git repo. Or an option be available to allow recursive search in a particular directory.

If such an option were available, a user who has collected various snippet files over time, could update all those snippets from their github sources with one command. And authors could update their snippets on github and be assured that the users would have the latest updates.

Thank you

**Comment by SirVer** [comment]
But that is possible. `~/.vim/Ultisnips/mithril/*.snippets` is already searched for snippets. 

This is not recursive, UltiSnips just follows the search order of ftplugin: https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L511

Though personally I would suggest you make a vim plugin - even if it just contains `Ultisnips/` for now, eventually you want to add `ftdetect/` rules and maybe even some `ftplugin/` rules for your framework. And for users it will just be another plugin to bundle, instead of something special that does not work with plugin managers. 

Closing this, should work as you want to.
