### ISSUE TITLE
Vim with two dynamic python

### ISSUE THREAD

**Issue by s-y** [SirVer/ultisnips#469]
When I active pyenv venv with python3 I got this error.
Also I use this plugin https://github.com/lambdalisue/vim-pyenv

```
'forum-py3' is activated.
Виявлено помилку під час виконання function UltiSnips#bootstrap#Bootstrap:
рядок   35:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ihor/.vim/bundle/ultisnips/pythonx/UltiSnips/__init__.py", line 8, in <module>
    from UltiSnips.snippet_manager import SnippetManager
  File "/home/ihor/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 16, in <module>
    from UltiSnips.snippet.definition import UltiSnipsSnippetDefinition
  File "/home/ihor/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/__init__.py", line 3, in <module>
    from UltiSnips.snippet.definition.ultisnips import UltiSnipsSnippetDefinition
  File "/home/ihor/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/ultisnips.py", line 6, in <module>
    from UltiSnips.snippet.definition._base import SnippetDefinition
  File "/home/ihor/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 12, in <module>
    from UltiSnips.text_objects import SnippetInstance
  File "/home/ihor/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/__init__.py", line 9, in <module>
    from UltiSnips.text_objects._shell_code import ShellCode
  File "/home/ihor/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_shell_code.py", line 10, in <module>
    import tempfile
  File "/home/ihor/.pyenv/versions/3.4.2/lib/python3.4/tempfile.py", line 36, in <module>
    from random import Random as _Random
  File "/home/ihor/.pyenv/versions/3.4.2/lib/python3.4/random.py", line 144
    raise TypeError from e
                       ^
SyntaxError: invalid syntax
```

**Comment by SirVer** [comment]
That seems like python2 is used for UltiSnips though python3 modules are on the pythonpath. Not sure if that is an ultisnips issue or something in your setup. 

UltiSnips should default to python3 if it is available inside Vim, so I am not sure why python2 is used here. You can try to force the python version to be 3 though, see [the documentation](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L107).

**Comment by SirVer** [comment]
Closing because my reply should offer a workable solution.

**Comment by oblitum** [comment]
Ok, I've checked the tip by @SirVer and this is happening because of this:

```
:h has-python

You can test what Python version is available with: >
	if has('python')
	  echo 'there is Python 2.x'
  	elseif has('python3')
	  echo 'there is Python 3.x'
	endif

Note however, that when Python 2 and 3 are both available and loaded
dynamically, these has() calls will try to load them.  If only one can be
loaded at a time, just checking if Python 2 or 3 are available will prevent
the other one from being available. 
```

Even though it's seems quite OK to have Vim compiled with both python 2 and python 3, relying on this `has('python')` vs `has('python3')` check seems not very useful =/. So UltiSnip is loading with python 2 even though both is supported by vim and the current one loaded is python 3.

**Comment by oblitum** [comment]
Also, setting `let g:UltiSnipsUsePythonVersion = 3` doesn't work because of the check that returns `0` making UltiSnip report python 3 is unavailable (even though it would work if the check didn't exist).

**Comment by SirVer** [comment]
@oblitum I am confused - are you seeing a bug in ultisnips or in Vim? 

having both python versions available will likely be trouble since it isn't tested - no other platform supports that in the first place.

**Comment by oblitum** [comment]
@SirVer I'm not sure about Vim stated behavior, it says that if `has('python')` gets executed, then python 2 gets activated and I won't be able to access python 3, hence returning ` has('python3') == 0`. In truth, it doesn't seem so though.

With vim-pyenv I'm indeed able to load any python environment, including my python 3 one, jedi python 3 completion is working fine, but because UltiSnip is checking and trusting `has('python3')` it then tries to execute python 2 while python 3 is what active in truth.

If you check vim-pyenv, it tells about a way of setting jedi python when activating an environment with  call `jedi#force_py_version(major_version)` and it does the job, UltiSnip doesn't provide such option, the only route for setting python version for it goes through the broken checks.

So maybe Vim checks are broken and you could just ignore them or providing an option for that.

**Comment by SirVer** [comment]
> So maybe Vim checks are broken and you could just ignore them or providing an option for that.

I thought we did.... https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L114 

But you say that is not properly working. Since I have no access to a machine with two dynamic pythons, I cannot test a fix. It seems you are in a unique position to write and test a fix - could you conjecture a pull request?

**Comment by oblitum** [comment]
As I said, even after setting `let g:UltiSnipsUsePythonVersion = 3`, UltiSnips will still go through the `has('python3')` check, and not blindly assume python 3 is available.

I've compiled two Vim's with two dynamic pythons, the last one on Arch, with a more recent snapshot, doesn't have this problem, `has('python')` and `has('python3')` are both working as expected and returning `1` for both, so UltiSnip doesn't break because of the check, but in the last Ubuntu I've tried `has('python3')` was returning `0` for no reason. Before I conjecture a pull request I'll update Vim on that machine (when I get the time) and check whether this behavior have changed recently or whether it was a Vim-on-Ubuntu behavior.

**Comment by Shougo** [comment]
It is debian's distribution python problem.
`:help python2-and-3`

**Comment by oblitum** [comment]
wow, thanks @Shougo for pointing that. And that section was just above the `has('python')` section I've mentioned =)

Not sure whether this vim compilation with py2 and py3 will survive enough, as of now it seems stable.

**Comment by Shougo** [comment]
neovim can survive python2 and python3.
But Vim in debian based distributions cannot.

**Comment by oblitum** [comment]
Hence I didn't get the issue on Arch.
