### ISSUE TITLE
Nested Anon Snippet Expansion

### ISSUE THREAD

**Issue by markwoodhall** [SirVer/ultisnips#489]
Hi, 

Firstly, thanks for creating and maintaining this awesome plugin. :)

I'm currently doing some work to integrate UltiSnip with [OmniSharp-Vim](https://github.com/OmniSharp/omnisharp-vim) so that is expands anonymous snippets on the fly to enable quick completion, like this. 

![Example](https://camo.githubusercontent.com/5ae770969058c59df21784ed734cead1f5a4ebda/687474703a2f2f692e696d6775722e636f6d2f35376934364c412e676966)

In the above example when Vim fires a "CompleteDone" event the completion gets converted to an anonymous snippet and expanded on the fly. 

This all works fantastically so far but I've stumbled across one issue and I'm not sure if its something I'm doing or something that is not supported by UltiSnips. I expect it could be me. 

In the example below after completing the second anonymous snippet expansion I am unable to jump to the next placeholder of the first anonymous snippet. 

![Example](http://i.imgur.com/pjDcQg2.gif)

Should this functionality be supported?

**Comment by SirVer** [comment]
That seems a really awesome implementation you have there. 

Yes, that should be supported - unfortunately I have seen this bug before. I assume it is some difference in how Vim processes key presses when snippets are launched from vim-script compared to insert mode. So far I did not investigate this very deeply since there was little need for it. I assume that it is also difficult to track down due this touches on awful Vim internals...

Can you provide a simple failing test case?

**Comment by markwoodhall** [comment]
Thanks for taking the time to reply. I've actually almost managed to get this working. It appears the way Anon snippets are treated is a bit different? 

I've changed the Vim Script to UltiSnips#AddSnippetWithPriority and UltiSnips#ExpandSnippet while still building the snippet on the fly from the completion. 

![nested](https://cloud.githubusercontent.com/assets/893173/7431169/c8103fa8-f013-11e4-91b5-d2797f1d1ca7.gif)

I only have one small problem left, expanding the second snippet does not look like it adjusts the tab stops on the first snippet. So tab stops for the third parameter are hidden and for the 4th parameter they are partially hidden.

**Comment by SirVer** [comment]
> It appears the way Anon snippets are treated is a bit different?

not sure what you are referring to. They should not be handled in any other way by UltiSnips - but I think they are implicitly due to when Vim empties it's `feedkeys` buffer. 

> I only have one small problem left, expanding the second snippet does not look like it adjusts the tab stops on the first snippet.

They usually do - there are a bunch of tests that check exactly the behavior you see. Can you reproduce the behavior when you manually define the same snippets that you expand there?

**Comment by markwoodhall** [comment]
It looks like it works fine if I manually expand the generated snippets. It only appears to be an issue during the automated completion process. I'll check it out. Thanks for the help.

**Comment by markwoodhall** [comment]
Thanks for the help. Its working now. Looks like I had to notify of CursorMoved. 

After generating the snippets on the fly, the last step in the `CompleteDone` event looks like so:

```
    call UltiSnips#CursorMoved()
    call UltiSnips#ExpandSnippetOrJump()
```
![nested](https://cloud.githubusercontent.com/assets/893173/7437721/0d5aa542-f052-11e4-9d12-794dee98e411.gif)

**Comment by SirVer** [comment]
Awesome! Thanks for keeping me in the loop.
