### ISSUE TITLE
Vim freezes when cmdwin is opened and multi-step snippet isn't complete

### ISSUE THREAD

**Issue by mwcz** [SirVer/ultisnips#510]
I've been experiencing a pretty random freeze for the last few months and I think I've finally tracked it down and found a reproducer.

The background info is that I use cmdwin (`:help cmdwin`) instead of the standard `:` command line.  There appears to be a conflict between UltiSnips and cmdwin.

Here's a minimal reproducer I found.  The only plugins installed are UltiSnips, vim-snippets, and pathogen. 

**.vimrc**

    let g:UltiSnipsSnippetDirectories=["UltiSnips", "./UltiSnip"]
    
    call pathogen#infect()
    call pathogen#helptags()
    
    set nocompatible
    
    " remap : to open cmdwin instead of regular command-line
    nnoremap : :<C-F>
    xnoremap : :<C-F>
    nnoremap / /<C-F>
    xnoremap / /<C-F>
    nnoremap ? ?<C-F>
    xnoremap ? ?<C-F>

Reproduction steps:

  1. `vim foo.html`
  2. Go into insert mode, then `html5<Tab>`
  3. `<Esc>` to leave insert mode, with the multi-step 'html5' snippet unfinished
  4. Then press `:` to open cmdwin (`q:` or `:<C-F>` can be used manually as well, if you don't have the nnoremaps in your vimrc)

The result is that vim freezes and I can't enter any commands into the cmdwin.  If, before step 3, I complete each step of the snippet, cmdwin does not freeze.

With this minimal setup, the freeze lasts about 1 second.  With my normal vimrc and plugins (about 30), it usually 20 seconds or more to unfreeze.  I have no idea why the extra plugins impacts the freeze time.

My first guess is that this is related somehow to `ttimeout` or `timeoutlen`, but changing those values doesn't appear to have any impact on the behavior.

When I uninstall UltiSnips, the freeze problem goes away, but I LOVE and NEED UltiSnips. <3

Has anyone else run into this or similar problems?

**Comment by SirVer** [comment]
The problem is that no autocommand is triggered when leaving the window to enter commandwin. UltiSnips therefore sees it as if you deleted everything in your original window, then typed everything that is in your commandwin - instead of exiting the snippet like it should. 

I just read in the documentation that Vim is not sending a BufLeave autocommand when entering the CmdWin (thanks for being so consistent Vim :/). We need to account for that:

Could you try the following:

After this line [here](https://github.com/SirVer/ultisnips/blob/master/plugin/UltiSnips.vim#L64), insert:

    au CmdwinEnter * call UltiSnips#LeavingBuffer()
    au CmdwinLeave * call UltiSnips#LeavingBuffer()

**Comment by mwcz** [comment]
And the problem was resolved, by @SirVer's wizardly incantation.  That works perfectly.

vim-- for inconsistency, but vim++ for at least documenting the inconsistency, right?
