### ISSUE TITLE
Jump *first* and then try expanding

### ISSUE THREAD

**Issue by moll** [SirVer/ultisnips#527]
Hey,

I've got `UltiSnipsExpandTrigger` and `UltiSnipsJumpForwardTrigger` mapped to the same tab key. I occasionally name code variables etc. with the same name as my snippets. While inside another snippet, those keep on recursively expanding. Useful in some cases, not so in others.

Is there a way to configure UltiSnips to first try jumping and only if not inside a snippet, expand? I could then map explicit expanding to another key and not have to worry about single character variable names interfering with single character snippets while hitting tab. I see it may be possible by manually calling `UltiSnips#ExpandSnippetOrJump` and checking some globals, but it's not clear off the top of my head how to go about so.

Thanks!

**Comment by SirVer** [comment]
You can hack yourself that together using a custom mapping. See [this comment](https://github.com/SirVer/ultisnips/issues/376#issuecomment-97869844) for an example of how to call UltiSnips functions and check if they are successful and go from there.

**Comment by moll** [comment]
Hey, thanks. Managed to cook something up that finally works. Took some time going through the source though. Noticed I had to add my special function to `UltiSnipsMappingsToIgnore`, too. Otherwise it broke tabbing through placeholders.

**Comment by SirVer** [comment]
Can you share? Others might be interested in that solution too.

**Comment by tandrewnichols** [comment]
@moll What was your solution? I ran into that with these snippets:

```
snippet it
    it('${1}', ($2) => {
      ${0}
    })

snippet (
    (${1}) => ${0}
```

I type "it" then "<Tab>", type my test description and then "<Tab>" again. The second placeholder is for an optional callback, but if I don't add one and just hit "<Tab>" right away, it expands the second snippet instead (and it'll do this over and over since the first placeholder is inside the parentheses), so it ends up looking like:

```
it('some test description', (|) => () => {

})
```

with the cursor stuck (i.e. tab doesn't advance to the next placeholder) where `|` is.
