### ISSUE TITLE
Include or replace snippets temporarily for embedded languages

### ISSUE THREAD

**Issue by moll** [SirVer/ultisnips#534]
Hey,

Often templating languages (e.g. HTML with CSS and JavaScript) allow embedding different languages. Have you thought of having the ability to temporarily include or replace the current set of snippets with a different filetype's set when the cursor is inside embedded languages? I do know there are context sensitive filters for snippets, but those are per snippet. One can also include other filetypes' snippets wholesale, but those snippets will then be available in the outer language, too.

Cheers

**Comment by SirVer** [comment]
Well, there is the [extends](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L568) keyword which tells UltiSnips which filetype extends which other. 

Everything else is a limitation of Vim rather than UltiSnips: vim sets `filetype` on a per file basis and cannot change it in paragraphs. It supports embedding syntax highlighting of other languages as a hack - but it really is a hack: you do not get indenting, ftplugin or any other of your settings. Other editors handle this much more gracefully.

UltiSnips is bound by Vim's mental model. Hacking in your suggestion would be unreliable (i.e. it would need to rely on Vim's syntax parsing), slow and even surprising for people in the Vim mindframe. I think this feature suggestion should probably go to Neovim.

**Comment by moll** [comment]
Fair enough. Thanks.
