### ISSUE TITLE
Installation using Pathogen: missing link info

### ISSUE THREAD

**Issue by caneta** [SirVer/ultisnips#535]
Hi SirVer, I got some problem installing your plugin with Pathogen...but in the end I succeeded, so I would like to give you a little suggestion.
In the documentation, after line 142 of UltiSnips.txt, I would add the following:
```
cd ~/.vim/bundle
ln -s ultisnips/vim-snippets vim-snippets
```
Following Pathogen installation guide in section *UltiSnips-installnupdate* the plugin did not work.
I spent a lot understanding what I was missing and finally with the above lines everything started to work.
In the very next section, *UltiSnips-using-a-downloaded-packet*, there is a mention about a link creation, but in my opinion it's not clear if a Pathogen user has to follow also that section or not.
I hope I was helpful.
Best regards,

Caneta

**Comment by SirVer** [comment]
There is no vim-snippets folder in the UltiSnips repo, so that link you needed to make cannot have had anything to do with UltiSnips. UltiSnips the engine comes without snippets though. It is likely that you cloned https://github.com/honza/vim-snippets into the wrong directory - it should go into your bundle directory, not into UltiSnips.

I believe what has happened in your case is this:

1. you cloned UltiSnips correctly and it worked properly - but you could not know since there was no snippet available to test with.
2. you cloned vim-snippets, but not into `~/.vim/bundle` but into `~/vim/bundle/ultisnips`. 
3. you needed the symlink to make pathogen find vim-snippets.


The link in the download section is not needed for pathogen - pathogen takes care of that.

**Comment by caneta** [comment]
Yes, it was exactly as you described.
And that's because following the installation instructions, I got this git error:
```
canduc@candesktop:~$ cd ~/.vim/bundle && git clone git://github.com/SirVer/ultisnips.git
Cloning into 'ultisnips'...
remote: Counting objects: 6547, done.
remote: Total 6547 (delta 0), reused 0 (delta 0), pack-reused 6547
Receiving objects: 100% (6547/6547), 3.51 MiB | 745.00 KiB/s, done.
Resolving deltas: 100% (3349/3349), done.
Checking connectivity... done.
canduc@candesktop:~/.vim/bundle$ git submodule add https://github.com/honza/vim-snippets.git
fatal: Not a git repository (or any of the parent directories): .git
```
In this situation, I tried moving inside ultisnips directory where the second git command succeeded:
```
canduc@candesktop:~/.vim/bundle$ cd ultisnips/ && git submodule add https://github.com/honza/vim-snippets.git
Cloning into 'vim-snippets'...
remote: Counting objects: 4819, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 4819 (delta 2), reused 0 (delta 0), pack-reused 4809
Receiving objects: 100% (4819/4819), 1.27 MiB | 803.00 KiB/s, done.
Resolving deltas: 100% (2758/2758), done.
Checking connectivity... done.
```
Why the git submodule command did not work? What is its purpose for having a working UltiSnips installation with some examples to test?

So in the end I've tested that the correct steps to follow in order to have a working out of the box plugin are:

    1 - cd ~/.vim/bundle
    2 - git clone git://github.com/SirVer/ultisnips.git
    3 - git clone https://github.com/honza/vim-snippets.git

Extremely simple, but not properly clear from the docs.

Thank you for your response,

Caneta

**Comment by SirVer** [comment]
I see, that was indeed confusing in the docs. I fixed them. Thanks for the report!
