### ISSUE TITLE
Vim slowdown in insert mode after PR #539

### ISSUE THREAD

**Issue by osleg** [SirVer/ultisnips#552]
Vim became very sluggish in insert mode after #539
profile shows slowness on TrackChange() function.
```
count  total (s)   self (s)  function
   24   1.912173             UltiSnips#TrackChange()
``` 
it indeed feels like it takes about a half second for every char to appear.
Rolling back to pre #539 fixes the issue.

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 11 2015 08:45:35)
Included patches: 1-778
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz  -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl   -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic   -lruby -lpthread -lgmp -ldl -lcrypt -lm  -L/usr/lib    
```

**Comment by SirVer** [comment]
cc @seletskiy 

Stanislav, any ideas about this?

**Comment by seletskiy** [comment]
@osleg: Do you have HDD or SSD? Try to set `g:UltiSnipsSnippetDirectories` to `[$HOME . '/.vim/UltiSnips']` (or another directory, where snippets are located and see if it make difference or not.

I guess I have some thoughts why it can be slow.

**Comment by osleg** [comment]
@seletskiy I have SSD
I have this line in my config `let g:UltiSnipsSnippetDirectories=["UltiSnips", "/home/alex/.vim/bundle/angular-vim-snippets/UltiSnips"]` 
Commenting it out or changing to the one you asked doesn't change anything. 

Profile with Ultisnips without anything in config 
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   58   2.586945             UltiSnips#TrackChange()
   38   1.144387             <SNR>232_GetCompletions()
   74   1.143902   0.013038  youcompleteme#Complete()
   12   0.688888   0.003229  youcompleteme#OmniComplete()
   66   0.036426   0.006850  airline#check_mode()
   39   0.029703   0.006357  <SNR>232_OnCursorMovedInsertMode()
    2   0.029324   0.005496  airline#highlighter#highlight()
   43   0.021802   0.002621  <SNR>218_exec_separator()
   66   0.019530   0.001627  bufferline#refresh_status()
   66   0.017903   0.004748  bufferline#get_echo_string()
   86   0.016686   0.000990  airline#themes#get_highlight()
   90   0.016599   0.004978  airline#highlighter#get_highlight()
   66   0.013155             <SNR>65_generate_names()
   66   0.012794   0.001508  airline#extensions#tagbar#currenttag()
   16   0.011286   0.001446  tagbar#currenttag()
   29   0.011125             <SNR>232_IdentifierFinishedOperations()
  180   0.009427             <SNR>218_get_syn()
   66   0.009158   0.005301  airline#extensions#hunks#get_hunks()
   16   0.008509   0.008225  <SNR>227_GetNearbyTag()
   79   0.008336             <SNR>181_Highlight_Matching_Pair()

```
Profile with `let g:UltiSnipsSnippetDirectories=["UltiSnips", "/home/alex/.vim/bundle/angular-vim-snippets/UltiSnips"]`

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   50   3.154101             UltiSnips#TrackChange()
   58   0.411009   0.011839  youcompleteme#Complete()
   29   0.399170             <SNR>232_GetCompletions()
   70   0.075681   0.007735  airline#check_mode()
    4   0.067388   0.014539  airline#highlighter#highlight()
   83   0.043843   0.005245  <SNR>218_exec_separator()
  166   0.033612   0.001933  airline#themes#get_highlight()
  170   0.032532   0.009714  airline#highlighter#get_highlight()
   14   0.031881   0.004958  <SNR>232_OnFileReadyToParse()
   14   0.026714   0.026586  <SNR>232_UpdateDiagnosticNotifications()
   33   0.025181   0.004962  <SNR>232_OnCursorMovedInsertMode()
    2   0.023959   0.000056  <SNR>232_OnCursorHold()
   70   0.020249   0.001746  bufferline#refresh_status()
   74   0.019657   0.005147  bufferline#get_echo_string()
  340   0.018563             <SNR>218_get_syn()
  271   0.016095             airline#highlighter#exec()
   74   0.014510             <SNR>65_generate_names()
   70   0.012625   0.001520  airline#extensions#tagbar#currenttag()
   16   0.011105   0.001386  tagbar#currenttag()
   24   0.010847             <SNR>232_IdentifierFinishedOperations()
```

Profile without ultisnips at all
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   60   0.311126   0.015047  youcompleteme#Complete()
   30   0.296079             <SNR>226_GetCompletions()
   81   0.082554   0.009608  airline#check_mode()
    6   0.072314   0.015718  airline#highlighter#highlight()
   11   0.057207   0.012937  <SNR>226_OnFileReadyToParse()
   10   0.056456   0.001434  <SNR>226_OnCursorMovedNormalMode()
  119   0.048975   0.005853  <SNR>213_exec_separator()
   11   0.044129   0.044045  <SNR>226_UpdateDiagnosticNotifications()
  238   0.037536   0.002176  airline#themes#get_highlight()
  250   0.037495   0.011357  airline#highlighter#get_highlight()
   39   0.027218   0.006516  <SNR>226_OnCursorMovedInsertMode()
   81   0.026140   0.002246  bufferline#refresh_status()
   81   0.023894   0.006292  bufferline#get_echo_string()
  500   0.021115             <SNR>213_get_syn()
  381   0.017667             airline#highlighter#exec()
   81   0.017602             <SNR>65_generate_names()
   81   0.016252   0.001921  airline#extensions#tagbar#currenttag()
   17   0.014331   0.001883  tagbar#currenttag()
   25   0.014073   0.001422  airline#extensions#tabline#get()
   25   0.012651   0.001469  airline#extensions#tabline#buffers#get()
```

And profile with your line 

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   56   1.585673             UltiSnips#TrackChange()
    1   0.481728   0.003262  UltiSnips#Edit()
    3   0.410711   0.272739  <SNR>232_OnBufferVisit()
   15   0.214156   0.120213  <SNR>232_OnFileReadyToParse()
   48   0.163896   0.009281  youcompleteme#Complete()
   24   0.154615             <SNR>232_GetCompletions()
    1   0.120851   0.057629  <SNR>154_persistCache()
   82   0.103041   0.008743  airline#check_mode()
   15   0.093730   0.093619  <SNR>232_UpdateDiagnosticNotifications()
    6   0.093334   0.022966  airline#highlighter#highlight()
    1   0.087409   0.000146  <SNR>251_VimCssInit()
    1   0.087011   0.001765  <SNR>251_AdditionalColors()
  147   0.085246   0.010459  <SNR>251_MatchColorValue()
    1   0.081679   0.000072  neomru#_save()
    2   0.081607   0.000580  495()
  147   0.072597             <SNR>251_XTermColorForRGB()
  152   0.070046   0.007600  <SNR>218_exec_separator()
    1   0.065897   0.004621  <SNR>9_SynSet()
  366   0.063906   0.020633  airline#highlighter#get_highlight()
    1   0.063222             <SNR>154_readCache()
```
While it is a bit faster with 
`g:UltiSnipsSnippetDirectories=[$HOME . '/.vim/UltiSnips']` - it doesn't provide 
snippets (I don't have em in given directory) and still takes 1.5 seconds for execution

Maybe this is somehow related to YCM as well?

**Comment by osleg** [comment]
Also, maybe it matters, I'm using console vim, not gvim

**Comment by demon386** [comment]
+1 with this. Typing with YouCompleteMe becomes very very slow.

My profile log:
```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
  102              8.593525  UltiSnips#TrackChange()
   38              0.968263  <SNR>221_GetCompletions()
    7              0.377117  <SNR>187_check_mixed_indent()
   29   0.252822   0.252072  <SNR>221_OnFileReadyToParse()
    7   0.279799   0.150599  <SNR>221_OnInsertLeave()
   76   1.048468   0.080205  youcompleteme#Complete()
 1280              0.073472  airline#highlighter#exec()
   20   0.183268   0.057500  airline#highlighter#highlight()
  107              0.053506  <SNR>57_generate_names()
   28   0.051563   0.051168  <SNR>215_GetNearbyTag()
   39              0.040689  <SNR>221_IdentifierFinishedOperations()
  768              0.024801  <SNR>190_get_syn()
  122              0.017333  <SNR>151_Highlight_Matching_Pair()
  384   0.042960   0.012809  airline#highlighter#get_highlight()
   93   0.195958   0.010288  airline#check_mode()
  107   0.062983   0.009477  bufferline#get_echo_string()
   93   0.384852   0.007735  airline#extensions#whitespace#check()
  192   0.064460   0.007693  <SNR>190_exec_separator()
   93   0.012791   0.007492  airline#extensions#hunks#get_hunks()
   93              0.007321  108()
```

**Comment by osleg** [comment]
Just tried to disable YCM, doesn't change anything at all, so it not related to the problem :/

**Comment by demon386** [comment]
Not just about YCM. I notice obvious lag with Unite (https://github.com/Shougo/unite.vim) too.

**Comment by suy** [comment]
I use GVim, and I noticed the slow down too. I have no snippet configured to use auto trigger, so it could be something still optimizable.

**Comment by SirVer** [comment]
I rolled back the merge for now until we have a solution to the slowdowns. Guys, could you please all post your Vim version, OS version, CPU, Mem and everything that might be slightly related. Also please try to repro the slowdown with UltiSnips as your only plugin.

**Comment by demon386** [comment]
I uses MacVim with OS X Yosemite. I don't think it's related to CPU, mem, becamse my Mac Mini at home experiences the same thing as my Macbook Pro.

My MacVim version is 7.4-77.

**Comment by osleg** [comment]
I attached vim version in first post
here is the rest of info
```
OS    : Arch Linux x86_64
Kernel: 4.1.5-1-ARCH
Shell : /bin/zsh
RAM   : 7828M
CPU   : Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
SSD   : Corsair Force GT
```

I also tried Ultisnipst as the only plugin installed (well 2 plugins, UltiSnips and 'honza/vim-snippets') the results are the same

**Comment by oblitum** [comment]
Got this too on OS X and Linux. I build vim myself, I'm generally on master.

**Comment by SirVer** [comment]
@oblitum This is rolled back on head - are you still seeing this issue?

@seletskiy Are you tackling this performance degradation?

**Comment by oblitum** [comment]
@SirVer no, head is fine now, just wanted to report.

**Comment by seletskiy** [comment]
@SirVer: I've tried to repro this issue with honza/vim-snippets without any lack. However, I'll try to improve performance in near future.

**Comment by seletskiy** [comment]
Ok, the main reason of slowdown is that US tries to search for new snippet definitions on each expand (I overlooked that, my bad). I'll fix it.

**Comment by seletskiy** [comment]
@osleg, @demon386, @suy, @oblitum, can you test autotrigger branch from my fork (seletskiy/ultisnips@1649cad)? I think performance issues should be fixed.

**Comment by SirVer** [comment]
@osleg @demon386 @suy @oblitum Ping? Please, neither @seletskiy nor me can repro your performance degradation apparently, so you guys need to test for us.

**Comment by suy** [comment]
I think I see a clear improvement, but still a bit noticeable. But maybe it's just the placebo/nocebo effect. I'd better wait for somebody who has done a proper profiling, since I don't know how to do it.

**Comment by seletskiy** [comment]
@suy: Did you tested my latest (not SirVer/Ultisnips) changes in branch autotrigger`?

**Comment by suy** [comment]
Yes, of course. :)

**Comment by osleg** [comment]
It is much faster now, yet it still a bit laggy.
Not to the extend that it's impossible to work as it was before though.
If it possible to introduce a variable to disable it, or better a toggle function it would be great and as by me could be marked as solved
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   28   1.167079             <SNR>208_GetCompletions()


FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
   28              1.167079  <SNR>208_GetCompletions()
```

**Comment by SirVer** [comment]
I do not want UltiSnips features to be toggable as much as possible. That complicates everything, especially the support (which mostly I am doing).

@seletskiy What is your plan going forward with this feature?

**Comment by seletskiy** [comment]
@SirVer: I use this feature on the daily basis. After fixing latest performance issue I see no other troubles of merging it back into the upstream (so do I see in the latest profiling table from @osleg).

**Comment by SirVer** [comment]
Stanislav, which branch should I merge to get this feature back into master?

**Comment by seletskiy** [comment]
@SirVer: I've made PR with latest commit from my local branch: #582.

**Comment by SirVer** [comment]
Merged back in. Closing for now.

**Comment by wadestuart** [comment]
@seletskiy and @SirVer  I did not want to open a new thread on this but I was looking at the auto trigger code,   I am wondering if it would make sense to memoize ala pylru (its faster than the lru that just landed in 3.3 and was backported) the code around get_snippets and _snips as it seems very hot (even with the cut down of autotrigger_only).  I would hope that given even a small cache size you could marginalize almost all penalties for the scan on keystroke.  pylru is pretty easy to integrate (there may be other hot areas to memoize too) and you can easily clear all cache on an edit of the snippit files.  Let me know if that sounds interesting to you,  if so I can look at taking a stab and seeing what the bench looks like or you can up to you.

**Comment by seletskiy** [comment]
@wadestuart: I don't exactly understand, how (py)LRU can speed up the performance in that case? Can you provide an explanation?

LRU is good as cache mechanism, but in `get_snippets` and `_snips` we are *should* to walk all snippets and try to match trigger (and, possibly, python condition) and it's different from LRU.

**Comment by wadestuart** [comment]
Maybe I am reading it wrong,  but I see it as given a set of parameters both get_snippits and _snips run a deep loop and logic to return a list of snippits.  By memoizing the function with lru (FunctionCacheManager or the function decorator) you would allow a very little work lookup of the snippit returns given the same parameters instead of performing all of that logic on hot runs while being able to set a fixed cache size.   get_snippits and _snips are both highly cache able right? I mean given the same params they will return the same output or no?

**Comment by seletskiy** [comment]
Unfortunately, no.

Two points there: (a) on each expand UltiSnips engine will do hot-reload of
snippet sources, so new snippets will become magically available for
expansion when you edit snippet files (ok, it can be solved in different
way); (b) snippets can be context based so different snippets can be used
for expansion with same trigger text, e.g. snippet "a" can be provided with
context so it will be expanded when expansion occurs inside string syntax.

If (a) can be implemented in different way, like reloading snippet sources
on cursor idle events, I do not see how (b) can be optimized.

**Comment by wadestuart** [comment]
@seletskiy Looking at the code,  it seems that the only variation on self (that triggers change for cachability)  that happens is register_snippet_source and unregister_snippet_source where you can add a clear on the lru in those functions and rebuild the cache table transparently.   Given that,  where is the other mutation coming from?  I don't see anything else being passed or used to _snips or get_snippits that is not deterministic based on the parameters passed in?

**Comment by wadestuart** [comment]
@seletskiy Basically high level it looks like this:

for every call to get_snippets the decorator does a transparent lookup to see if it has been called with the same params before and there is a cache hit,  if so it just delivers the return for that hit.  If not it runsthe code as normal and stores the return as a cache keyed on the params.   If you insert the lru clear in the two mutations for snippit source than when any snippet is added or removed it will just clear the cache and transparently start building it again.  So if you are hot calling the get_snippets or _snips from something like autotrigger very frequently (such as when a user hits "        ") the cache will be hit and you get free results instead of doing what look like 5 or so deep loops to scan for snippets that may be returned.

**Comment by seletskiy** [comment]
@wadestuart: Let me illustrate point (b):

![a](https://cloud.githubusercontent.com/assets/674812/10783006/6b852118-7d76-11e5-871c-b7569b97f40a.gif)


See, how typing `i` in the beginning of the file automatically triggers expansion of the `import` snippet?

And then, after some function is declared, `i` is no longer expands into `import`. However, if I move cursor back to the import statements, `i` is automatically expanding into `import` again.

**Comment by wadestuart** [comment]
@seletskiy but isnt the return from _snips and get_snippets in each of those cases reliant on the parameters they are called with?  I mean they are deterministic so that (assuming you rebuild cache on the places I talked about above) for each state you are showing in the gif they are being called with a specific set of parameters and for those parameters they will always give the same result.  I will have to look through the code in more detail,  I have not coded in python in 5 or 6 years so I am pretty rusty here but it seems like given attaching a clear to the actions that add or remove snippets from the set and tweaking of the _snips and get_snippets params that it should just be a drop in to get cachng on these.   I must be missing something here.

**Comment by seletskiy** [comment]
@wadestuart: no, it's not. In both cases params for `_snip` and `get_snippets` will be the same, it's whole point. Will snippet `i` be expanded or not determined by python function which is specified in the snippet definition:

```
snippet "^i" "import" "filter_previous_buffer(snip, '^(#|$|import |from )')" reA
import 
endsnippet
```

**Comment by SirVer** [comment]
@wadestuart Stanislav is right, those function depend on side effects, mainly files changing on disk. LRU does not help at all. What would help is a `inotify` based watcher implementation, so that we could swap polling against pushing. 

Unfortunately - and that applies to your LRU suggestion as well - it is quite the non-starter to depend on any third party module in a Vim plugin. First there is compatibility: find a watcher library that works on windows, mac and linux. 

Second there is the ease of installation: A plugin has no way of compatibly running some sort of install hook - so every user has to manually install the dependency which then bitrots on their disk - so you have to deal with tons of different versions of your dependency as well. Telling vim users to install some python module site-wide is a non starter - because a lot of them can't. And even if they can do it, you also do not know if that is the particular Python version that Vim is actually ending up using. 

Throw in Neovim where everything is different again, it becomes even worse.

No, unfortunately for maintenance reasons we are sort of stuck with stock modules.

**Comment by wadestuart** [comment]
@SirVer that is too bad,  regarding the side effects -- I am still trying to wrap my head around why/where it is non deterministic specifically as I am not seeing it (I am sure it is I just dont see where the side effects are being pulled in). Can you point me to a place in the code (_snip and get_snippets) where files changing on disk (except for adding/removing snippits) is pulled in as a side effect?

Regarding the install/platform support that is the beauty of the lru module you can wrap the import in a try and because it is a decorator there is no issue on systems that have not installed it -- its transparent caching/memoization and because its lru is deterministic size caching too.  For systems that would want the extra performance and have the ability to install all they would need to do is install it.

**Comment by wadestuart** [comment]
@SirVer regarding inotify the standard way to handle this is to use (either homebrew or modules) that hook to inotify or windows change event or macos FSevents finally fall back on polling.  In this case,  because of the issue with module install and cross platform it may be possible to simply just do a poll wrapper on functions that need to check for new data that stash the modified timestamp of the file the last time it was read in and scanned and short circuit the cached result if the modified time is not newer than the last scan.   The only real difference here is that inotify is nicer because it gives a notification and you don;t have to poll a directory of thousands of files to understand as soon as one changes -- in our case we only care if a file changes when we need to act on it so we have a free poll opportunity.   The only things I think will be a little work here are isolating the functions that read these files and there may be a modified time low granularity on some obscure systems that you want to support that would need to turn off the poll cache.

**Comment by SirVer** [comment]
@wadestuart The culprit is SnippetSource.ensure, for example [here in a derived class](https://github.com/SirVer/ultisnips/blob/master/pythonx/UltiSnips/snippet/source/file/_base.py#L41) that will go to the filesystem to see if there are new snippet files or if any have changed. 

I am pretty sure, an LRU cache will not buy us anything here. You need to provide numbers to convince me otherwise.

We did the optimization you suggest already before, i.e. only using a stat() instead of a full hash. Since there are so few snippet files and the OS is so good at caching content it did not change the performance in my measurements at all. A bigger issues is that we also need to know if new files are created - since snippets can be distributed over many files - so we also need to do a few lsdir()s which is also slow.

Feel free to experiment with the timings - if you find something that is significantly faster and compatible, we will gladly merge.

**Comment by seletskiy** [comment]
@wadestuart: you are trying to find solution to the point (a) from my previous message. There are some ways to overcome it, but profit/implementation cost is non-clear at all. You're trying to propose active polling, as far as I understand, but it is will require additional background thread, and threading in vim-python is **no way**. It's very error prone and very difficult to work with, because vim is "not thread-safe".

You entirely omitting point (b) about context snippets, and without some really smart way to cache this it's pointless to invent some caching for (a).

Context snippets are non-deterministic in sense that they expansion can depend on anything, including current buffer state, other buffer state, date, time, files on file system, result of network request or whatever you will write in context-checking python function. Of course, I overemphasizing it, but most common use of the context is to check something in the buffer before or after the cursor. `_snips` and `get_snippets` will be given only with the current **line** before cursor, so they are not aware what is above or below current line.

**Comment by wadestuart** [comment]
@seletskiy I was answering @sirvers response items.  For the polling question,  I don't think we would need a background thread at all -- snips are either loaded from a known set of files or inserted dynamically.  In this case you can run a poll (really just testing inline) if the files have been changed on each call -- I am not sure if that buys us anything over the sha hash that currently happens (i guess it depends on just how hot the process/lookup path is as stat mtime on a small set of files is very likely to be cached by the OS vs a open+ read+ sha hash and string compare * x files).  The point being is that we know when we need to check if a file has been modified so we dont need to thread out and get notified of the update,   we can just do the mtime test before we go load the file (as long as this is faster/better than the sha ensure). 

regarding the point b,  I am still wrapping my head around this code. I do understand that some of these snippet types are dynamic and recursive and pull in unknown processing,   on the other hand there are a lot of types of snippets that seem like they would be completely dependent only on the before and other params that we are able to memoize.   My gut tells me that if we are able to lessen the hot deep loop buy pulling the ones out and short circuiting the LRU cache on them we will find that for many common param sets the bubble up of return for that segment will be "free" while we would still need to deep loop on the other types. 

Right now I am just trying to wrap my head around the code and see if there is a way to speed it up because the autotrigger stuff seems to have put a much larger cost on each keystroke for the plugin.  from what I have seen of the changes I love them,  but vim is feeling like a remote ssh session now.   My gut is telling me there should be ways to cut this tight loop down so it feels much more responsive while retaining the new abilities of the trigger.   The easy way for this speedup is obviously to fork and kill it off,  what I am trying to do is see if there is some way I can make it livable for me.   Its not nearly as slow as it was before the changes here but still way more laggy than before.

**Comment by wadestuart** [comment]
@seletskiy to be clear,  the fork and kill it means I would just fork it for my own use and keep a slimmed version not fork to compete.

**Comment by seletskiy** [comment]
@wadestuart: no need to fork if you experience problems with autotrigger, you can just remove autocommand by using `au! UltiSnips_AutoTrigger`.

**Comment by seletskiy** [comment]
@wadestuart: I do understand you point more clearly now, thanks for explanation. But I really doubt to see how caching will be real solution here due to tremendous miss/hits ratio. BTW, are you using neovim or vanilla vim? Because performance degradation is known issue in neovim, but for vim it should work just fine. If you experiencing problems in vim, can you, please, run profiling to see how many time it's exactly takes for run UltiSnips autocommand?
