### ISSUE TITLE
expand in the middle of the line

### ISSUE THREAD

**Issue by cacplate** [SirVer/ultisnips#564]
Is it possible to expand a snippet like so?
`something* something else`
and then expand the first `something` regardless of the `something else`.

**Comment by SirVer** [comment]
Obvious answer is yes. Likely with the inword option or regex. If you could provide a more specific example of what you want, I'll try to help.

**Comment by cacplate** [comment]
I narrowed down the problem. suppose I have a snippet defined as follow
```
snippet frac "latex frac tag" !i
\frac{$1}{$2}
endsnippet
```
that does what it is meant.
I use unicode characters in my latex code and it seems to trigger correctly anytime except when I try in front of a unicode character.

**Comment by SirVer** [comment]
so first, `!` option has not been in ultisnipes for > 2 years - we use priorities now.

And I think your problem comes down to your vim settings: ':help iskeyword'. This defines what is a word/a word boundary. Try changing this setting, if you still believe it is an UltiSnips issue, please post here again.
