### ISSUE TITLE
Regular expression can not work.

### ISSUE THREAD

**Issue by tang3w** [SirVer/ultisnips#576]
The snippet which not work is:

```
snippet /#i(n|nc|ncl|nclu|nclud)/ "#include" rb
#include 
endsnippet
```

Above snippet will only triggered when I type `#in`, `#inc` ~ `#includ` will not work.

**Comment by SirVer** [comment]
That is subtle, but working as intended. The problem here is that the regular expression must match the full length of your trigger. Otherwise an empty regex would always match.

For example if you had typed `#inc<expand>`, the regular expression you used will return a successful match for your first branch `#in`, which is not your full trigger. You can fix this in two ways.

Either, let the matcher try your longest match first:

`/#i(nclud|nclu|ncl|nc|n)/`

or explicitly ask that the trigger ends after your match

`/#i(n$|nc$|ncl$|nclu$|nclud$)/`
