### ISSUE TITLE
How to call a vim plugin in a snippet

### ISSUE THREAD

**Issue by ahmedelgabri** [SirVer/ultisnips#594]
I have a todo snippet in `all.snippets` 

```
snippet todo "Add a todo with date and github username" b
@TODO: ${1:Do something} (`!v strftime("%d-%m-%y %H:%M")`${2: - `echo $GITHUB_USER`})
$0
endsnippet
```
I want to call [commentary](https://github.com/tpope/vim-commentary) on the whole line, instead of creating the same snippet for each language with the right comment syntax.

So is this possible using Vim  interpolation?

**Comment by SirVer** [comment]
Maybe.... First let me explain why this is hard: Vim does not inform plugins about changes done to the buffer, so if you modify the buffer while UltiSnips has a snippet active, you will confuse it since its internal buffer marks have been shifted around. Consequently, it will modify parts of the buffer that are not part of the snippet.

However, @seletskiy added a new feature recently called [post expand](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L1508) that allows changing the buffer under the snippet, as long as you inform UltiSnips how the buffer changed. I am not sure how you can call a VimFunction on the line though and still understand how it changed without running a diff algorithm, but maybe Stanislav has an idea.

Another approach would be to just use `vim_snippets.get_comment_format` ([example usage](https://github.com/honza/vim-snippets/blob/master/UltiSnips/all.snippets#L42)), this will get you to the same result, but of course not using `commentary`.

**Comment by ahmedelgabri** [comment]
Thanks @SirVer for the detailed reply. 

I can live with this limitation, I was just wondering if it can be done and thanks for the great plugin.

**Comment by seletskiy** [comment]
@ahmedelgabri: It depends on the plugin. If the plugin modifies buffer, then it's not possible right now to call it, because it will lead to desync in the internal UltiSnips buffer implementation and actual modified buffer (UltiSnips has no way to directly get buffer change information from vim).

I added special handling for that case and any change of the buffer outside of special `snip.buffer` variable in the snippet will lead to the runtime error.

**Comment by ahmedelgabri** [comment]
Thanks @seletskiy, I will close this then.
