### ISSUE TITLE
Nested snippets

### ISSUE THREAD

**Issue by tbastos** [SirVer/ultisnips#604]
Hey, thanks for this plugin!

I can't figure out, based on the documentation, if this is possible. I'd like to include multiple child snippets into a parent snippet, and expand all child snippets at the same time with the parent.

For example, if I have a snippet "foo" and another "bar", I'd like to define a snippet "fb" that's equivalent to "foo\<tab> bar\<tab>", so I don't have to hit \<tab> several times for each child.

Is there a way to do this with a post-action in python or something?

Thanks again!

**Comment by seletskiy** [comment]
@tbastos: For now it's possible to expand anon-snippets only. See advanced usage of this feature in my [go.snippets](https://github.com/seletskiy/dotfiles/blob/master/.vim/UltiSnips/go.snippets#L403-L430) (I'm typing <kbd>do Tab</kbd>, which expands snippet for docopt, then jump to last placeholder and get usage snippet expanded):

![a](https://cloud.githubusercontent.com/assets/674812/11027596/c578c5e2-86d8-11e5-96cb-7ce4e459f0a0.gif)

It's not possible to expand named snippets, because they heavely based on currently entered text, like regexp snippets or context snippets.

**Comment by tbastos** [comment]
That makes sense, thanks!

**Comment by seletskiy** [comment]
@tbastos: You're welcome!
