### ISSUE TITLE
Add a possibility to disable all default maps

### ISSUE THREAD

**Issue by hl037** [SirVer/ultisnips#633]
Hi,
I would like to use and map by myself only the expand and jump forward functions, without the others. Could you add a boolean variable to disable all default map keys ? (current behavior is to assign a default map if not defined, or to give the possibility to list conflicts)
(ok I think I just have to redefine the other maps to disable them, but if you add a new feature in the future, I want to keep the current behavior and look by my self if I want it)

on an old commit I added a test to prevent the redefinition, but the code has changed a bit since ^^

**Comment by hl037** [comment]
I did a pull request on it ;) #634

**Comment by seletskiy** [comment]
@hl037: Thanks for the PR!

However, is it really necessary to add new code into the UltiSnips rather than having vimrc with other mappings set to <kbd>&lt;NUL&gt;</kbd>? Select mode maps are required for correct work of snippet engine in the select mode, and besides of that there is only one keybinding left that can be unmapped: `g:UltiSnipsListSnippets`.

So, in fact, you're exchanging one line to another

```
let g:UltiSnipsListSnippets = '<NUL>'
```
→
```
let g:UltiSnipsNoMap = 1
```

Correct me, if I'm wrong.

**Comment by MintPaw** [comment]
Yeah, this is a bit of a problem, I remap tab in my vimrc, but the imap doesn't stay because this plugin overrides it, I hope this gets worked out soon.

**Comment by seletskiy** [comment]
@MintPaw: just add to your vimrc `let g:UltiSnipsExpandTrigger = "<NUL>"`.

**Comment by MintPaw** [comment]
@seletskiy Ah thanks, I had tried that but didn't realized closing and reopening a tab doesn't correctly reload the binding, vim needs to be closed entirely.

**Comment by seletskiy** [comment]
@MintPaw: No problem, you're welcome!

**Comment by gwerbin** [comment]
I know this is an old issue, but let me add a +1 for the original suggestion. I understand that it might be easy or hard to implement depending on how UltiSnips mappings are implemented, but I think it's a matter of courtesy to users to allow them to disable all default mappings if they prefer. Otherwise the burden is on the user to carefully peruse the documentation and add a bunch of `let g:UltiSnipsThingamajig = "<NUL>"`s to their startup file.
