### ISSUE TITLE
how to expand visual selection?

### ISSUE THREAD

**Issue by peterdutton** [SirVer/ultisnips#659]
Hi,

I'm trying to expand a visual selection but can't seem to get the plugin to trigger - nothing happens. I have Ctrl-Space mapped as the expansion key, and this is working fine for insert mode expansions. I checked :map for any clashes and these are the only two lines:

```
x  <C-Space>   * :call UltiSnips#SaveLastVisualSelection()<CR>gvs
s  <C-Space>   * <Esc>:call UltiSnips#ExpandSnippet()<CR>
```

I wondered whether my own snippet - which is in the html filetype - was the issue, so I tried a few from the PHP snippet file that I got from the honza repo, but that doesn't work either.

Any ideas? Thanks for your help.

**Comment by peterdutton** [comment]
No matter - I changed the key mapping to Ctrl-j and things started working in both modes.

**Comment by matthijskooijman** [comment]
I just ran into this problem as well, maybe this should be reopened?

C-space works fine for normal expansion, but not in visual mode. I also tried c-y, which also does not seem to work (also not for normal expansion).

If I manually run the commands that C-space maps to in visual mode, it works as expected, so somehow vim is not activating the mapping. Running `:map <c-space>` shows the right mappings:

	x  <C-Space>   * :call UltiSnips#SaveLastVisualSelection()<CR>gvs
	s  <C-Space>   * <Esc>:call UltiSnips#ExpandSnippet()<CR>

If I remap to `<tab>`, the visual part seems to work (but then the normal expansion conflicts with YCM, so that's not a workable solution).

Redefining to `<c-t>` seems to work, so I'm going to go with that for now, but it would be nice if this could be fixed (or, if it is some vim limitation, maybe be detected and reported by ultisnips).

**Comment by SirVer** [comment]
There is no bug in UltiSnips or Vim, the problem is that terminal emulators interpret `c-space` as NUL byte: 	https://github.com/microsoft/terminal/issues/2865#issuecomment-534723165. If you'd use gvim, this would have worked as expected.

**Comment by matthijskooijman** [comment]
Hm, somewhat surprising that it works in insert mode, but not visual mode, but maybe that's some vim detail. Having ultisnips raise a warning for this mapping (and maybe also other problematic ones) might be something to consider, but I guess it might be hard to predict whether something is actually problematic or not... Anyhow, thanks for looking into this :-)
