### ISSUE TITLE
How do I disable sets of completions?

### ISSUE THREAD

**Issue by Industrial** [SirVer/ultisnips#665]
Hi.

I'm using the [vim-snippets](https://github.com/honza/vim-snippets) plugin and it contains quite a lot of (to me) unneeded JavaScript snippet sets. Can I disable some sets like the jquery ones?

I opened a ticket for this in that repo but was directed here.

**Comment by seletskiy** [comment]
@Industrial: Either create file with corresponding name with `clearsnippets` directive in it or copy-and-paste only snippets that you want to use into `~/.vim/UltiSnips/` directory.

**Comment by deanishe** [comment]
I'm having a similar issue with vim-snippets, but it's the *snipMate* snippets I'd like to turn off/override (the snipMate Python snippets are mostly low-quality versions of the UltiSnips ones).

`clearsnippets` isn't valid in snipMate snippets and adding a file with the same name doesn't appear to work.

Am I missing something?

**Comment by seletskiy** [comment]
@deanishe: Just disable snipMate completely by adding `g:UltiSnipsEnableSnipMate = 0` to your `.vimrc`;

**Comment by deanishe** [comment]
Thanks for the speedy reply.

I don't want to disable *all* the snipMate snippets, just the Python ones. Is that possible?

**Comment by seletskiy** [comment]
@deanishe: You can try to disable/enable snipMate in realtime by using autocommand for specific filetype, but I'm not sure if it works or not.

**Comment by deanishe** [comment]
@seletskiy: Thanks very much. I'll give that a try.

**Comment by blacksails** [comment]
Maybe it would be nice to be able to ignore snipmate snippets if there is a ultisnips version for the file.

**Comment by lolilolicon** [comment]
With the new package support in vim 8, the `runtimepath` list is getting pretty long fast.
That's why it really makes sense to specify *one* directory for snippets, as described by the doc:
```vim
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']
```
BUT this currently only applies to **UltiSnips** snippets; for **snipMate** snippets, you either disable them all with `g:UltiSnipsEnableSnipMate = 0`, or, as by default, all `snippets` directories in `runtimepath` are checked and loaded.
I'd like to request an equivalent setting for **snipMate** snippets.

**Comment by SirVer** [comment]
Closing as answered.
