### ISSUE TITLE
Dynamic tab behaviour

### ISSUE THREAD

**Issue by ahmedelgabri** [SirVer/ultisnips#670]
While reading this http://howivim.com/2016/fatih-arslan/ I found that nice trick to make <kbd>tab</kbd> more [dyanmic](https://github.com/fatih/dotfiles/blob/master/init.vim#L576-L599) so I was wondering how can this be done with UltiSnips instead of neosnippet?

``` vim
" I want to use my tab more smarter. If we are inside a completion menu jump
" to the next item. Otherwise check if there is any snippet to expand, if yes
" expand it. Also if inside a snippet and we need to jump tab jumps. If none
" of the above matches we just call our usual 'tab'.
function! s:tab_complete()
  if pumvisible()
    return "\<c-n>"
  endif

  if neosnippet#expandable_or_jumpable() 
    return "\<Plug>(neosnippet_expand_or_jump)"
  endif

  return "\<tab>"
endfunction
imap <silent><expr><TAB> <SID>tab_complete()

smap <expr><tab> neosnippet#expandable_or_jumpable() ? 
      \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

inoremap <silent><expr><s-tab> pumvisible() ? "\<c-p>" : "\<s-tab>"
imap <silent><expr> <CR> pumvisible() ? "\<C-y>" : '<Plug>delimitMateCR'

autocmd InsertLeave * NeoSnippetClearMarkers
```

**Comment by seletskiy** [comment]
@ahmedelgabri: See `:help UltiSnips-trigger-functions`, you can find `UltiSnips#ExpandSnippetOrJump` there.

Personally, I do not recommend using it, because given, that it's best to use short snippet triggers for the most common snippets (max 3 chars long) you will often get false-positives with completion, which is undesirable.

I tried similar setup by myself in the past and dropped it off in favor of using <kbd>&lt;Tab></kbd> separately for snippet expansion and <kbd>&lt;C-P></kbd> for the previous completion match, <kbd>&lt;C-N></kbd> for the next completion match.

**Comment by ahmedelgabri** [comment]
Thanks @seletskiy I'll try and play with it and see if it's good idea or not. You have a valid point though about why it won't be perfect.
