### ISSUE TITLE
How to jump correctly?

### ISSUE THREAD

**Issue by dragonxlwang** [SirVer/ultisnips#672]
Can I still jump back once reaching the end of the trigger words ($0, $1, $2, etc)? I thought it more like cycling or at least one can jump forward/backward even already reaching the end (like bouncing between $0, $1, $2 so on and so forth) but it seems for me I couldn't get it done. Once I reach the last word and keep jumping it doesn't work anymore.

Here's my settings and what it looks like by what I mean...

In my vimrc, to reproduce this problem I already disabled YCM, and changed the keymap to what everyone suggests.
![image](https://cloud.githubusercontent.com/assets/15812510/13937249/7a5b39ec-ef91-11e5-8e7c-9ce7f350d5a1.png)

You can see how the jump got stuck  once reaching the boundary... 

![untitled](https://cloud.githubusercontent.com/assets/15812510/13937305/dd875910-ef91-11e5-9e1a-4b1f61309e7b.gif)

**Comment by seletskiy** [comment]
@dragonxlwang: Unfortunately, it's impossible to jump back after you reach `$0` placeholder because of performance reasons. UltiSnips finishes snippet as soon as you reach last placeholder to keep things fast.

BTW: do not use long snippet triggers. Try to keep it in between 1 and 2 symbols. So, use `fi` instead of `forin`.

**Comment by dragonxlwang** [comment]
thanks! :P
