### ISSUE TITLE
Strange behaviour in python snippet (using vim interpolation)

### ISSUE THREAD

**Issue by purpleP** [SirVer/ultisnips#676]
In [this](https://github.com/honza/vim-snippets/blob/master/snippets/python.snippets) file you can see def and deff snipptets
Here they are, if you don't want to open link

```
# New Function
snippet def
	def ${1:fname}(${2:`indent('.') ? 'self' : ''`}):
		"""${3:docstring for $1}"""
		${0}
snippet deff
	def ${1:fname}(${2:`indent('.') ? 'self' : ''`}):
		${0}
```

What the author is trying to do is pretty smart because he's using indentation level too add or to not add self argument. But how it works is really strange. I've recorded a [video](https://dl.dropboxusercontent.com/u/28070056/out.gif) to show you.

**Comment by seletskiy** [comment]
@purpleP: It's because UltiSnips by design runs interpolations on EVERY change, so when your cursor moves to the `def` body, `indent('.')` will become equal indenting of that line, which is `> 0`.

There are at least two ways of fixing issue: (a) use regexp triggers, like this: `snippet "(\s+)d"` and `snippet d`, first one will insert def with self and second will insert def without self; (b) using more complicated interpolation, that will track current state and insert `self` corretly (https://github.com/reconquest/snippets/blob/master/python.snippets#L8-L28); (c) use advanced context snippets (https://github.com/seletskiy/dotfiles/blob/master/.vim/UltiSnips/python.snippets#L119-L125)

BTW, you are using outdated snipMate syntax, please, consider using much more powerful UltiSnips syntax. You can see differences in `:help UltiSnips-syntax`.

**Comment by seletskiy** [comment]
@purpleP: some gif to inspire you (note, that I'm using same trigger `d` again and again and it expand to different snippets; also not, that correct newlines count are inserting automatically in between `def` and `class` declarations):

![a](https://cloud.githubusercontent.com/assets/674812/14072148/d3ea0996-f4de-11e5-9ed8-f0bd6f63c833.gif)
