### ISSUE TITLE
Regular expression snippets not in completion list

### ISSUE THREAD

**Issue by cgathuru** [SirVer/ultisnips#741]
Hi,

I recently wrote some snippets with regular expression triggers which work when expanded but they are not listed when i list all snippets or in the ycm completion. Is this the default behaviour or have I gone wrong somewhere?

**Comment by kiryph** [comment]
I would like to propose an addition to the ultisnips snippet format: add a user-defined completion entry for snippets which use regex in their trigger word, so they are listed. The description should remind the user of the valid regex to the user can take advantage of it.

**Comment by mMontu** [comment]
The regular expression feature is really great. It is sad that this bug is sitting here without any response for more than a year.

**Comment by SirVer** [comment]
Regular expressions are not in the completion list, because Python's `re` module does not support testing for partially matching regular expressions - i.e. you only know when a re matches, when your trigger is complete. Right now, there is unfortunately nothing actionable that can be done about this.

@kiryph suggestion is a workable work around, but it is a new feature that requires design, implementation and test and I have my doubts that manually curated completion reminders are very ergonomic or scalable. If you feel strongly, please open a new issue and link this one in it.

**Comment by SirVer** [comment]
More discussion in #177.

**Comment by kiryph** [comment]
### Regex to allow substring of trigger word

I want to add a note for situations where regexes are only used to allow to enter substrings of a trigger word.

Consider for example the tex snippet `b(egin)?` from https://github.com/honza/vim-snippets/blob/master/UltiSnips/tex.snippets
```
snippet "b(egin)?" "begin{} / end{}" br
\begin{${1:something}}
	${0:${VISUAL}}
\end{$1}
endsnippet
```
The purpose of the regex is that a user can trigger this snippet by entering `b` or `begin`.
I would have written this as "\?b(eg|egin)?".

An alternative can be to allow to expand a snippet already for a unique substring[0,x] of the trigger word.

This might not be identical but in many circumstances quite helpful.

UltiSnips offers this as documented


>  3.5.3 UltiSnips#SnippetsInCurrentScope    *UltiSnips#SnippetsInCurrentScope*
> 
> [...]
> 
> As a second example on how to use this function consider the following
> function and mapping definition:
> 
> ```
> function! ExpandPossibleShorterSnippet()
>   if len(UltiSnips#SnippetsInCurrentScope()) == 1 "only one candidate...
>     let curr_key = keys(UltiSnips#SnippetsInCurrentScope())[0]
>     normal diw
>     exe "normal a" . curr_key
>     exe "normal a "
>     return 1
>   endif
>   return 0
> endfunction
> inoremap <silent><C-L> <C-R>=(ExpandPossibleShorterSnippet()==0?'':UltiSnips#ExpandSnippet())<CR>
> ```
> 
> If the trigger for your snippet is lorem, you type lor, and you have no other
> snippets whose trigger matches lor then hitting <C-L> will expand to whatever
> lorem expands to.
> 
> [...]


This means you would write the above snippet without using a regular expression and therefore would occur in your completion menu

However, if `beg` is already unique in your snippet collection for tex, it can already be expanded.

Also you can enter `b` and trigger it as long as `begin` is alphabetically the first snippet starting with a `b`.

IMHO snippet aliases could also be used but would clutter your menu.

For comparison see
- [gnuplot](http://www.bersch.net/gnuplot-doc/commands.html)
> Note that in most cases unambiguous abbreviations for command names and their options are permissible, i.e., `p f(x) w li` instead of `plot f(x) with lines`.
- Vim follows this in a manually managed way. You can enter `:e` instead of `:edit`. Read `:h 20.2`.

**Comment by SirVer** [comment]
Related to #951. @kiryph I tend to agree that an option to UltiSnips is the least fragile of all the suggested solutions. Do you want to give that a shot?
