### ISSUE TITLE
Allow setting snippet search paths

### ISSUE THREAD

**Issue by lolilolicon** [SirVer/ultisnips#750]
## Request

I want an option to set snippets search paths instead of `runtimepath`.
For example, with

``` vim
let g:UltiSnipsSearchPaths=[$HOME.'/.vim']
```

only `~/.vim/UltiSnips` and `~/.vim/snippets` are searched.
## Reasoning

For anyone using a plugin manager or vim 8 packages, the `runtimepath` list can get very long.
That's why it really makes sense to specify _one_ directory for snippets, as is described in the UltiSnips documentation:

``` vim
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']
```

However, this currently only applies to `UltiSnips` snippets; for `SnipMate` snippets, you can disable them all with `g:UltiSnipsEnableSnipMate = 0`, otherwise **all** `snippets` directories in `runtimepath` are checked and loaded.

Note the proposed option may have some overlapping with `g:UltiSnipsSnippetDirectories`, which interprets absolute paths differently from relative paths. Although nothing _needs_ to be changed here, `g:UltiSnipsSearchPaths` should probably make absolute paths in `g:UltiSnipsSnippetDirectories` obsolete.

**Comment by pnloyd** [comment]
Iv'e run into the same issue, in the sense that I wanted to have a custom directory for SnipMate snippets. (at the time I just believed UltiSnips syntax was just a super set of SnipMates, but now it's apparent that UltiSnips must be aware it is parsing the SnipMates style syntax)

The title of this issue, "Allow setting snippet search paths", isn't really accurately describing the issue here, because you _can_ set search paths. The real issue here is that the paths are assumed  to be UltiSnips syntax (which makes sense), but that leaves no option for the SnipMate path.

Being forced to use the "snippets" directory is problematic if you both want to use SnipMate snippets and also want to ignore some SnipMate snippets that are bundled with a plugin.

As of this point the options are that..

1. You must include all runtimepath/snippets/* or that..
2. You don't use any SnipMate snippets at all

### Possible fix..
`g:UltiSnipsSnipMateDirectories`
A new setting that behaves exactly as `g:UltiSnipsSnippetDirectories` except for SnipMate snippets. It would remain consistent with the current way UltiSnips handles the directory configurations and would be intuitive for users already familiar with the `g:UltiSnipsSnippetDirectories` setting.

**Comment by SirVer** [comment]
@lolilolicon I do not understand your reasoning - so what if you have a long `rtp`? Searching it is quick and only few of them will have an UltiSnips directory anyways.

@pnloyd I understand your use case, but it is so niche that I hesitate considering adding more features into UltiSnips to avoid it. My suggestion is to do `2.` and do not use snipMate snippets at all - the support for snipMate was only ever meant to be transitional.
