### ISSUE TITLE
Expand/JumpForward/JumpBackwardTrigger doesn't work with clang_complete

### ISSUE THREAD

**Issue by adam900710** [SirVer/ultisnips#759]
Only clang_complete is installed, and set

```
let g:clang_snippets=1
let g:clang_snippets_engine="ultisnips"
```

The clang_complete works well, completing the whole function name lile
![2016-09-19 16-14-50](https://cloud.githubusercontent.com/assets/460269/18625936/63697636-7e84-11e6-9ba2-fccb79924863.png)

But, if using `<tab>` to expand the list, it just fails and acts as a normal tab.
![2016-09-19 16-15-02](https://cloud.githubusercontent.com/assets/460269/18626045/12fcabea-7e85-11e6-9f61-36d1c754ea6d.png)

Further more, there is no mapping conflicts for `<tab>`
![2016-09-19 16-18-18](https://cloud.githubusercontent.com/assets/460269/18626047/17c6c476-7e85-11e6-960d-34b767c13921.png)

The problem has been here for a long long long time, so long I have already given up.

**Comment by andreyorst** [comment]
May be related to #681

**Comment by SirVer** [comment]
Cannot reproduce. I've set up YCM for a test a while ago and it has worked for me out of the box as expected at 3a8b0548b3efd01bff0393f8f32228786149806c. If Andre ist right, the bug is already fixed at master.

If not, please provide a fully reproducible example, ideally using the approach explained in https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs or if not possible with a minimal `vimrc` and snippets files and an exact sequence of key strokes that trigger the bug.
