### ISSUE TITLE
Auto-Trigger not working as intended (neovim)

### ISSUE THREAD

**Issue by geratheon** [SirVer/ultisnips#778]
I want to define an (for now) extremely simple Snippet for my vimrc, using the auto-trigger functionality, but it does not work.

I've defined so far:

```
snippet Plug "" bA
Plug '$1'$0
endsnippet
```

As stated before, this does not auto trigger, but I can trigger it manually after typing `Plug`.

Also it does not help to make it a regex triggered snippet like this:

```
snippet "^Plug" "" rA
Plug '$1'$0
endsnippet
```

Since this is a 1:1 copy from the help files I presume this is a bug.

I'm currently on an Elementary OS in a VirtualBox VM with a recently built Neovim v0.1.6.

**Comment by seletskiy** [comment]
@geratheon: I do not support neovim+UltiSnips integration. However, pull requests are welcome.

**Comment by geratheon** [comment]
I just tried again and at least the regex triggering snippet works now on neovim.

**Comment by TheZoq2** [comment]
I have experienced this aswell. It seems like autotriggers only work for triggers that are 1 or 2 characters, but not 3 or more. 

I wouldn't mind looking into fixing it since you don't support neovim but I don't really know where to start searching for the issue. Do you have any pointers to where I could start?

**Comment by TheZoq2** [comment]
I looked into this and it looks like `before = _vim.buf.line_till_cursor` returns one character less than it should whenever youcompleteme is active and shows above 2 characters. I assume it's a neovim or ycm issue and not part of ultisnips because of it.

**Comment by TheZoq2** [comment]
I looked into this myself and found out that this might actually be intended behaviour. `:help TextChangedI` which is what I assume triggers the autoexpansion in neovim says that this event will not be triggered if the completionmenu is open.

**Comment by SirVer** [comment]
This issue was closed due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).
