### ISSUE TITLE
Screencast Episode 1 has no video or text version.

### ISSUE THREAD

**Issue by still-dreaming-1** [SirVer/ultisnips#816]
The link to the screencast Episode one takes you to a page without a video or text version that you could read instead of the video.

**Comment by willbr** [comment]
Try https://www.youtube.com/embed/Zik6u0klD40

The video is blocked because of mixed content. The page is loaded over HTTP**S** but it's trying to load YouTube over HTTP.

https://www.sirver.net/blog/2011/12/30/first-episode-of-ultisnips-screencast/
http://www.youtube.com/embed/Zik6u0klD40

More info:
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

**Comment by still-dreaming-1** [comment]
The YouTube video works, thanks

**Comment by andreyorst** [comment]
duplicate of #851
