### ISSUE TITLE
Python interpolation: if statements with tabstops

### ISSUE THREAD

**Issue by xixa** [SirVer/ultisnips#820]
I wanted my snippet to add a `new` keyword in front of a class name, depending on the name of the class. So I came up with:

``    `!p if t[1] == 'Name': snip.rv = 'new '`Class${1:<name here>}``

It doesn't work. 
But, weirdly enough, if instead of `Name` you'd use `name`, it works!

Is that a bug or am I overlooking something here?

**Comment by SirVer** [comment]
Can't repo, works for me at 43b059bf1c20a1d328b7499c45332d367620c541.  See https://asciinema.org/a/eS3IMrwqJDaqUrTDEZtgbyFZt. 

I see another bug and that is that the snippet is exited because the python interpolation expands, which is of course incorrect. But that is a different bug than the one described in this issue.

Closing as cant repro.
