### ISSUE TITLE
snip not in youcompleteme completion menu, but can troggle when press key

### ISSUE THREAD

**Issue by nothing001** [SirVer/ultisnips#821]
When I use vim editing a file, snip not in youcompleteme completion menu, but can troggle when press key 。

**Comment by z3t0** [comment]
same here, any solutions yet?

**Comment by Anzumana** [comment]
same issue anyone figure this out yet ?

**Comment by andreyorst** [comment]
Since Ultisnips don't need completion menu at all, it's just visualization of snippets that match your input, no wonder that you can expand it. You can have snippets with or without any completion engine. So that's more a question to YCM, why your snippets are not listed, but ultisnips works as intended. I may be wrong, feel fre to reopen the issue.
