### ISSUE TITLE
UltiSnips#SnippetsInCurrentScope() is slow

### ISSUE THREAD

**Issue by balta2ar** [SirVer/ultisnips#827]
Hello. I'm not sure how to provide a minimal reproducible example, but today I've tracked down that ultisnips is the slowest of all sources I have in deoplete (see timestamps on the left):
```
2017-02-22 21:08:19,636 INFO     (deoplete.core) Profile Start: ultisnips
2017-02-22 21:08:20,700 INFO     (deoplete.core) Profile End  : ultisnips                 time=0.0003300000
```
I'm ready to do the necessary steps in my environment to profile and locate the bottleneck, just tell me where and how (I'm no expert at vimscript, though).

NVIM 0.1.7
Latest version of ultisnips and deoplete.
Thanks.

**Comment by balta2ar** [comment]
```
FUNCTION  UltiSnips#SnippetsInCurrentScope()
Called 2 times
Total time:   1.630317
 Self time:   1.630317

count  total (s)   self (s)
    2              0.000030     let g:current_ulti_dict = {}
    2              0.000031     let all = get(a:, 1, 0)
    2              0.000008     if all
                                  let g:current_ulti_dict_info = {}
                                endif
    2              1.630189     exec g:_uspy "UltiSnips_Manager.snippets_in_current_scope(" . all . ")"
    2              0.000023     return g:current_ulti_dict
```

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   20   5.182494   5.064161  provider#python#Call()
    2   1.630317             UltiSnips#SnippetsInCurrentScope()
   13   1.112159   0.003217  textobj#user#plugin()
    1   1.079275   0.119938  <SNR>14_LoadFTPlugin()
   13   1.041409   0.000592  111()
   13   1.040817   0.000235  112()
   13   1.040583   0.000492  <SNR>102_normalize()
   13   1.034545   0.016032  <SNR>102_normalize_property_values()
   12   1.017507   0.123048  <SNR>102_snr_prefix()
    5   0.988560   0.000372  <SNR>161_on_window_changed()
    2   0.967956   0.724445  <SNR>161_init()
 2556   0.894459             <SNR>102_normalize_path()
    4   0.857689   0.000321  jedi#init_python()
    1   0.857367   0.020810  <SNR>207_init_python()
    1   0.836558   0.000037  jedi#force_py_version()
    1   0.836521             jedi#setup_py_version()
    1   0.594609   0.463136  airline#extensions#load()
    1   0.411126   0.000075  chromatica#enable()
    1   0.378793   0.007602  chromatica#initialize()
    1   0.370011   0.030993  chromatica#init#_initialize()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
   20   5.182494   5.064161  provider#python#Call()
    2              1.630317  UltiSnips#SnippetsInCurrentScope()
 2556              0.894459  <SNR>102_normalize_path()
    1              0.836521  jedi#setup_py_version()
    2   0.967956   0.724445  <SNR>161_init()
    1   0.594609   0.463136  airline#extensions#load()
    2   0.342562   0.340757  provider#pythonx#Require()
    1   0.260147   0.237248  nerdtree#loadClassFiles()
    1   0.196856   0.196501  jedi#show_call_signatures()
    1              0.137971  _deoplete()
   12   1.017507   0.123048  <SNR>102_snr_prefix()
    1   1.079275   0.119938  <SNR>14_LoadFTPlugin()
    1   0.118728   0.112663  <SNR>235_toggle_on()
    2   0.073307   0.068054  chromatica#init#_enable()
    1   0.070638   0.064308  <SNR>17_SynSet()
    1   0.148142   0.060486  nerdtree#postSourceActions()
   56              0.059953  <SNR>94_IsInDict()
    1   0.176779   0.053926  <SNR>94_ParseFileAssociationList()
    2              0.053683  <SNR>36_check_interpreter()
   64   0.086631   0.044192  <SNR>274_ParseTagline()
```

The whole profile file:
[vim.12519.7066profile.txt](https://github.com/SirVer/ultisnips/files/794816/vim.12519.7066profile.txt)

**Comment by seletskiy** [comment]
@balta2ar: I guess it's neovim-only issue. If so, I will gladly merge PR which fix it.

**Comment by z3t0** [comment]
I seem to be having a similar issue on vim (not neovim). Will create a new issue once I have some more profiles done.

**Comment by Herz3h** [comment]
I found an issue with ultisnippets (latest) and neovim v0.2.0-59-gadf29ce. When i press **o** in a ruby file (didn't try on other extensions), takes like a second (~800ms) for the new ine to appear : 

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   14   0.119991   0.000725  <SNR>43_append()
   14   0.119266   0.004640  neomru#_append()
    7   0.112286   0.014330  GetRubyIndent()
   28   0.109722   0.001322  28()
    4   0.106990   0.001291  25()
   14   0.081100   0.002172  <SNR>64_PrevNonBlankNonString()
   18   0.080730             <SNR>64_IsInStringOrComment()
    4   0.069118   0.004973  30()
  570   0.066373             <SNR>69_is_file_exist()
    7   0.066171             UltiSnips#TrackChange()
    7   0.065923             provider#python#Call()
    7   0.052449   0.002908  <SNR>64_GetMSL()
  135   0.037753             <SNR>48_Highlight_Matching_Pair()
    4   0.031194   0.000192  <SNR>69_uniq()
    4   0.031002             <SNR>69_uniq_by()
   76   0.008150   0.007530  <SNR>64_Match()
    4   0.005270             <SNR>69_writefile()
    6   0.003645             <SNR>64_IsInString()
    1   0.001827   0.000644  <SNR>64_ExtraBrackets()
   28   0.001410   0.000965  26()
```

full log here : https://pastebin.com/raw/meXcTeRx

I basically tried to add new lines and pressed **gt** few times to switch tabs.

**Comment by seletskiy** [comment]
@Herz3h: I do not see reference to SnippetsInCurrentScope in your log.

**Comment by seletskiy** [comment]
@balta2ar, @Herz3h: can you try branch https://github.com/SirVer/ultisnips/tree/optimize-snippets-in-current-scope?

**Comment by jordwalke** [comment]
I'm seeing this too. In an empty text file (happen to also have mucomplete setup).

**Comment by SirVer** [comment]
This issue was closed due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis.

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).

**Comment by balta2ar** [comment]
@SirVer Thanks for being straightforward about that! Though, could you please elaborate the meaning of "are considered on a best effort basis" expression to a non-native speaker? I think I understand but I'm a bit unsure... Do it mean "we will try our best but we do not guarantee any result"? Is that precise enough?

**Comment by SirVer** [comment]
In the current situation (without a hero caring for Neovim support), it likely means: If it is easy to fix and/or affects core Vim too, we try to work on it. It might get fixed by accident with other bugs but might regress again since it is not tested. It might get fixed by a drive-by contribution that cared about the use case (as long as it is not regressing core vim support). Or it might never get fixed.

This particular issue seems to come through Neovim's design of running out of core and will not get fixed until UltiSnips is converted into an async plugin. There are no current plans of doing so.
