### ISSUE TITLE
Crashes git merge_msg

### ISSUE THREAD

**Issue by x-benclarke** [SirVer/ultisnips#840]
After vim opens and prompts you to write your merge message, I get the following error on every keystroke after I enter insert mode:

Error detected while processing function UltiSnips#TrackChange:
File "<string>", line 1, in <module>
NameError: name 'UltiSnips_Manager' is not defined

**Comment by seletskiy** [comment]
@x-benclarke: Please, provide minimal reproduceable configuration for that error.

**Comment by abair** [comment]
@x-benclarke, I had this same issue.  It's likely that the version of Vim opened by the `git commit` command isn't the same as when you invoke Vim directly.  See issue #958 for a more in depth explanation of what was happening to me and how I fixed it, but the short version is to make sure your $EDITOR environment variable is set to vim: `export EDITOR=vim`

@seletskiy, the issue I mentioned to him describes what I found when fixing this issue for myself.  I'm pointing you at it because I've seen a few similar issues closed and tagged with "can't reproduce".  Any time it's caused by an environment issue, someone with a healthy environment won't be able to reproduce with just a vim config file.
