### ISSUE TITLE
Snippets are not executed

### ISSUE THREAD

**Issue by tobi2006** [SirVer/ultisnips#855]
This is probably just my stupidity, but I cannot get UltiSnips to work properly. I have cloned the repo into my bundle/ folder, and I am using pathogen to launch it. I have created an ftdetect folder in my .vim folder, and have set a symlink: `ln -s ~/.vim/bundle/ultisnips/ftdetect/* ~/.vim/ftdetect/`.

When I go to a .tex file, I can access :UltiSnipsEdit, and I have added the following snippets:

```
snippet frame
\begin{frame}[fragile]
	\frametitle{$1}
	$2
\end{frame}
$0
endsnippet

snippet item
\begin{itemize}
	\item $1
\end{itemize}
$0
endsnippet

snippet i
\item $1
endsnippet
```

These do also come up when I go into another .tex file and try the same. However, none of these seem to execute when I press tab after typing one of the trigger words. These are the corresponding settings in my .vimrc:

```
set runtimepath+="~/.vim/my_snippets"
let g:UltiSnipsUsePythonVersion = 3
let g:UltiSnipsSnippetsDir="~/.vim/my_snippets"
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsEditSplit="vertical"
```

I would be very grateful if someone could have a look at this!

**Comment by costis-t** [comment]
I also have the same problem. Has anything changed? Last time I used snippers it was working fine.
`:verbose imap <tab>` returns

    i  <Tab>       * <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>
            Last set from ~/.vim/plugged/ultisnips/autoload/UltiSnips/map_keys.vim

as it should. My simple `.vimrc` is [here](https://pastebin.com/Mwm12abJ).

**Comment by costis-t** [comment]
Ok, my issue is fixed now, i had messed up my snippet directories. 

@tobi2006 Your snippets work fine for me.
Please ensure that the output of `:verbose imap <tab>` is the correct one, like I mentioned before.

Next, you should have defined some snippet directories. I am not a heavy UltiSnips user, but shouldn't you have set ` let g:UltiSnipsSnippetDirectories=["~/.vim/my_snippets"]` instead of the `g:UltiSnipsSnippetsDir`? For more info type in vim: `:help UltiSnips-snippet-search-path`.

**Comment by andreyorst** [comment]
#948
