### ISSUE TITLE
Does ultisnips support neovim in windows?

### ISSUE THREAD

**Issue by yehuohan** [SirVer/ultisnips#895]
I found recently that 'tab' doesn't work in insert mode for neovim-qt in windows when the plugin SirVer/ultisnips is loaded. Maybe there're some conficts.

**Comment by foxbunny** [comment]
Same here. I've also tried other bindings like C-Tab, but that did not work wither.

**Comment by yehuohan** [comment]
But it's ok in linux -_-||

**Comment by andreyorst** [comment]
Neovim is currently not supported at all. Readme will be updated soon. Because we don't have contributor that can help in supporting neovim, issues related to it will be marked as 'neovim-only' and closed. It will be opened in the future if neovim contributor will appear. You cand read explanations here for now https://github.com/SirVer/ultisnips/issues/901#issuecomment-378378085
