### ISSUE TITLE
Ultisnips can't handle tilda in user snippets path defined in g:UltiSnipsSnippetDirectories

### ISSUE THREAD

**Issue by andreyorst** [SirVer/ultisnips#956]
This is reopen of #948.

Setting
```vim
let g:UltiSnipsSnippetDirectories = ['~/.vim/UltiSnips', 'UltiSnips']
```
Works only patrially. Ultisips command `:UltiSnipsEdit` opens snippet files located in `~/.vim/UltiSnips` correctly. However snippets not visible to plugin itself, because python can only see filles by defining absolute path like so:
```vim
let g:UltiSnipsSnippetDirectories = ['/home/user/.vim/UltiSnips', 'UltiSnips']
```
Wich is not great because one may have same vim configuration across different machines, with different users (home, work, another home machine, etc).

From [python docs](https://docs.python.org/2/library/os.path.html):
> Unlike a unix shell, Python does not do any automatic path expansions. Functions such as expanduser() and expandvars() can be invoked explicitly when an application desires shell-like path expansion. (See also the glob module.)

As I see (correct me if Im wrong, i'm not a python developer) this function: https://github.com/SirVer/ultisnips/blob/662e03602825801ba1e15a66f7bb83f4e9c39f18/pythonx/UltiSnips/snippet/source/file/ulti_snips.py#L29-L54
takes contents of vim variable `UltiSnipsSnippetDirectories`, but path is not expanded properly:
https://github.com/SirVer/ultisnips/blob/662e03602825801ba1e15a66f7bb83f4e9c39f18/pythonx/UltiSnips/snippet/source/file/ulti_snips.py#L33

Maybe something like: 
```python
snippet_dirs = os.path.expanduser(snippet_dirs)
```
should be added in this function?

**Comment by SirVer** [comment]
`b:UltiSnipsSnippetDirectories` should either be 

1. a list of basenames, i.e. `['UltiSnips']` or
2. A single absolute path. You can use $HOME for your home dir: `let g:UltiSnipsSnippetDirectories=$HOME.'/.vim/UltiSnips'`

For setting the path where your snippets are saved, you should set `g:UltiSnipsSnippetsDir`. Please See `:help UltiSnips-snippet-search-path` for details.

This is as documented, I think currently the documented behaviour diverges from the implemented. Please add your thoughts if you see this in #711.

**Comment by andreyorst** [comment]
setting `let g:UltiSnipsSnippetDirectories=`**[**`$HOME.'/.vim/UltiSnips'`**]** worked

**Comment by smancill** [comment]
@SirVer I see no reason to not use `os.path.expanduser` when the list has one element:

https://github.com/SirVer/ultisnips/blob/905e5249246169b6db2bb060e0a2b06eac1890e6/pythonx/UltiSnips/snippet/source/file/ulti_snips.py#L36

**Comment by smancill** [comment]
You misunderstood.

```
In [2]: os.path.isabs(os.path.expanduser('~/snippets_dir'))
Out[2]: True
```

The code should be
```python
if len(snippet_dirs) == 1 and os.path.isabs(os.path.expanduser(snippet_dirs[0])):
```

Nothing will break.

And Vim has its own functions for this exact purpose, like `expand` or `glob`:
```
:echo expand('~/snippets_dir')
/Users/smancill/snippets_dir
```

And this is already supported:
```
let g:UltiSnipsSnippetsDir = '~/.vim/my_snippets'
```

The least surprising thing to do is to support `~` expansion on `g:UltiSnipsSnippeDirectories`. Otherwise UltiSnips fails silently and leads to this kind of issue being opened. I had to read the source to understand why a perfectly valid path wasn't working. The author of this issue did the same, and proposed the same solution.

**Comment by SirVer** [comment]
> Nothing will break.

`~` is a valid character in filepaths in windows and unix. If you suddenly make it a special character there will be a user out there who will be surprised.

> And Vim has its own functions for this exact purpose, like expand or glob:

this is one more argument why UltiSnips should not do it - there are Vim ways of doing it.

> And this is already supported:

yes, I am aware of this inconsistency. I wish it would not be supported there. The inconsistency cannot be removed without breaking backwards compatibility though, which requires a 4.0 release and would still surprise users - since most of them pull from github master. 

I understand your point, but I am not willing to change behaviour in a backwards incompatible way. I disagree with your statement that your suggestion would not break things.

The documentation is up to date, precise and even contains a working example for the use case : https://github.com/SirVer/ultisnips/blob/30e651fb1f342f8a185e7df638d6dd9a72cd6c73/doc/UltiSnips.txt#L555

**Comment by SirVer** [comment]
I relented on this eventually and expand `~` in the path now.
