### ISSUE TITLE
remove autotrigger snippets when using tirgger key manually

### ISSUE THREAD

**Issue by 0mco** [SirVer/ultisnips#993]
When a snippet has option 'A', it will auto-trigger when this snippet matches, this is good. But this snippet should not get triggered when we use trigger key manually since no one will manually expand a snippet that is automatically expanded.
This can happen when the trigger has other meanings, e.g. when using `<tab>` to insert tab.

I use the following snippet to automatically move curser to the middle of `""`, and both my `UltiSnipsExpandTrigger` and `UltiSnipsJumpForwardTrigger` are `<tab>` so I don't need to press arrow key to move the cursor:
```
snippet "" "middle" Ai
"${1:${VISUAL}}"
endsnippet
```
Aafter I type `""`, the cursor is automatically moved to the middle of `""`, if I just need an empty string, I press `<tab>` to jump out of `""`, now this should be `""<cursor>`, then I want to press `<tab>` to insert tab (to write some comment). **The problem is:** instead of inserting tab, the cursor gets back to `"<cursor>"` because it triggers the `""` snippet.
**Expected behavior:**
insert tab

**Actual behavior:**
trigger the `""` snippet

**Steps to reproduce**

set 
```
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
```
in `.vimrc`.

the snippet
```
snippet "" "middle" Ai
"${1:${VISUAL}}"
endsnippet
```
1.
type `""`, you should get `"<curosr>"`
2.
press `<tab>` to jump forward, you sould get `""<cursor>`
3.
press `<tab>`, you will get `"<cursor>"`

**My workaround:**
change
```
        if autotrigger_only:
            all_snippets = [s for s in all_snippets if s.has_option('A')]
```
to
```
        if autotrigger_only:
            all_snippets = [s for s in all_snippets if s.has_option('A')]
        else:
            all_snippets = [s for s in all_snippets if not s.has_option('A')]
```
in `get_matching_snippets`.

-----

- **Operating System**: 
- **Vim Version**: 
- **UltiSnips Version**: 
- **Python inside Vim**: 
- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
I believe the premise of this bug report is an alternative suggested solution to the problem being discussed in #1157. This bug that autotriggers should not execute when the trigger key is pressed, since they should have triggered automatically. The other one suggests that autotriggers should only expand while typing.

I tend to disagree with this suggestion, I see it as unexpected complexity that autotrigger should have expansions rules removed. My expectation is that only the rule is added that they trigger automatically. Also, I feel your problem could be worked around by not overloading the jump and trigger key onto the same key - it is impossible for the snippet engine to read your mind what you want to do in a situation where both are possible. 

My suggestion: use a different key for jumping as for expanding.
